import fs from 'fs';
import { Scheme } from './src/types';

export const womenChildSchemes: Scheme[] = [
  {
    id: 'beti-bachao-beti-padhao-bbbp-scheme',
    title: 'Beti Bachao Beti Padhao (BBBP Girl Child Protection & Education Campaign)',
    code: 'BBBP-MWCD-GIRL-CHILD',
    ministry: 'Ministry of Women and Child Development (MWCD), Govt. of India',
    origin: 'central',
    category: 'Women & Child',
    subCategory: 'Girl Child Education & Protection',
    beneficiaries: ['Children', 'Women', 'Students'],
    benefitValue: 'District Education & Health Grants, Sukanya Samriddhi Account Incentives & Elimination of Gender-Biased Sex Selection',
    benefitNumericMin: 10000,
    benefitNumericMax: 100000,
    description: 'National multi-sectoral initiative aiming to improve Child Sex Ratio (CSR), ensure survival and protection of the girl child, and ensure higher secondary education completion.',
    eligibilityDescription: 'Girl children born in India and their parents/guardians.',
    requiredDocs: ['Girl Child Birth Certificate', 'Parents Aadhaar Card'],
    deadline: 'District Women and Child Development Office / Anganwadi Centres',
    officialWebsiteUrl: 'https://wcd.nic.in',
    rules: { minAge: 0, maxAge: 18, genderConstraint: 'Female' },
    isPopular: true,
    iconName: 'face_3'
  },
  {
    id: 'pradhan-mantri-matru-vandana-yojana-pmmvy',
    title: 'Pradhan Mantri Matru Vandana Yojna (PMMVY Direct Cash Transfer for Pregnant Women)',
    code: 'PMMVY-2-0-MWCD-MATERNITY',
    ministry: 'Ministry of Women and Child Development (MWCD), Govt. of India',
    origin: 'central',
    category: 'Women & Child',
    subCategory: 'Maternal Welfare & Health',
    beneficiaries: ['Women', 'Children'],
    benefitValue: 'Direct Benefit Cash Transfer of ₹5,000 for 1st Child + ₹6,000 for 2nd Child (if Girl Child) directly into Bank Account',
    benefitNumericMin: 5000,
    benefitNumericMax: 11000,
    description: 'Provides financial maternity benefit cash transfers directly to pregnant women and lactating mothers to compensate for wage loss and promote nutritional care.',
    eligibilityDescription: 'Pregnant Women and Lactating Mothers (PW&LM) aged 19+ for first living child and second girl child, belonging to low-income households.',
    requiredDocs: ['Mother and Child Protection (MCP) Smart Card', 'Aadhaar Card', 'Aadhaar Seeded Bank Account Details'],
    deadline: 'PMMVY Official Portal (pmmvy.wcd.gov.in) / Anganwadi Centre',
    officialWebsiteUrl: 'https://pmmvy.wcd.gov.in',
    rules: { minAge: 19, maxAge: 45, genderConstraint: 'Female' },
    isPopular: true,
    iconName: 'pregnant_woman'
  },
  {
    id: 'sukanya-samriddhi-yojana-ssy-girl-savings',
    title: 'Sukanya Samriddhi Yojana (SSY High-Interest Tax-Free Savings Scheme)',
    code: 'SSY-MOF-GIRL-SAVINGS',
    ministry: 'Department of Posts / Ministry of Finance, Govt. of India',
    origin: 'central',
    category: 'Women & Child',
    subCategory: 'Girl Child Education & Wealth',
    beneficiaries: ['Children', 'Women', 'Students'],
    benefitValue: 'Guaranteed 8.2% Tax-Free Interest Rate + 100% Tax Exemption under 80C + Maturity Corpus up to ₹70 Lakh for Girl Higher Education/Marriage',
    benefitNumericMin: 250,
    benefitNumericMax: 150000,
    description: 'Small deposit savings scheme for girl children offering India’s highest tax-free interest rate, buildable with minimum ₹250 annual deposit.',
    eligibilityDescription: 'Parents or legal guardians of a girl child below 10 years of age (maximum 2 girl children per family).',
    requiredDocs: ['Girl Child Birth Certificate', 'Parent/Guardian Aadhaar & PAN Card', 'Address Proof'],
    deadline: 'Post Office / Authorized Public & Private Sector Banks',
    officialWebsiteUrl: 'https://indiapost.gov.in',
    rules: { minAge: 0, maxAge: 10, genderConstraint: 'Female' },
    isPopular: true,
    iconName: 'savings'
  },
  {
    id: 'poshan-abhiyaan-national-nutrition-mission',
    title: 'POSHAN Abhiyaan (National Nutrition Mission for Children & Mothers)',
    code: 'POSHAN-ABHIYAAN-MWCD',
    ministry: 'Ministry of Women and Child Development (MWCD), Govt. of India',
    origin: 'central',
    category: 'Women & Child',
    subCategory: 'Early Childhood Care & Nutrition',
    beneficiaries: ['Children', 'Women'],
    benefitValue: '100% Free Hot Cooked Meals, Take Home Rations (THR), Growth Monitoring & Micronutrient Supplements at Anganwadi Centres',
    benefitNumericMin: 6000,
    benefitNumericMax: 15000,
    description: 'National flagship program reducing stunting, wasting, anemia, and low birth weight among young children (0-6 years), adolescent girls, and pregnant women.',
    eligibilityDescription: 'Children aged 0 to 6 years, pregnant women, lactating mothers, and adolescent girls across India.',
    requiredDocs: ['Poshan Tracker App Registration at Local Anganwadi Centre'],
    deadline: 'Poshan Tracker App (poshantracker.in) / Local Anganwadi Worker',
    officialWebsiteUrl: 'https://poshantracker.in',
    rules: { minAge: 0, maxAge: 6 },
    isPopular: true,
    iconName: 'child_care'
  },
  {
    id: 'mission-vatsalya-child-protection-services',
    title: 'Mission Vatsalya (Child Protection Services & Foster Care Grant)',
    code: 'MISSION-VATSALYA-MWCD',
    ministry: 'Ministry of Women and Child Development (MWCD), Govt. of India',
    origin: 'central',
    category: 'Women & Child',
    subCategory: 'Child Protection & Rehabilitation',
    beneficiaries: ['Children'],
    benefitValue: 'Monthly Financial Sponsorship Grant of ₹4,000 per Child for Foster Care & Non-Institutional Care for Orphans and Vulnerable Children',
    benefitNumericMin: 48000,
    benefitNumericMax: 48000,
    description: 'Ensures a safe, secure environment for children in difficult circumstances, providing foster care monthly grants, institutional care, and emergency helpline (1098).',
    eligibilityDescription: 'Orphans, abandoned children, child laborers, runaway children, and children in conflict with law.',
    requiredDocs: ['District Child Protection Unit (DCPU) Social Investigation Report', 'Birth / Death Certificate of Parents'],
    deadline: 'District Child Protection Unit (DCPU) / Child Welfare Committee (CWC)',
    officialWebsiteUrl: 'https://wcd.nic.in',
    rules: { minAge: 0, maxAge: 18 },
    isPopular: true,
    iconName: 'family_restroom'
  },
  {
    id: 'mission-shakti-sambal-working-women-hostel',
    title: 'Sakhi Niwas (Working Women Hostel Scheme under Mission Shakti)',
    code: 'SAKHI-NIWAS-MISSION-SHAKTI',
    ministry: 'Ministry of Women and Child Development (MWCD), Govt. of India',
    origin: 'central',
    category: 'Women & Child',
    subCategory: 'Women Empowerment & Safe Housing',
    beneficiaries: ['Women', 'Job Seekers', 'Workers'],
    benefitValue: 'Safe, Subsidized Modern Hostel Accommodation with Daycare Crèche for Children in Urban & Industrial Cities',
    benefitNumericMin: 30000,
    benefitNumericMax: 90000,
    description: 'Provides safe, affordable, clean housing accommodation and daycare facilities for working women, single mothers, and female job trainees living away from family.',
    eligibilityDescription: 'Working women earning monthly income up to ₹50,000 (metro cities) or ₹35,000 (other places), single/widowed/divorced women.',
    requiredDocs: ['Employment Proof / Salary Slip', 'Aadhaar Card', 'Passport Photos'],
    deadline: 'Sakhi Niwas Management / District Women Welfare Officer',
    officialWebsiteUrl: 'https://wcd.nic.in',
    rules: { minAge: 18, maxAge: 60, genderConstraint: 'Female' },
    isPopular: false,
    iconName: 'apartment'
  },
  {
    id: 'one-stop-centre-sakhi-scheme-women-helpline',
    title: 'One Stop Centre (Sakhi Scheme) & Women Helpline 181',
    code: 'SAKHI-ONE-STOP-CENTRE-MWCD',
    ministry: 'Ministry of Women and Child Development (MWCD), Govt. of India',
    origin: 'central',
    category: 'Women & Child',
    subCategory: 'Women Protection & Emergency Assistance',
    beneficiaries: ['Women'],
    benefitValue: '100% Free Emergency Medical First-Aid, Legal Counselling, Police Facilitation, Psychological Therapy & 5-Day Temporary Shelter',
    benefitNumericMin: 10000,
    benefitNumericMax: 50000,
    description: 'Integrated 24/7 support center in every district providing immediate emergency medical, legal, and psychological help to women affected by violence or distress.',
    eligibilityDescription: 'All women and young girls experiencing physical, domestic, sexual, or economic violence/distress.',
    requiredDocs: ['No mandatory documents required for immediate emergency assistance'],
    deadline: '24/7 Toll-Free Women Helpline: 181 / Nearest District Hospital OSC',
    officialWebsiteUrl: 'https://wcd.nic.in',
    rules: { minAge: 0, maxAge: 100, genderConstraint: 'Female' },
    isPopular: true,
    iconName: 'support_agent'
  },
  {
    id: 'swadhar-greh-scheme-destitute-women-shelter',
    title: 'Swadhar Greh Scheme (Rehabilitation & Shelter for Women in Difficult Circumstances)',
    code: 'SWADHAR-GREH-MWCD-SHELTER',
    ministry: 'Ministry of Women and Child Development (MWCD), Govt. of India',
    origin: 'central',
    category: 'Women & Child',
    subCategory: 'Women Empowerment & Rehabilitation',
    beneficiaries: ['Women'],
    benefitValue: '100% Free Food, Shelter, Clothing, Medical Treatment & Vocational Skill Rehabilitation Training for Up to 3 Years',
    benefitNumericMin: 36000,
    benefitNumericMax: 100000,
    description: 'Provides free shelter, nutrition, healthcare, legal assistance, and vocational training to homeless women, widows, released female prisoners, and trafficking survivors.',
    eligibilityDescription: 'Destitute women, deserted wives, survivors of domestic violence or trafficking aged 18 and above.',
    requiredDocs: ['Self-Declaration / District Magistrate or Police Recommendation'],
    deadline: 'District Social Welfare Office / Swadhar Greh Shelter Home',
    officialWebsiteUrl: 'https://wcd.nic.in',
    rules: { minAge: 18, maxAge: 70, genderConstraint: 'Female' },
    isPopular: false,
    iconName: 'house'
  },
  {
    id: 'palna-national-creche-scheme-child-care',
    title: 'Palna Scheme (National Crèche Scheme for Children of Working Mothers)',
    code: 'PALNA-CRECHE-SCHEME-MWCD',
    ministry: 'Ministry of Women and Child Development (MWCD), Govt. of India',
    origin: 'central',
    category: 'Women & Child',
    subCategory: 'Early Childhood Care & Daycare',
    beneficiaries: ['Children', 'Women', 'Workers'],
    benefitValue: '100% Free / Nominal Daycare Crèche Care (8 Hours/Day), Supplementary Nutrition, Immunization & Early Learning for Children',
    benefitNumericMin: 12000,
    benefitNumericMax: 30000,
    description: 'Provides safe daycare crèche services for young children (6 months to 6 years) of working mothers, enabling mothers to pursue employment without sacrificing child care.',
    eligibilityDescription: 'Working women in formal and informal sectors with children aged 6 months to 6 years.',
    requiredDocs: ['Mother Employment Proof', 'Child Birth Certificate / Immunization Card', 'Aadhaar Card'],
    deadline: 'Nearest Anganwadi cum Crèche Centre / WCD Portal',
    officialWebsiteUrl: 'https://wcd.nic.in',
    rules: { minAge: 0, maxAge: 6 },
    isPopular: true,
    iconName: 'child_friendly'
  },
  {
    id: 'mahila-e-haat-women-entrepreneur-marketing',
    title: 'Mahila E-Haat (Online Digital Marketing Platform for Female Entrepreneurs)',
    code: 'MAHILA-E-HAAT-MWCD-RMK',
    ministry: 'Rashtriya Mahila Kosh (RMK) / MWCD',
    origin: 'central',
    category: 'Women & Child',
    subCategory: 'Women Empowerment & Entrepreneurship',
    beneficiaries: ['Women', 'Entrepreneurs', 'Workers'],
    benefitValue: '100% Free Direct Buyer-to-Seller Digital E-Commerce Marketplace Listing with Zero Commission',
    benefitNumericMin: 15000,
    benefitNumericMax: 100000,
    description: 'Direct online digital marketing platform leveraging e-commerce for individual female entrepreneurs, SHGs, and women NGOs to sell handcrafted goods and garments.',
    eligibilityDescription: 'Women entrepreneurs, women-led Self Help Groups (SHGs), and female artisans aged 18+.',
    requiredDocs: ['Aadhaar Card', 'Bank Passbook', 'Product Photographs'],
    deadline: 'Mahila E-Haat Online Portal',
    officialWebsiteUrl: 'https://wcd.nic.in',
    rules: { minAge: 18, maxAge: 70, genderConstraint: 'Female' },
    isPopular: false,
    iconName: 'storefront'
  },
  {
    id: 'up-mukhyamantri-kanya-sumangala-yojana',
    title: 'UP Mukhyamantri Kanya Sumangala Yojana (Financial Cash Grant for Girls)',
    code: 'UP-KANYA-SUMANGALA-YOJANA',
    ministry: 'Women and Child Development Department, Govt. of UP',
    origin: 'state',
    stateName: 'Uttar Pradesh',
    category: 'Women & Child',
    subCategory: 'Girl Child Education & Health',
    beneficiaries: ['Children', 'Students', 'Women'],
    benefitValue: 'Step-by-Step Financial Grant Totaling ₹25,000 Transferred across 6 Milestones (Birth, Vaccination, Class 1, Class 6, Class 9, Degree/Diploma)',
    benefitNumericMin: 25000,
    benefitNumericMax: 25000,
    description: 'Provides ₹25,000 total cash transfers to girls in UP from birth through graduation to promote female birth ratio, vaccination, and higher education.',
    eligibilityDescription: 'UP domicile girl children born in families with total annual family income up to ₹3,00,000 (maximum 2 girls per family).',
    requiredDocs: ['UP Domicile Certificate', 'Family Income Certificate', 'Girl Birth Certificate / School Admission Proof', 'Bank Account'],
    deadline: 'MKSY Official Portal (mksy.up.gov.in)',
    officialWebsiteUrl: 'https://mksy.up.gov.in',
    rules: { minAge: 0, maxAge: 25, maxAnnualIncome: 300000, genderConstraint: 'Female', statesAllowed: ['Uttar Pradesh'] },
    isPopular: true,
    iconName: 'card_giftcard'
  },
  {
    id: 'up-bal-seva-yojana-covid-orphans',
    title: 'UP Mukhyamantri Bal Seva Yojana (Monthly Financial Aid for Orphan Children)',
    code: 'UP-BAL-SEVA-YOJANA-CHILD',
    ministry: 'Women and Child Development Department, Govt. of UP',
    origin: 'state',
    stateName: 'Uttar Pradesh',
    category: 'Women & Child',
    subCategory: 'Child Protection & Monthly Stipend',
    beneficiaries: ['Children', 'Students'],
    benefitValue: 'Monthly Cash Transfer Allowance of ₹4,000 per Child until Age 18 + Free Tablet/Laptop for Higher Education',
    benefitNumericMin: 48000,
    benefitNumericMax: 48000,
    description: 'Provides monthly ₹4,000 financial support to children who lost one or both parents to COVID-19 or other fatal reasons in UP.',
    eligibilityDescription: 'Orphan children or children who lost breadwinning parent residing in UP aged 0 to 18 years.',
    requiredDocs: ['UP Domicile Certificate', 'Death Certificate of Parent(s)', 'Aadhaar Card', 'Guardian Bank Passbook'],
    deadline: 'District Probation Officer UP / WCD Portal',
    officialWebsiteUrl: 'https://womenchild.up.gov.in',
    rules: { minAge: 0, maxAge: 18, statesAllowed: ['Uttar Pradesh'] },
    isPopular: true,
    iconName: 'family_restroom'
  },
  {
    id: 'mh-majhi-kanya-bhagyalashmi-yojana',
    title: 'Majhi Kanya Bhagyashree Scheme (Financial Fixed Deposit Grant for Girl Child)',
    code: 'MH-MAJHI-KANYA-BHAGYASHREE',
    ministry: 'Women and Child Development Department, Govt. of Maharashtra',
    origin: 'state',
    stateName: 'Maharashtra',
    category: 'Women & Child',
    subCategory: 'Girl Child Education & Protection',
    beneficiaries: ['Children', 'Women'],
    benefitValue: 'Direct Financial Fixed Deposit of ₹50,000 for Single Girl Child or ₹25,000 each for Two Girl Children',
    benefitNumericMin: 25000,
    benefitNumericMax: 50000,
    description: 'Encourages family planning and girl child education in Maharashtra by depositing up to ₹50,000 in bank fixed deposit in the girl’s name.',
    eligibilityDescription: 'Maharashtra resident families with annual income up to ₹7.5 Lakh who undergo sterilization after birth of 1 or 2 girl children.',
    requiredDocs: ['Maharashtra Domicile', 'Sterilization Certificate', 'Girl Birth Certificate', 'Income Certificate'],
    deadline: 'District Women & Child Development Officer Maharashtra',
    officialWebsiteUrl: 'https://womenchild.maharashtra.gov.in',
    rules: { minAge: 0, maxAge: 18, maxAnnualIncome: 750000, genderConstraint: 'Female', statesAllowed: ['Maharashtra'] },
    isPopular: true,
    iconName: 'savings'
  },
  {
    id: 'tn-chief-ministers-girl-child-protection-scheme',
    title: 'TN Chief Minister’s Girl Child Protection Scheme (Fixed Deposit Grant)',
    code: 'TN-GIRL-CHILD-PROTECTION-SCHEME',
    ministry: 'Social Welfare and Women Empowerment Dept, Govt. of Tamil Nadu',
    origin: 'state',
    stateName: 'Tamil Nadu',
    category: 'Women & Child',
    subCategory: 'Girl Child Education & Wealth',
    beneficiaries: ['Children', 'Students', 'Women'],
    benefitValue: 'Fixed Deposit Certificate of ₹50,000 for One Girl Child or ₹25,000 each for Two Girl Children + Monthly Incentive of ₹150',
    benefitNumericMin: 25000,
    benefitNumericMax: 50000,
    description: 'Deposits state funds in Power Finance Corporation in the name of the girl child, maturing with interest when she turns 18 for college education.',
    eligibilityDescription: 'Tamil Nadu resident families with 1 or 2 girl children and no male child, family annual income below ₹72,000, parent undergoing sterilization.',
    requiredDocs: ['TN Smart Ration Card', 'Sterilization Certificate', 'Income Certificate', 'Girl Birth Certificate'],
    deadline: 'District Social Welfare Officer Tamil Nadu',
    officialWebsiteUrl: 'https://tn.gov.in',
    rules: { minAge: 0, maxAge: 18, maxAnnualIncome: 72000, genderConstraint: 'Female', statesAllowed: ['Tamil Nadu'] },
    isPopular: true,
    iconName: 'card_giftcard'
  },
  {
    id: 'ka-bhagyalakshmi-scheme-lic-bond',
    title: 'Karnataka Bhagyalakshmi Scheme (Financial LIC Sukanya Insurance Bond)',
    code: 'KA-BHAGYALAKSHMI-SCHEME-LIC',
    ministry: 'Department of Women and Child Development, Govt. of Karnataka',
    origin: 'state',
    stateName: 'Karnataka',
    category: 'Women & Child',
    subCategory: 'Girl Child Protection & Wealth',
    beneficiaries: ['Children', 'Women'],
    benefitValue: 'Financial LIC Security Bond Maturing to ₹1,00,000 when the Girl Child Attains 18 Years + Health Insurance Cover up to ₹25,000/Year',
    benefitNumericMin: 100000,
    benefitNumericMax: 100000,
    description: 'Provides a guaranteed ₹1 Lakh maturity bond for BPL girl children in Karnataka to ensure financial independence upon reaching 18 years.',
    eligibilityDescription: 'Girl children born in BPL families in Karnataka (up to 2 girl children per family registered within 1 year of birth).',
    requiredDocs: ['Karnataka BPL Ration Card', 'Girl Child Birth Certificate', 'Aadhaar Card'],
    deadline: 'Seva Sindhu Portal / Anganwadi Centre Karnataka',
    officialWebsiteUrl: 'https://dwcd.karnataka.gov.in',
    rules: { minAge: 0, maxAge: 18, genderConstraint: 'Female', statesAllowed: ['Karnataka'] },
    isPopular: true,
    iconName: 'verified'
  },
  {
    id: 'ts-kCR-kit-and-arogya-laxmi-scheme',
    title: 'KCR Kit Scheme & Arogya Lakshmi Nutritional Meal Scheme',
    code: 'TS-KCR-KIT-MATERNITY-GRANT',
    ministry: 'Department of Women, Children, Disabled and Senior Citizens, Govt. of Telangana',
    origin: 'state',
    stateName: 'Telangana',
    category: 'Women & Child',
    subCategory: 'Maternal Welfare & Infant Care',
    beneficiaries: ['Women', 'Children'],
    benefitValue: 'Direct Financial Cash Benefit of ₹12,000 (Boy Child) or ₹13,000 (Girl Child) in 4 Installments + 16-Item Baby KCR Kit Box',
    benefitNumericMin: 12000,
    benefitNumericMax: 13000,
    description: 'Provides financial maternity support and a complete baby care kit (clothes, soap, mosquito net, toys, baby oil) to pregnant women delivering in government hospitals.',
    eligibilityDescription: 'Pregnant women delivering up to 2 live births in government hospitals in Telangana.',
    requiredDocs: ['Aadhaar Card', 'Mother MCP Smart Card', 'Telangana Residential Proof', 'Bank Account Details'],
    deadline: 'KCR Kit Official Portal (kcrkit.telangana.gov.in) / ANM Officer',
    officialWebsiteUrl: 'https://kcrkit.telangana.gov.in',
    rules: { minAge: 18, maxAge: 45, genderConstraint: 'Female', statesAllowed: ['Telangana'] },
    isPopular: true,
    iconName: 'child_friendly'
  },
  {
    id: 'ap-ysr-sampoorna-poshana-plus',
    title: 'YSR Sampoorna Poshana Plus (Free Super Nutritional Food for Mothers & Toddlers)',
    code: 'AP-YSR-SAMPOORNA-POSHANA',
    ministry: 'Department of Women, Children, Differently Abled & Senior Citizens, Govt. of AP',
    origin: 'state',
    stateName: 'Andhra Pradesh',
    category: 'Women & Child',
    subCategory: 'Maternal Welfare & Nutrition',
    beneficiaries: ['Women', 'Children'],
    benefitValue: '100% Free Take-Home Ration (Milk, Eggs, Fortified Flour, Chana, Dates, Jaggery) Delivered Monthly to Pregnant Mothers & Children',
    benefitNumericMin: 10000,
    benefitNumericMax: 20000,
    description: 'Combats anemia and malnutrition among pregnant women, lactating mothers, and infants across 77 scheduled tribal and rural mandals in AP.',
    eligibilityDescription: 'Pregnant women, lactating mothers, and children aged 6 to 72 months in AP.',
    requiredDocs: ['AP YSR Rice Card', 'Anganwadi Registration Number'],
    deadline: 'YSR Sampoorna Poshana App / Local Anganwadi Worker',
    officialWebsiteUrl: 'https://wdcw.ap.gov.in',
    rules: { minAge: 0, maxAge: 45, statesAllowed: ['Andhra Pradesh'] },
    isPopular: true,
    iconName: 'restaurant'
  },
  {
    id: 'wb-kanyashree-prakalpa-scheme-k1-k2-k3',
    title: 'Kanyashree Prakalpa (K1, K2 & K3 Financial Cash Grants for Girl Students)',
    code: 'WB-KANYASHREE-PRAKALPA-K2',
    ministry: 'Department of Women & Child Development and Social Welfare, Govt. of West Bengal',
    origin: 'state',
    stateName: 'West Bengal',
    category: 'Women & Child',
    subCategory: 'Girl Child Education & Protection',
    beneficiaries: ['Students', 'Women'],
    benefitValue: 'Annual Educational Scholarship of ₹1,000 (K1: Age 13-18) + Direct One-Time Cash Grant of ₹25,000 (K2: Age 18 Unmarried) + PG Fellowship (K3)',
    benefitNumericMin: 1000,
    benefitNumericMax: 25000,
    description: 'Internationally UN-awarded scheme incentivizing girls in WB to stay in school, complete secondary education, and delay marriage until 18.',
    eligibilityDescription: 'Unmarried girl students studying in Class 8th to 12th or pursuing higher education in West Bengal with family income up to ₹1.2 Lakh.',
    requiredDocs: ['Unmarried Certificate', 'School Enrollment Proof', 'WB Residential Proof', 'Bank Passbook Details'],
    deadline: 'Kanyashree Portal (wbkanyashree.gov.in) / School Headmaster',
    officialWebsiteUrl: 'https://wbkanyashree.gov.in',
    rules: { minAge: 13, maxAge: 25, maxAnnualIncome: 120000, genderConstraint: 'Female', requiresStudent: true, statesAllowed: ['West Bengal'] },
    isPopular: true,
    iconName: 'school'
  },
  {
    id: 'gj-vhali-dikri-yojana-girl-child-grant',
    title: 'Vhali Dikri Yojana (Financial Assistance Grant Totaling ₹1,10,000 for Girls)',
    code: 'GJ-VHALI-DIKRI-YOJANA',
    ministry: 'Women and Child Development Department, Govt. of Gujarat',
    origin: 'state',
    stateName: 'Gujarat',
    category: 'Women & Child',
    subCategory: 'Girl Child Education & Wealth',
    beneficiaries: ['Children', 'Students', 'Women'],
    benefitValue: 'Cash Grant of ₹4,000 (Class 1) + ₹6,000 (Class 9) + ₹1,00,000 Financial Grant on Attaining 18 Years for Higher Studies/Marriage',
    benefitNumericMin: 110000,
    benefitNumericMax: 110000,
    description: 'Provides ₹1,10,000 cumulative financial assistance to first and second girl children in Gujarat to prevent female foeticide and promote education.',
    eligibilityDescription: 'Girl children born in Gujarat families with annual family income up to ₹2,00,000.',
    requiredDocs: ['Gujarat Domicile Certificate', 'Girl Birth Certificate', 'Income Certificate', 'Aadhaar Card'],
    deadline: 'e-Samaj Kalyan Portal Gujarat (esamajkalyan.gujarat.gov.in)',
    officialWebsiteUrl: 'https://esamajkalyan.gujarat.gov.in',
    rules: { minAge: 0, maxAge: 18, maxAnnualIncome: 200000, genderConstraint: 'Female', statesAllowed: ['Gujarat'] },
    isPopular: true,
    iconName: 'card_giftcard'
  },
  {
    id: 'rj-rajsree-yojana-girl-child-grant',
    title: 'Mukhyamantri Rajsree Yojana (Financial Cash Grant Totaling ₹50,000 for Girls)',
    code: 'RJ-RAJSRRE-YOJANA-GIRL',
    ministry: 'Women and Child Development Department, Govt. of Rajasthan',
    origin: 'state',
    stateName: 'Rajasthan',
    category: 'Women & Child',
    subCategory: 'Girl Child Education & Health',
    beneficiaries: ['Children', 'Students', 'Women'],
    benefitValue: 'Financial Cash Transfer Totaling ₹50,000 Paid across 6 Installments from Birth up to Class 12th Graduation',
    benefitNumericMin: 50000,
    benefitNumericMax: 50000,
    description: 'Offers ₹50,000 direct benefit cash transfers in 6 stages to girls born in Rajasthan to ensure institutional delivery, vaccination, and school completion.',
    eligibilityDescription: 'Girl children born in institutional deliveries in Rajasthan government/empaneled hospitals.',
    requiredDocs: ['Jan Aadhaar Card', 'Institutional Delivery Certificate', 'Girl Birth Certificate', 'Aadhaar Card'],
    deadline: 'PCHFC Portal Rajasthan / Anganwadi Centre',
    officialWebsiteUrl: 'https://rajpustahar.rajasthan.gov.in',
    rules: { minAge: 0, maxAge: 18, genderConstraint: 'Female', statesAllowed: ['Rajasthan'] },
    isPopular: true,
    iconName: 'payments'
  },
  {
    id: 'kl-kathortham-and-snehapoorvam-scholarship',
    title: 'Snehapoorvam Scheme (Financial Assistance for Orphan & Vulnerable Children)',
    code: 'KL-SNEHAPOORVAM-SCHOLARSHIP',
    ministry: 'Social Security Mission / Social Justice Dept, Govt. of Kerala',
    origin: 'state',
    stateName: 'Kerala',
    category: 'Women & Child',
    subCategory: 'Child Protection & Education',
    beneficiaries: ['Children', 'Students'],
    benefitValue: 'Monthly Financial Allowance of ₹300 (Class 1-5), ₹500 (Class 6-10), ₹750 (Class 11-12) & ₹1,000 (Degree)',
    benefitNumericMin: 3600,
    benefitNumericMax: 12000,
    description: 'Provides monthly educational financial support to orphan children living with relatives or guardians in Kerala.',
    eligibilityDescription: 'Orphan children or children who lost both parents/father/mother residing in Kerala belonging to BPL households.',
    requiredDocs: ['Death Certificate of Parents', 'Kerala BPL Certificate', 'School Attendance Proof'],
    deadline: 'KSSM Official Portal (socialsecuritymission.kerala.gov.in)',
    officialWebsiteUrl: 'https://socialsecuritymission.kerala.gov.in',
    rules: { minAge: 5, maxAge: 21, requiresStudent: true, statesAllowed: ['Kerala'] },
    isPopular: true,
    iconName: 'school'
  },
  {
    id: 'od-subhadra-yojana-women-cash-voucher',
    title: 'SUBHADRA Yojana (Annual Financial Cash Voucher of ₹10,000 for Women)',
    code: 'OD-SUBHADRA-YOJANA-WOMEN',
    ministry: 'Women and Child Development Department, Govt. of Odisha',
    origin: 'state',
    stateName: 'Odisha',
    category: 'Women & Child',
    subCategory: 'Women Empowerment & Cash Assistance',
    beneficiaries: ['Women', 'Rural Citizens'],
    benefitValue: 'Direct Cash Benefit Transfer of ₹10,000 Per Year (Paid in 2 Installments of ₹5,000 on Rakhi Purnima & Women’s Day) for 5 Years Totaling ₹50,000',
    benefitNumericMin: 10000,
    benefitNumericMax: 50000,
    description: 'Odisha’s flagship women empowerment scheme providing ₹50,000 total cash assistance directly to over 1 crore eligible female househeads.',
    eligibilityDescription: 'Women residents of Odisha aged 21 to 60 covered under NFSA/SFSS or low-income households.',
    requiredDocs: ['Aadhaar Card', 'Odisha Ration Card', 'Aadhaar Seeded Bank Passbook'],
    deadline: 'SUBHADRA Portal (subhadra.odisha.gov.in) / Mo Seba Kendra',
    officialWebsiteUrl: 'https://subhadra.odisha.gov.in',
    rules: { minAge: 21, maxAge: 60, genderConstraint: 'Female', statesAllowed: ['Odisha'] },
    isPopular: true,
    iconName: 'savings'
  },
  {
    id: 'pb-mai-bhago-vidya-scheme-free-bicycles',
    title: 'Mai Bhago Vidya Scheme (Free Bicycles for High School Girl Students)',
    code: 'PB-MAI-BHAGO-FREE-BICYCLES',
    ministry: 'Department of Social Security and Women & Child Development, Govt. of Punjab',
    origin: 'state',
    stateName: 'Punjab',
    category: 'Women & Child',
    subCategory: 'Girl Child Education & Mobility',
    beneficiaries: ['Students', 'Women'],
    benefitValue: '100% Free Sturdy Bicycle Distributed to Girl Students in Classes 9th, 10th, 11th & 12th',
    benefitNumericMin: 4000,
    benefitNumericMax: 5000,
    description: 'Distributes free bicycles to high school girl students in Punjab government schools to reduce dropouts and promote female education.',
    eligibilityDescription: 'Girl students studying in Class 9 to 12 in Punjab government schools.',
    requiredDocs: ['School ID Card / Principal Certificate'],
    deadline: 'Punjab Social Security Dept / School Headmaster',
    officialWebsiteUrl: 'https://sswcd.punjab.gov.in',
    rules: { minAge: 13, maxAge: 18, genderConstraint: 'Female', requiresStudent: true, statesAllowed: ['Punjab'] },
    isPopular: true,
    iconName: 'pedal_bike'
  },
  {
    id: 'hr-laadli-social-security-allowance-scheme',
    title: 'Haryana Laadli Social Security Allowance Scheme (Monthly Pension for Parents of Girls)',
    code: 'HR-LAADLI-PENSION-SCHEME',
    ministry: 'Department of Social Justice and Empowerment, Govt. of Haryana',
    origin: 'state',
    stateName: 'Haryana',
    category: 'Women & Child',
    subCategory: 'Girl Child Protection & Family Pension',
    beneficiaries: ['Senior Citizens', 'Women', 'Workers'],
    benefitValue: 'Monthly Financial Pension Allowance of ₹3,000 for Parents Having Only Daughter(s)',
    benefitNumericMin: 36000,
    benefitNumericMax: 36000,
    description: 'Provides monthly financial pension of ₹3,000 to families in Haryana having only female child/children upon parent turning 45 years.',
    eligibilityDescription: 'Parents residing in Haryana for 15+ years having only girl child/children upon father/mother completing 45 years.',
    requiredDocs: ['Haryana Family ID (PPP)', 'Self-Declaration of Only Daughter(s)', 'Aadhaar Card'],
    deadline: 'SARAL Haryana Portal (saralharyana.gov.in)',
    officialWebsiteUrl: 'https://saralharyana.gov.in',
    rules: { minAge: 45, maxAge: 60, statesAllowed: ['Haryana'] },
    isPopular: true,
    iconName: 'family_restroom'
  },
  {
    id: 'mp-ladli-behna-yojana-monthly-cash-transfer',
    title: 'MP Mukhyamantri Ladli Behna Yojana (Monthly Cash Transfer of ₹1,250)',
    code: 'MP-LADLI-BEHNA-YOJANA-CASH',
    ministry: 'Women and Child Development Department, Govt. of MP',
    origin: 'state',
    stateName: 'Madhya Pradesh',
    category: 'Women & Child',
    subCategory: 'Women Empowerment & Financial Independence',
    beneficiaries: ['Women', 'Rural Citizens'],
    benefitValue: 'Direct Benefit Transfer (DBT) Cash Transfer of ₹1,250 on the 10th of Every Month (₹15,000/Year) into Female Bank Accounts',
    benefitNumericMin: 15000,
    benefitNumericMax: 15000,
    description: 'Madhya Pradesh’s mega cash transfer scheme empowering 1.25 crore married, widowed, divorced, or deserted women with monthly financial dignity.',
    eligibilityDescription: 'Married, widowed, divorced, or abandoned women aged 21 to 60 residing in MP with family annual income under ₹2.5 Lakh.',
    requiredDocs: ['MP Samagra Family ID', 'Aadhaar Card', 'Aadhaar Seeded Bank Account Details'],
    deadline: 'Ladli Behna Portal (cmladlibehna.mp.gov.in) / Gram Panchayat Camp',
    officialWebsiteUrl: 'https://cmladlibehna.mp.gov.in',
    rules: { minAge: 21, maxAge: 60, maxAnnualIncome: 250000, genderConstraint: 'Female', statesAllowed: ['Madhya Pradesh'] },
    isPopular: true,
    iconName: 'savings'
  },
  {
    id: 'mp-ladli-lakshmi-yojana-2-0-bond',
    title: 'MP Ladli Lakshmi Yojana 2.0 (Financial Fixed Deposit Bond Totaling ₹1,43,000)',
    code: 'MP-LADLI-LAKSHMI-2-0-BOND',
    ministry: 'Women and Child Development Department, Govt. of MP',
    origin: 'state',
    stateName: 'Madhya Pradesh',
    category: 'Women & Child',
    subCategory: 'Girl Child Education & Protection',
    beneficiaries: ['Children', 'Students', 'Women'],
    benefitValue: 'Financial Fixed Assurance Bond Totaling ₹1,43,000 + College Admission Incentive Grant of ₹25,000 for Higher Education',
    benefitNumericMin: 143000,
    benefitNumericMax: 143000,
    description: 'Pioneer girl child scheme paying scheduled milestone grants (Class 6, 9, 11, 12) and ₹1 Lakh lump-sum upon girl turning 21 years.',
    eligibilityDescription: 'Girl children born in MP residing families who register at local Anganwadi within 1 year of birth.',
    requiredDocs: ['MP Samagra ID', 'Girl Child Birth Certificate', 'Anganwadi Registration Number'],
    deadline: 'Ladli Lakshmi Portal (ladlilaxmi.mp.gov.in)',
    officialWebsiteUrl: 'https://ladlilaxmi.mp.gov.in',
    rules: { minAge: 0, maxAge: 21, genderConstraint: 'Female', statesAllowed: ['Madhya Pradesh'] },
    isPopular: true,
    iconName: 'verified'
  },
  {
    id: 'br-mukhyamantri-kanya-utthans-yojana',
    title: 'Bihar Mukhyamantri Kanya Utthan Yojana (Financial Grant Totaling ₹54,100)',
    code: 'BR-KANYA-UTTHAN-YOJANA-50K',
    ministry: 'Social Welfare & Education Department, Govt. of Bihar',
    origin: 'state',
    stateName: 'Bihar',
    category: 'Women & Child',
    subCategory: 'Girl Child Education & Protection',
    beneficiaries: ['Children', 'Students', 'Women'],
    benefitValue: 'Direct Cash Transfer Totaling ₹54,100 from Birth to Graduation (₹2,000 Birth, ₹1,000 Aadhar, ₹2,000 Immunization, ₹10,000 12th Pass, ₹50,000 Graduate Pass)',
    benefitNumericMin: 54100,
    benefitNumericMax: 54100,
    description: 'Provides ₹50,000 cash reward directly to every girl student in Bihar upon passing Bachelor’s graduation degree from any recognized college.',
    eligibilityDescription: 'Unmarried girl students residing in Bihar passing 12th standard or graduation degree.',
    requiredDocs: ['Bihar Residential Certificate', 'Graduation Marksheet / Admit Card', 'Aadhaar Card', 'Bank Passbook'],
    deadline: 'Medhasoft Bihar Portal (medhasoft.bih.nic.in)',
    officialWebsiteUrl: 'https://medhasoft.bih.nic.in',
    rules: { minAge: 0, maxAge: 25, genderConstraint: 'Female', statesAllowed: ['Bihar'] },
    isPopular: true,
    iconName: 'school'
  },
  {
    id: 'cg-mahtari-vandan-yojana-monthly-cash-transfer',
    title: 'CG Mahtari Vandan Yojana (Monthly Direct Cash Assistance of ₹1,000 for Women)',
    code: 'CG-MAHTARI-VANDAN-YOJANA',
    ministry: 'Women and Child Development Department, Govt. of Chhattisgarh',
    origin: 'state',
    stateName: 'Chhattisgarh',
    category: 'Women & Child',
    subCategory: 'Women Empowerment & Cash Assistance',
    beneficiaries: ['Women', 'Rural Citizens'],
    benefitValue: 'Direct Benefit Transfer (DBT) Cash Assistance of ₹1,000 Per Month (₹12,000/Year) into Married Women’s Bank Account',
    benefitNumericMin: 12000,
    benefitNumericMax: 12000,
    description: 'Provides ₹1,000 monthly financial assistance to 70+ lakh married women across Chhattisgarh to ensure health, nutrition, and financial independence.',
    eligibilityDescription: 'Married, widowed, divorced, or abandoned women aged 21 and above residing in Chhattisgarh.',
    requiredDocs: ['Chhattisgarh Domicile Certificate', 'Marriage Certificate / Affidavit', 'Aadhaar Card', 'Bank Account Details'],
    deadline: 'Mahtari Vandan Portal (mahtarivandan.cgstate.gov.in)',
    officialWebsiteUrl: 'https://mahtarivandan.cgstate.gov.in',
    rules: { minAge: 21, maxAge: 65, genderConstraint: 'Female', statesAllowed: ['Chhattisgarh'] },
    isPopular: true,
    iconName: 'savings'
  },
  {
    id: 'jh-mukhyamantri-maiyna-sammaan-yojana',
    title: 'Jharkhand Mukhyamantri Maiyna Sammaan Yojana (Monthly ₹1,000 for Women)',
    code: 'JH-MAIYNA-SAMMAAN-YOJANA',
    ministry: 'Department of Women, Child Development and Social Security, Govt. of Jharkhand',
    origin: 'state',
    stateName: 'Jharkhand',
    category: 'Women & Child',
    subCategory: 'Women Empowerment & Cash Assistance',
    beneficiaries: ['Women', 'Rural Citizens'],
    benefitValue: 'Direct Benefit Cash Transfer of ₹1,000 Every Month (₹12,000/Year) directly into Bank Accounts',
    benefitNumericMin: 12000,
    benefitNumericMax: 12000,
    description: 'Delivers ₹1,000 monthly cash assistance to 48 lakh women aged 21 to 50 years across Jharkhand.',
    eligibilityDescription: 'Women aged 21 to 50 domiciled in Jharkhand belonging to low-income/ration card holding families.',
    requiredDocs: ['Jharkhand Residential Certificate', 'Aadhaar Card', 'Ration Card', 'Bank Account Details'],
    deadline: 'MMMSY Portal Jharkhand / Pragya Kendra Camps',
    officialWebsiteUrl: 'https://mmmsy.jharkhand.gov.in',
    rules: { minAge: 21, maxAge: 50, genderConstraint: 'Female', statesAllowed: ['Jharkhand'] },
    isPopular: true,
    iconName: 'savings'
  },
  {
    id: 'as-mukhya-mantri-nijut-moina-yojana',
    title: 'Mukhya Mantri Nijut Moina Scheme (Monthly Education Stipend for Girls Assam)',
    code: 'AS-NIJUT-MOINA-SCHEME-GIRLS',
    ministry: 'Education & Women Welfare Dept, Govt. of Assam',
    origin: 'state',
    stateName: 'Assam',
    category: 'Women & Child',
    subCategory: 'Girl Child Education & Higher Studies',
    beneficiaries: ['Students', 'Women'],
    benefitValue: 'Monthly Cash Stipend of ₹1,000 (Class 11-12), ₹1,250 (Degree Graduation) & ₹2,500 (Post Graduation / B.Ed)',
    benefitNumericMin: 10000,
    benefitNumericMax: 25000,
    description: 'Provides monthly cash stipends to 10 lakh girl students in Assam to prevent underage marriage and encourage completion of post-graduation degrees.',
    eligibilityDescription: 'Girl students pursuing higher education in Assam government colleges who maintain 75%+ class attendance and do not marry during studies.',
    requiredDocs: ['Assam Domicile Certificate', 'College Admission Receipt', 'Self-Declaration of Unmarried Status'],
    deadline: 'Directorate of Higher Education Assam Portal',
    officialWebsiteUrl: 'https://directorateofhighereducation.assam.gov.in',
    rules: { minAge: 15, maxAge: 26, genderConstraint: 'Female', requiresStudent: true, statesAllowed: ['Assam'] },
    isPopular: true,
    iconName: 'school'
  },
  {
    id: 'uk-mukhyamantri-aanchal-amrit-yojana',
    title: 'Mukhyamantri Aanchal Amrit Yojana (Free Milk for Anganwadi Children UK)',
    code: 'UK-AANCHAL-AMRIT-YOJANA',
    ministry: 'Women Empowerment and Child Development Dept, Govt. of Uttarakhand',
    origin: 'state',
    stateName: 'Uttarakhand',
    category: 'Women & Child',
    subCategory: 'Early Childhood Care & Nutrition',
    beneficiaries: ['Children'],
    benefitValue: '100% Free Fortified Flavored Milk (100ml) Served 4 Days a Week to 2.5 Lakh Children across 20,000 Anganwadi Centres',
    benefitNumericMin: 3000,
    benefitNumericMax: 8000,
    description: 'Provides free fortified milk to children aged 3 to 6 years attending Anganwadi centres in Uttarakhand to tackle childhood malnutrition and stunting.',
    eligibilityDescription: 'Children aged 3 to 6 years registered at Anganwadi centres in Uttarakhand.',
    requiredDocs: ['Anganwadi Registration Entry'],
    deadline: 'Local Anganwadi Centre Uttarakhand',
    officialWebsiteUrl: 'https://wecd.uk.gov.in',
    rules: { minAge: 3, maxAge: 6, statesAllowed: ['Uttarakhand'] },
    isPopular: false,
    iconName: 'child_care'
  },
  {
    id: 'hp-mukhyamantri-bal-sukh-yojana',
    title: 'HP Mukhyamantri Sukh Aashraya Yojana (State Support for Orphan Children)',
    code: 'HP-SUKH-AASHRAYA-ORPHAN-CARE',
    ministry: 'Social Justice and Empowerment Dept, Govt. of Himachal Pradesh',
    origin: 'state',
    stateName: 'Himachal Pradesh',
    category: 'Women & Child',
    subCategory: 'Child Protection & Education',
    beneficiaries: ['Children', 'Students'],
    benefitValue: 'Declared "Children of the State": 100% Free IIT/NIT/Medical Higher Education Fee + Monthly Pocket Allowance of ₹4,000 + ₹2.0 Lakh Marriage Grant',
    benefitNumericMin: 48000,
    benefitNumericMax: 500000,
    description: 'Adopts orphan children in Himachal Pradesh as "Children of the State", funding their complete higher education, hostel fees, monthly pocket money, and home construction.',
    eligibilityDescription: 'Orphan children, destitute children, and single-mother children residing in Himachal Pradesh.',
    requiredDocs: ['Bonafide Himachali Certificate', 'Orphan Status Certificate from Tehsildar'],
    deadline: 'District Child Protection Officer HP / SJE Portal',
    officialWebsiteUrl: 'https://himachal.nic.in',
    rules: { minAge: 0, maxAge: 27, statesAllowed: ['Himachal Pradesh'] },
    isPopular: true,
    iconName: 'family_restroom'
  },
  {
    id: 'delhi-ladli-scheme-fixed-deposit-bond',
    title: 'Delhi Ladli Scheme (Financial Fixed Deposit Bond Grant for Girl Child)',
    code: 'DELHI-LADLI-SCHEME-BOND',
    ministry: 'Department of Women and Child Development, Govt. of NCT of Delhi',
    origin: 'state',
    stateName: 'Delhi',
    category: 'Women & Child',
    subCategory: 'Girl Child Education & Wealth',
    beneficiaries: ['Children', 'Students', 'Women'],
    benefitValue: 'Fixed Deposit Bond Totaling ₹35,000 (Institutional Birth) or ₹30,000 Deposited in Milestones (Class 1, 6, 9, 10, 12) Maturing at 18 Years',
    benefitNumericMin: 35000,
    benefitNumericMax: 100000,
    description: 'Deposits state funds with SBI Life Insurance in the name of girl children in Delhi, providing a huge financial lump-sum upon passing Class 10th/12th at age 18.',
    eligibilityDescription: 'Girl children born in Delhi with family annual income up to ₹1,00,000 (residing in Delhi for past 3 years).',
    requiredDocs: ['Delhi Address Proof (3 Years)', 'Girl Child Birth Certificate', 'Income Certificate', 'Aadhaar Card'],
    deadline: 'e-District Delhi Portal (edistrict.delhigovt.nic.in)',
    officialWebsiteUrl: 'https://edistrict.delhigovt.nic.in',
    rules: { minAge: 0, maxAge: 18, maxAnnualIncome: 100000, genderConstraint: 'Female', statesAllowed: ['Delhi'] },
    isPopular: true,
    iconName: 'savings'
  },
  {
    id: 'jk-laadli-beti-scheme-financial-deposit',
    title: 'J&K Laadli Beti Scheme (Monthly Financial Bank Deposit Totaling ₹1,00,000)',
    code: 'JK-LAADLI-BETI-SCHEME',
    ministry: 'Social Welfare Department, Govt. of Jammu and Kashmir',
    origin: 'state',
    stateName: 'Jammu and Kashmir',
    category: 'Women & Child',
    subCategory: 'Girl Child Education & Wealth',
    beneficiaries: ['Children', 'Women'],
    benefitValue: 'Monthly State Deposit of ₹1,000 in Girl’s Account for 14 Years Totaling ₹1,68,000 Maturing to ~₹6.5 Lakh upon Girl Reaching 21 Years',
    benefitNumericMin: 168000,
    benefitNumericMax: 650000,
    description: 'High-value financial security scheme depositing ₹1,000 every month in a girl child’s account from birth until 14 years, yielding over ₹6.5 Lakh at 21 years.',
    eligibilityDescription: 'Girl children born in J&K families with annual family income up to ₹75,000.',
    requiredDocs: ['J&K Domicile Certificate', 'Girl Birth Certificate', 'Income Certificate', 'Aadhaar Card'],
    deadline: 'District Social Welfare Officer J&K',
    officialWebsiteUrl: 'https://jk.gov.in',
    rules: { minAge: 0, maxAge: 21, maxAnnualIncome: 75000, genderConstraint: 'Female', statesAllowed: ['Jammu and Kashmir'] },
    isPopular: true,
    iconName: 'verified'
  },
  {
    id: 'step-women-employment-training-programme',
    title: 'Support to Training and Employment Programme for Women (STEP)',
    code: 'STEP-MWCD-SKILLS',
    ministry: 'Ministry of Women and Child Development (MWCD)',
    origin: 'central',
    category: 'Women & Child',
    subCategory: 'Women Empowerment & Skill Training',
    beneficiaries: ['Women', 'Workers', 'Rural Citizens'],
    benefitValue: '100% Free Vocational Skill Training in Agriculture, Handloom, IT, Tailoring & Food Processing',
    benefitNumericMin: 15000,
    benefitNumericMax: 45000,
    description: 'Provides skills that give employability to women and to provide competencies and skill that enable women to become self-employed entrepreneurs.',
    eligibilityDescription: 'Marginalized and rural women aged 16 years and above across India.',
    requiredDocs: ['Aadhaar Card', 'Income Certificate', 'Category Certificate'],
    deadline: 'MWCD Official Portal',
    officialWebsiteUrl: 'https://wcd.nic.in',
    rules: { minAge: 16, maxAge: 65, genderConstraint: 'Female' },
    isPopular: true,
    iconName: 'work'
  },
  {
    id: 'rashtriya-mahila-kosh-micro-finance-women',
    title: 'Rashtriya Mahila Kosh (RMK Micro-Finance for Women SHGs)',
    code: 'RMK-MICROFINANCE-MWCD',
    ministry: 'Ministry of Women and Child Development (MWCD)',
    origin: 'central',
    category: 'Women & Child',
    subCategory: 'Women Empowerment & Micro-Credit',
    beneficiaries: ['Women', 'Entrepreneurs', 'Rural Citizens'],
    benefitValue: 'Collateral-Free Micro-Loans at Concessional Interest Rates for Women Self-Help Groups (SHGs)',
    benefitNumericMin: 20000,
    benefitNumericMax: 200000,
    description: 'Facilitates micro-credit to poor women for income generation activities and micro-enterprises.',
    eligibilityDescription: 'Women SHGs and micro-enterprises operating in rural and urban poor areas.',
    requiredDocs: ['SHG Bank Passbook', 'Aadhaar Cards of Group Members', 'Resolution Copy'],
    deadline: 'RMK Portal',
    officialWebsiteUrl: 'https://wcd.nic.in',
    rules: { minAge: 18, maxAge: 65, genderConstraint: 'Female' },
    isPopular: false,
    iconName: 'payments'
  },
  {
    id: 'ujjawala-scheme-trafficking-prevention-rehabilitation',
    title: 'Ujjawala Scheme for Prevention of Trafficking & Rescue of Women',
    code: 'UJJAWALA-MWCD-REHAB',
    ministry: 'Ministry of Women and Child Development (MWCD)',
    origin: 'central',
    category: 'Women & Child',
    subCategory: 'Women Protection & Rehabilitation',
    beneficiaries: ['Women', 'Children'],
    benefitValue: '100% Free Safe Shelter, Food, Medical Care, Legal Aid & Vocational Training for Trafficking Survivors',
    benefitNumericMin: 30000,
    benefitNumericMax: 80000,
    description: 'Comprehensive scheme for prevention of trafficking and rescue, rehabilitation and re-integration of victims of trafficking for commercial sexual exploitation.',
    eligibilityDescription: 'Women and children who are vulnerable to or survivors of trafficking.',
    requiredDocs: ['Police / NGO Referral Certificate'],
    deadline: 'District Child Protection Unit / Protective Homes',
    officialWebsiteUrl: 'https://wcd.nic.in',
    rules: { minAge: 0, maxAge: 70, genderConstraint: 'Female' },
    isPopular: false,
    iconName: 'security'
  },
  {
    id: 'nari-shakti-puraskar-national-women-award',
    title: 'Nari Shakti Puraskar (National Award for Outstanding Women)',
    code: 'NARI-SHAKTI-PURASKAR-MWCD',
    ministry: 'Ministry of Women and Child Development (MWCD)',
    origin: 'central',
    category: 'Women & Child',
    subCategory: 'Women Recognition & Honor',
    beneficiaries: ['Women'],
    benefitValue: 'National Honor Award Certificate + ₹2,00,000 Cash Citation Presented by President of India',
    benefitNumericMin: 200000,
    benefitNumericMax: 200000,
    description: 'Highest civilian honor for women in India, recognizing exceptional work towards women empowerment and social service.',
    eligibilityDescription: 'Individual women aged 25+ and institutions with exceptional track record in women empowerment.',
    requiredDocs: ['Nomination Form', 'Citation of Achievements', 'Identity Proof'],
    deadline: 'National Awards Portal (awards.gov.in)',
    officialWebsiteUrl: 'https://awards.gov.in',
    rules: { minAge: 25, maxAge: 100, genderConstraint: 'Female' },
    isPopular: true,
    iconName: 'emoji_events'
  },
  {
    id: 'stree-shakti-package-sbi-women-entrepreneurs',
    title: 'Stree Shakti Package for Women Entrepreneurs (SBI Interest Concession)',
    code: 'STREE-SHAKTI-SBI-LOAN',
    ministry: 'State Bank of India & Ministry of MSME',
    origin: 'central',
    category: 'Women & Child',
    subCategory: 'Women Empowerment & Business Credit',
    beneficiaries: ['Women', 'Entrepreneurs'],
    benefitValue: 'Concessional Interest Rate (0.50% Discount) + No Collateral for Loans up to ₹5 Lakh for Women-Owned Businesses',
    benefitNumericMin: 50000,
    benefitNumericMax: 500000,
    description: 'Supports female entrepreneurs running enterprise where women hold majority shareholding of 51%+ capital.',
    eligibilityDescription: 'Women entrepreneurs running manufacturing, service, or retail businesses with 51%+ ownership.',
    requiredDocs: ['Enterprise Registration Proof', 'Aadhaar / PAN Card', 'Business Plan'],
    deadline: 'Any State Bank of India Branch',
    officialWebsiteUrl: 'https://sbi.co.in',
    rules: { minAge: 18, maxAge: 65, genderConstraint: 'Female' },
    isPopular: true,
    iconName: 'store'
  },
  {
    id: 'mp-mukhyamantri-kanya-vivah-yojana',
    title: 'MP Mukhyamantri Kanya Vivah/Nikah Yojana (Financial Marriage Grant)',
    code: 'MP-KANYA-VIVAH-YOJANA',
    ministry: 'Social Justice and Disabled Welfare Dept, Govt. of MP',
    origin: 'state',
    stateName: 'Madhya Pradesh',
    category: 'Women & Child',
    subCategory: 'Marriage Support & Financial Aid',
    beneficiaries: ['Women', 'Rural Citizens'],
    benefitValue: 'Financial Grant Totaling ₹51,000 for Mass Marriage Expenses & Household Establishment',
    benefitNumericMin: 51000,
    benefitNumericMax: 51000,
    description: 'Provides ₹51,000 financial support for marriage of girls belonging to poor, destitute, widowed, or divorced families in MP.',
    eligibilityDescription: 'Destitute, poor, widowed, or divorced women aged 18+ residing in MP with BPL/low-income status.',
    requiredDocs: ['MP Samagra ID', 'Age Proof of Bride & Groom', 'Income Certificate'],
    deadline: 'Gram Panchayat / Urban Local Body MP',
    officialWebsiteUrl: 'https://socialjustice.mp.gov.in',
    rules: { minAge: 18, maxAge: 45, genderConstraint: 'Female', statesAllowed: ['Madhya Pradesh'] },
    isPopular: true,
    iconName: 'favorite'
  },
  {
    id: 'hr-mukhyamantri-vivah-shagun-yojana',
    title: 'Haryana Mukhyamantri Vivah Shagun Yojana (Financial Shagun Grant)',
    code: 'HR-VIVAH-SHAGUN-YOJANA',
    ministry: 'Department of Welfare of SC and BC, Govt. of Haryana',
    origin: 'state',
    stateName: 'Haryana',
    category: 'Women & Child',
    subCategory: 'Marriage Support & Financial Aid',
    beneficiaries: ['Women', 'Socially Backward Classes'],
    benefitValue: 'Financial Shagun Grant up to ₹71,000 Transferred Directly on Marriage Registration',
    benefitNumericMin: 31000,
    benefitNumericMax: 71000,
    description: 'Offers financial shagun grant to SC/BPL/Widowed families in Haryana during daughter’s marriage.',
    eligibilityDescription: 'Girls aged 18+ domiciled in Haryana belonging to SC/ST/BPL/Destitute families.',
    requiredDocs: ['Haryana Family ID (PPP)', 'Marriage Card & Proof', 'Aadhaar Card'],
    deadline: 'SARAL Haryana Portal',
    officialWebsiteUrl: 'https://saralharyana.gov.in',
    rules: { minAge: 18, maxAge: 40, genderConstraint: 'Female', statesAllowed: ['Haryana'] },
    isPopular: true,
    iconName: 'card_giftcard'
  },
  {
    id: 'up-mukhyamantri-samuhik-vivah-yojana',
    title: 'UP Mukhyamantri Samuhik Vivah Yojana (Mass Marriage Financial Grant)',
    code: 'UP-SAMUHIK-VIVAH-YOJANA',
    ministry: 'Social Welfare Department, Govt. of UP',
    origin: 'state',
    stateName: 'Uttar Pradesh',
    category: 'Women & Child',
    subCategory: 'Marriage Support & Financial Aid',
    beneficiaries: ['Women', 'Rural Citizens'],
    benefitValue: 'Financial Aid Totaling ₹51,000 (₹35,000 Direct Bank Cash + ₹10,000 Household Gifts + ₹6,000 Event Cost)',
    benefitNumericMin: 51000,
    benefitNumericMax: 51000,
    description: 'Provides complete financial grant and household utensils/gifts for poor girls getting married in mass community ceremonies.',
    eligibilityDescription: 'UP resident poor families with annual income up to ₹2,00,000.',
    requiredDocs: ['UP Domicile', 'Income Certificate', 'Age Proof of Bride (18+) and Groom (21+)'],
    deadline: 'UP Social Welfare Portal / Vikas Khand Office',
    officialWebsiteUrl: 'https://socialwelfare.up.gov.in',
    rules: { minAge: 18, maxAge: 40, maxAnnualIncome: 200000, genderConstraint: 'Female', statesAllowed: ['Uttar Pradesh'] },
    isPopular: true,
    iconName: 'celebration'
  },
  {
    id: 'rj-indira-gandhi-matritva-poshan-yojana',
    title: 'Rajasthan Indira Gandhi Matritva Poshan Yojana (IGMPY Maternity Cash)',
    code: 'RJ-IGMPY-MATERNITY-CASH',
    ministry: 'Women and Child Development Department, Govt. of Rajasthan',
    origin: 'state',
    stateName: 'Rajasthan',
    category: 'Women & Child',
    subCategory: 'Maternal Welfare & Nutrition',
    beneficiaries: ['Women', 'Children'],
    benefitValue: 'Financial Cash Transfer of ₹6,000 in 5 Installments on Birth of 2nd Child',
    benefitNumericMin: 6000,
    benefitNumericMax: 6000,
    description: 'Provides ₹6,000 cash incentives to pregnant women in Rajasthan on second child birth to promote maternal nutrition.',
    eligibilityDescription: 'Pregnant women residing in Rajasthan delivering second child.',
    requiredDocs: ['Jan Aadhaar Card', 'PCTS Registration ID', 'Bank Passbook'],
    deadline: 'Integrated Child Development Services (ICDS) Rajasthan',
    officialWebsiteUrl: 'https://wcd.rajasthan.gov.in',
    rules: { minAge: 19, maxAge: 45, genderConstraint: 'Female', statesAllowed: ['Rajasthan'] },
    isPopular: true,
    iconName: 'pregnant_woman'
  },
  {
    id: 'wb-lakshmir-bhandar-scheme-monthly-cash',
    title: 'WB Lakshmir Bhandar Scheme (Monthly Direct Cash Transfer of ₹1,000 - ₹1,200)',
    code: 'WB-LAKSHMIR-BHANDAR-CASH',
    ministry: 'Department of Women & Child Development, Govt. of West Bengal',
    origin: 'state',
    stateName: 'West Bengal',
    category: 'Women & Child',
    subCategory: 'Women Empowerment & Cash Assistance',
    beneficiaries: ['Women', 'Rural Citizens'],
    benefitValue: 'Monthly Direct Bank Cash Allowance of ₹1,200 (SC/ST Women) or ₹1,000 (General Category Women)',
    benefitNumericMin: 12000,
    benefitNumericMax: 14400,
    description: 'West Bengal flagship basic income scheme providing direct monthly cash transfer to over 2 crore female heads of households.',
    eligibilityDescription: 'Women aged 25 to 60 residing in West Bengal holding Swasthya Sathi Card.',
    requiredDocs: ['Swasthya Sathi Card', 'Aadhaar Card', 'Caste Certificate (if SC/ST)', 'Bank Account Details'],
    deadline: 'Duare Sarkar Camps / WB WCD Portal',
    officialWebsiteUrl: 'https://socialsecurity.wb.gov.in',
    rules: { minAge: 25, maxAge: 60, genderConstraint: 'Female', statesAllowed: ['West Bengal'] },
    isPopular: true,
    iconName: 'savings'
  },
  {
    id: 'jk-tejaswini-scheme-women-entrepreneurs',
    title: 'J&K Tejaswini Scheme for Young Women Entrepreneurs (Business Loan & Subsidy)',
    code: 'JK-TEJASWINI-WOMEN-LOAN',
    ministry: 'Mission Youth, Govt. of Jammu and Kashmir',
    origin: 'state',
    stateName: 'Jammu and Kashmir',
    category: 'Women & Child',
    subCategory: 'Women Empowerment & Business Credit',
    beneficiaries: ['Women', 'Entrepreneurs'],
    benefitValue: 'Financial Project Loan up to ₹5 Lakh + ₹50,000 State Subsidy + 100% Interest Subvention',
    benefitNumericMin: 50000,
    benefitNumericMax: 500000,
    description: 'Empowers young female entrepreneurs in J&K to set up manufacturing, retail, or service units with interest-free loans.',
    eligibilityDescription: 'Young women aged 18 to 35 residing in Jammu & Kashmir with 10th pass qualification.',
    requiredDocs: ['J&K Domicile', '10th Marksheet', 'Detailed Project Report (DPR)'],
    deadline: 'J&K Mission Youth Portal',
    officialWebsiteUrl: 'https://missionyouth.jk.gov.in',
    rules: { minAge: 18, maxAge: 35, genderConstraint: 'Female', statesAllowed: ['Jammu and Kashmir'] },
    isPopular: true,
    iconName: 'storefront'
  },
  {
    id: 'ka-stree-samarthya-yojana-shg-grant',
    title: 'Karnataka Stree Samarthya Yojana (Micro-Enterprise Financial Grant for SHGs)',
    code: 'KA-STREE-SAMARTHYA-SHG',
    ministry: 'Department of Skill Development, Entrepreneurship and Livelihood, Govt. of KA',
    origin: 'state',
    stateName: 'Karnataka',
    category: 'Women & Child',
    subCategory: 'Women Empowerment & SHG Support',
    beneficiaries: ['Women', 'Rural Citizens'],
    benefitValue: 'Financial Revolving Fund Grant up to ₹1.5 Lakh per Women Self Help Group for Cottage Industry Startup',
    benefitNumericMin: 50000,
    benefitNumericMax: 150000,
    description: 'Strengthens women Self Help Groups in Karnataka by providing seed capital to establish small manufacturing and processing units.',
    eligibilityDescription: 'Registered Women Stree Shakti and Sanjeevini SHGs in Karnataka.',
    requiredDocs: ['SHG Registration Certificate', 'Group Aadhaar Copy', 'Bank Passbook'],
    deadline: 'Sanjeevini KSRLPS Portal',
    officialWebsiteUrl: 'https://sanjeevini.karnataka.gov.in',
    rules: { minAge: 18, maxAge: 65, genderConstraint: 'Female', statesAllowed: ['Karnataka'] },
    isPopular: false,
    iconName: 'groups'
  },
  {
    id: 'tn-sathya-ammathaiyar-widow-daughter-marriage',
    title: 'TN EVR Maniammaiyar / Sathya Ammathaiyar Poor Widow Daughter Marriage Scheme',
    code: 'TN-WIDOW-DAUGHTER-MARRIAGE',
    ministry: 'Social Welfare and Women Empowerment Dept, Govt. of Tamil Nadu',
    origin: 'state',
    stateName: 'Tamil Nadu',
    category: 'Women & Child',
    subCategory: 'Marriage Support & Financial Aid',
    beneficiaries: ['Women', 'Socially Backward Classes'],
    benefitValue: 'Financial Cash Assistance of ₹50,000 (Degree/Diploma) or ₹25,000 (10th Pass) + 8 Gram Gold Sovereign for Thirumangalyam',
    benefitNumericMin: 25000,
    benefitNumericMax: 50000,
    description: 'Helps poor widows in Tamil Nadu perform the marriage of their daughters by giving ₹50,000 cash plus free 8g gold coin.',
    eligibilityDescription: 'Daughters of poor widows in Tamil Nadu with family annual income under ₹72,000.',
    requiredDocs: ['TN Smart Ration Card', 'Mother Widow Certificate', 'Daughter Educational Marksheet', 'Marriage Proof'],
    deadline: 'District Social Welfare Officer TN',
    officialWebsiteUrl: 'https://tn.gov.in',
    rules: { minAge: 18, maxAge: 40, maxAnnualIncome: 72000, genderConstraint: 'Female', statesAllowed: ['Tamil Nadu'] },
    isPopular: true,
    iconName: 'card_giftcard'
  },
  {
    id: 'mh-lokshahir-annabhau-sathe-women-loan',
    title: 'MH Lokshahir Annabhau Sathe Financial Support for Matang Community Women',
    code: 'MH-ANNABHAU-SATHE-WOMEN-LOAN',
    ministry: 'Social Justice Dept, Govt. of Maharashtra',
    origin: 'state',
    stateName: 'Maharashtra',
    category: 'Women & Child',
    subCategory: 'Women Empowerment & Micro-Credit',
    beneficiaries: ['Women', 'Socially Backward Classes'],
    benefitValue: 'Financial Business Loan up to ₹1 Lakh with 50% Capital Subsidy (Max ₹10,000 Grant) at 4% Interest',
    benefitNumericMin: 10000,
    benefitNumericMax: 100000,
    description: 'Provides low-interest micro-credit loans to women belonging to marginalized communities in Maharashtra.',
    eligibilityDescription: 'Women from Matang and allied communities residing in Maharashtra with annual income under ₹1 Lakh.',
    requiredDocs: ['Caste Certificate', 'Maharashtra Domicile', 'Income Proof'],
    deadline: 'LASDVC Portal Maharashtra',
    officialWebsiteUrl: 'https://sjsa.maharashtra.gov.in',
    rules: { minAge: 18, maxAge: 55, maxAnnualIncome: 100000, genderConstraint: 'Female', statesAllowed: ['Maharashtra'] },
    isPopular: false,
    iconName: 'payments'
  },
  {
    id: 'pb-kasturba-gandhi-balika-vidyalaya-kgbv',
    title: 'Kasturba Gandhi Balika Vidyalaya (KGBV Residential Schools for Girls)',
    code: 'KGBV-RESIDENTIAL-SCHOOL-GIRLS',
    ministry: 'Ministry of Education & State Education Departments',
    origin: 'central',
    category: 'Women & Child',
    subCategory: 'Girl Child Education & Residential Facilities',
    beneficiaries: ['Children', 'Students', 'Socially Backward Classes'],
    benefitValue: '100% Free Quality Boarding, Lodging, Books, Uniforms & Education from Class 6 to 12 in Residential Schools',
    benefitNumericMin: 20000,
    benefitNumericMax: 50000,
    description: 'Upper primary and secondary residential schools for girls belonging predominantly to SC, ST, OBC, Minority, and BPL families in educationally backward blocks.',
    eligibilityDescription: 'Girls aged 10 to 18 belonging to SC/ST/OBC/Minority/BPL families who are dropouts or out of school.',
    requiredDocs: ['Aadhaar Card', 'Caste / BPL Certificate', 'Previous School Transfer Certificate'],
    deadline: 'District Education Officer / KGBV School Principal',
    officialWebsiteUrl: 'https://education.gov.in',
    rules: { minAge: 10, maxAge: 18, genderConstraint: 'Female', requiresStudent: true },
    isPopular: true,
    iconName: 'school'
  }
];

console.log('Women & Child schemes count:', womenChildSchemes.length);

fs.writeFileSync('temp_women_child.json', JSON.stringify(womenChildSchemes, null, 2));

