import fs from 'fs';
import { Scheme } from './src/types';

export const transportInfraSchemes: Scheme[] = [
  {
    id: 'pm-e-bus-sewa-scheme-electric-buses',
    title: 'PM-eBus Sewa Scheme (10,000 Electric Buses for City Bus Operations)',
    code: 'PM-EBUS-SEWA-MOHUA',
    ministry: 'Ministry of Housing and Urban Affairs (MoHUA), Govt. of India',
    origin: 'central',
    category: 'Transport & Infrastructure',
    subCategory: 'Public Infrastructure & Mobility',
    beneficiaries: ['General Citizen', 'Workers'],
    benefitValue: '10,000 Zero-Emission Electric City Buses + Central Subsidy for EV Charging & Depot Infrastructure across 169 Cities',
    benefitNumericMin: 500000,
    benefitNumericMax: 20000000,
    description: 'Augmentations city bus operations with 10,000 electric buses under Public-Private Partnership (PPP) model, modernizing urban public transport and cutting air pollution.',
    eligibilityDescription: 'Urban Local Bodies (ULBs) and Municipal Transport Corporations in cities with 3 Lakh to 40 Lakh population.',
    requiredDocs: ['Municipal Urban Transport Plan Agreement'],
    deadline: 'PM-eBus Sewa Portal (mohua.gov.in)',
    officialWebsiteUrl: 'https://mohua.gov.in',
    rules: { minAge: 0, maxAge: 100 },
    isPopular: true,
    iconName: 'directions_bus'
  },
  {
    id: 'pm-gram-sadak-yojana-pmgsy-phase-3',
    title: 'Pradhan Mantri Gram Sadak Yojana (PMGSY Phase III All-Weather Rural Roads)',
    code: 'PMGSY-PHASE-3-MORD',
    ministry: 'Ministry of Rural Development (MoRD), Govt. of India',
    origin: 'central',
    category: 'Transport & Infrastructure',
    subCategory: 'Roads & Rural Connectivity',
    beneficiaries: ['Rural Citizens', 'Farmers', 'Workers'],
    benefitValue: '100% Fully Central Funded All-Weather Paved Asphalt Roads Connecting Habitations to Gramin Agricultural Markets (Haats), Hospitals & Higher Secondary Schools',
    benefitNumericMin: 1000000,
    benefitNumericMax: 50000000,
    description: 'Constructs 1,25,000 km of high-quality all-weather rural paved roads connecting remote habitations directly to district markets, hospitals, and schools.',
    eligibilityDescription: 'Unconnected rural habitations with population of 500+ (plains) or 250+ (hills, desert, tribal, and border areas).',
    requiredDocs: ['Gram Sabha Resolution / District Rural Road Plan Proposal'],
    deadline: 'PMGSY OMMAS Portal (omms.nic.in)',
    officialWebsiteUrl: 'https://omms.nic.in',
    rules: { minAge: 0, maxAge: 100 },
    isPopular: true,
    iconName: 'add_road'
  },
  {
    id: 'pm-gati-shakti-national-master-plan',
    title: 'PM GatiShakti National Master Plan for Multi-Modal Connectivity',
    code: 'PM-GATI-SHAKTI-DPIIT',
    ministry: 'DPIIT, Ministry of Commerce and Industry, Govt. of India',
    origin: 'central',
    category: 'Transport & Infrastructure',
    subCategory: 'Public Infrastructure & Connectivity',
    beneficiaries: ['Entrepreneurs', 'Workers', 'General Citizen'],
    benefitValue: 'Integrated GIS Digital Planning Platform Synchronizing 16 Central Ministries (Railways, Highways, Ports, Aviation) for Rapid Infrastructure Execution',
    benefitNumericMin: 10000000,
    benefitNumericMax: 1000000000,
    description: 'A transformative multi-modal connectivity infrastructure plan breaking departmental silos to streamline freight corridors, logistics parks, and industrial zones.',
    eligibilityDescription: 'State Governments, Port Authorities, Railway Zones, and Logistics Park Developers across India.',
    requiredDocs: ['PM GatiShakti NMP Project Proposal Entry'],
    deadline: 'PM GatiShakti Portal (gatishakti.gov.in)',
    officialWebsiteUrl: 'https://gatishakti.gov.in',
    rules: { minAge: 0, maxAge: 100 },
    isPopular: true,
    iconName: 'alt_route'
  },
  {
    id: 'fame-india-phase-2-electric-vehicle-subsidy',
    title: 'FAME India / PM E-DRIVE Scheme (Faster Adoption & Manufacturing of Electric Vehicles)',
    code: 'PM-E-DRIVE-HEAVY-INDUSTRIES',
    ministry: 'Ministry of Heavy Industries, Govt. of India',
    origin: 'central',
    category: 'Transport & Infrastructure',
    subCategory: 'Transport & Clean Mobility',
    beneficiaries: ['General Citizen', 'Workers', 'Entrepreneurs'],
    benefitValue: 'Up to ₹10,000 (2-Wheelers), ₹50,000 (3-Wheelers) & ₹5.0 Lakh (E-Buses/Trucks) Direct Upfront Electric Vehicle Purchase Price Discount',
    benefitNumericMin: 10000,
    benefitNumericMax: 500000,
    description: 'Accelerates electric mobility in India by offering direct upfront purchase subsidies on electric 2-wheelers, 3-wheelers, e-rickshaws, and public EV buses.',
    eligibilityDescription: 'Indian citizens, commercial transport operators, and municipal transit bodies purchasing approved OEM electric vehicles.',
    requiredDocs: ['Aadhaar Card', 'EV Purchase Invoice / Vehicle Registration', 'Bank Details'],
    deadline: 'PM E-DRIVE Portal (heavyindustries.gov.in)',
    officialWebsiteUrl: 'https://heavyindustries.gov.in',
    rules: { minAge: 18, maxAge: 85 },
    isPopular: true,
    iconName: 'electric_car'
  },
  {
    id: 'udan-scheme-regional-airport-connectivity',
    title: 'Ude Desh ka Aam Nagrik (UDAN Regional Air Connectivity Scheme)',
    code: 'UDAN-5-0-CIVIL-AVIATION',
    ministry: 'Ministry of Civil Aviation, Govt. of India',
    origin: 'central',
    category: 'Transport & Infrastructure',
    subCategory: 'Connectivity & Air Transport',
    beneficiaries: ['General Citizen', 'Travelers'],
    benefitValue: 'Capped Capped Low Airfare Seats (₹2,500 for 1-Hour Flight) + VGF Subsidies for Airline Operators in Tier-2/3 Cities',
    benefitNumericMin: 2500,
    benefitNumericMax: 10000,
    description: 'Makes air travel affordable for common citizens by revitalizing unserved/underserved regional airports and heliports across remote Indian districts.',
    eligibilityDescription: 'Passengers traveling on designated UDAN regional flight routes connecting Tier-2 and Tier-3 cities.',
    requiredDocs: ['Standard Valid Flight Booking Ticket'],
    deadline: 'Civil Aviation UDAN Portal (civilaviation.gov.in)',
    officialWebsiteUrl: 'https://civilaviation.gov.in',
    rules: { minAge: 0, maxAge: 100 },
    isPopular: true,
    iconName: 'flight_takeoff'
  },
  {
    id: 'bharatmala-pariyojana-national-highways',
    title: 'Bharatmala Pariyojana (National Highway Corridors & Expressway Development)',
    code: 'BHARATMALA-PARIYOJANA-MORTH',
    ministry: 'Ministry of Road Transport and Highways (MoRTH), Govt. of India',
    origin: 'central',
    category: 'Transport & Infrastructure',
    subCategory: 'Roads & Highways',
    beneficiaries: ['General Citizen', 'Workers', 'Entrepreneurs'],
    benefitValue: '34,800 km of World-Class Access-Controlled Expressways, Economic Corridors & Border Connectivity Roads',
    benefitNumericMin: 10000000,
    benefitNumericMax: 1000000000,
    description: 'Flagship highway sector program optimizing efficiency of freight and passenger movement across economic corridors, expressways, and border areas.',
    eligibilityDescription: 'National Highways Authority of India (NHAI), National Highways and Infrastructure Development Corporation (NHIDCL), and general public.',
    requiredDocs: ['NHAI E-Tendering Portal Registration'],
    deadline: 'NHAI Official Portal (nhai.gov.in)',
    officialWebsiteUrl: 'https://nhai.gov.in',
    rules: { minAge: 0, maxAge: 100 },
    isPopular: true,
    iconName: 'directions_car'
  },
  {
    id: 'sagarmala-programme-port-led-development',
    title: 'Sagarmala Programme (Port-Led Infrastructure & Coastal Logistics Development)',
    code: 'SAGARMALA-PORTS-SHIPPING',
    ministry: 'Ministry of Ports, Shipping and Waterways, Govt. of India',
    origin: 'central',
    category: 'Transport & Infrastructure',
    subCategory: 'Public Infrastructure & Waterways',
    beneficiaries: ['Entrepreneurs', 'Workers', 'General Citizen'],
    benefitValue: 'Port Modernization, Inland Waterways Development, Coastal Shipping Subsidies & Coastal Community Skill Centers',
    benefitNumericMin: 10000000,
    benefitNumericMax: 1000000000,
    description: 'Reduces logistics cost for EXIM and domestic trade through port modernization, coastal shipping, and inland waterway infrastructure development.',
    eligibilityDescription: 'Major and Non-Major Port Authorities, Coastal State Maritime Boards, and logistics park developers.',
    requiredDocs: ['Sagarmala Project DPR Approval'],
    deadline: 'Sagarmala Portal (sagarmala.gov.in)',
    officialWebsiteUrl: 'https://sagarmala.gov.in',
    rules: { minAge: 0, maxAge: 100 },
    isPopular: false,
    iconName: 'directions_boat'
  },
  {
    id: 'parvatmala-pariyojana-ropeway-infrastructure',
    title: 'National Ropeways Development Programme (Parvatmala Pariyojana)',
    code: 'PARVATMALA-ROPEWAY-MORTH',
    ministry: 'Ministry of Road Transport and Highways (MoRTH) / NHLML',
    origin: 'central',
    category: 'Transport & Infrastructure',
    subCategory: 'Public Infrastructure & Hill Mobility',
    beneficiaries: ['General Citizen', 'Travelers', 'Rural Citizens'],
    benefitValue: '100% Fully Funded Construction of Modern Cable Car Ropeways in Difficult Hilly & Congested Urban Pilgrimage Sites',
    benefitNumericMin: 5000000,
    benefitNumericMax: 100000000,
    description: 'Constructs eco-friendly ropeway cable car systems in hilly regions (Kedarnath, Shimla, Varanasi, Mussoorie) to solve last-mile tourist and rural transport bottlenecks.',
    eligibilityDescription: 'State Governments in Hilly States (Uttarakhand, Himachal Pradesh, J&K, Northeast) and Urban Local Bodies.',
    requiredDocs: ['NHLML Ropeway DPR Sanction'],
    deadline: 'MoRTH NHLML Portal (morth.nic.in)',
    officialWebsiteUrl: 'https://morth.nic.in',
    rules: { minAge: 0, maxAge: 100 },
    isPopular: true,
    iconName: 'tram'
  },
  {
    id: 'amrit-bharat-station-scheme-railways',
    title: 'Amrit Bharat Station Scheme (Modernization of 1,300+ Railway Stations)',
    code: 'AMRIT-BHARAT-STATIONS-RAILWAYS',
    ministry: 'Ministry of Railways, Govt. of India',
    origin: 'central',
    category: 'Transport & Infrastructure',
    subCategory: 'Public Infrastructure & Railway Mobility',
    beneficiaries: ['General Citizen', 'Travelers', 'Workers'],
    benefitValue: '100% Modernized Railway Stations with Roof Plazas, Escalators, Free Wi-Fi, Divyangjan Access & Multi-Modal Hubs',
    benefitNumericMin: 10000000,
    benefitNumericMax: 500000000,
    description: 'Transformative scheme upgrading 1,300+ Indian railway stations with modern city centers, roof plazas, executive lounges, and barrier-free access.',
    eligibilityDescription: 'Rail passengers and railway station infrastructure facilities across all railway zones in India.',
    requiredDocs: ['Indian Railways Passenger Ticketing / Service Access'],
    deadline: 'Indian Railways Official Portal (indianrailways.gov.in)',
    officialWebsiteUrl: 'https://indianrailways.gov.in',
    rules: { minAge: 0, maxAge: 100 },
    isPopular: true,
    iconName: 'train'
  },
  {
    id: 'national-clean-air-programme-ncap-ev-charging',
    title: 'NCAP Urban Clean Transit & Public Transport Electrification Grants',
    code: 'NCAP-MOEFCC-TRANSIT-CLEAN',
    ministry: 'Ministry of Environment, Forest and Climate Change (MoEFCC)',
    origin: 'central',
    category: 'Transport & Infrastructure',
    subCategory: 'Transport & Clean Mobility',
    beneficiaries: ['General Citizen', 'Workers'],
    benefitValue: 'Central Clean Air Grants up to ₹50 Crore per Non-Attainment City for Paving Roads, Mechanical Sweepers & EV Bus Infrastructure',
    benefitNumericMin: 10000000,
    benefitNumericMax: 500000000,
    description: 'Provides financial grants to 131 non-attainment cities to reduce PM10/PM2.5 particulate levels by expanding green transport, road paving, and EV charging grids.',
    eligibilityDescription: 'Municipal Corporations and Pollution Control Boards in 131 identified NCAP cities.',
    requiredDocs: ['City Air Quality Action Plan Approval'],
    deadline: 'PRANA NCAP Portal (prana.cpcb.gov.in)',
    officialWebsiteUrl: 'https://prana.cpcb.gov.in',
    rules: { minAge: 0, maxAge: 100 },
    isPopular: false,
    iconName: 'air'
  },
  {
    id: 'up-electric-vehicle-manufacturing-and-mobility-policy',
    title: 'UP Electric Vehicle Subsidy & Road Tax Waiver Scheme 2024',
    code: 'UP-EV-SUBSIDY-POLICY-2024',
    ministry: 'Department of Transport, Govt. of Uttar Pradesh',
    origin: 'state',
    stateName: 'Uttar Pradesh',
    category: 'Transport & Infrastructure',
    subCategory: 'Transport & Clean Mobility',
    beneficiaries: ['General Citizen', 'Workers', 'Entrepreneurs'],
    benefitValue: '100% Exemption of Road Tax & Registration Fees + Direct Cash Subsidy up to ₹5,000 (E-2W), ₹12,000 (E-3W) & ₹1,00,000 (E-4W)',
    benefitNumericMin: 5000,
    benefitNumericMax: 100000,
    description: 'Waives 100% road tax and registration fees for all electric vehicles registered in Uttar Pradesh and provides upfront cash subsidy directly into buyer bank account.',
    eligibilityDescription: 'Individuals and commercial transport operators purchasing new electric vehicles registered with UP RTOs.',
    requiredDocs: ['UP EV Subsidy Portal Registration', 'Vehicle Registration Certificate (RC)', 'Aadhaar Card', 'Bank Passbook Details'],
    deadline: 'UP EV Subsidy Portal (upevsubsidy.in)',
    officialWebsiteUrl: 'https://upevsubsidy.in',
    rules: { minAge: 18, maxAge: 85, statesAllowed: ['Uttar Pradesh'] },
    isPopular: true,
    iconName: 'electric_car'
  },
  {
    id: 'up-expressway-industrial-development-upeida',
    title: 'UP UPEIDA Industrial Expressway Logistics Corridor Scheme',
    code: 'UP-UPEIDA-EXPRESSWAY-CORRIDORS',
    ministry: 'UPEIDA / Department of Infrastructure, Govt. of Uttar Pradesh',
    origin: 'state',
    stateName: 'Uttar Pradesh',
    category: 'Transport & Infrastructure',
    subCategory: 'Roads & Logistics Infrastructure',
    beneficiaries: ['Entrepreneurs', 'Workers', 'General Citizen'],
    benefitValue: 'Industrial Land Allotment, Plug-and-Play Warehousing Facilities & Subsidized Power along Purvanchal, Bundelkhand & Ganga Expressways',
    benefitNumericMin: 1000000,
    benefitNumericMax: 100000000,
    description: 'Develops world-class expressway networks (Ganga Expressway, Purvanchal Expressway, Bundelkhand Expressway) backed by industrial manufacturing parks along nodes.',
    eligibilityDescription: 'Logistics park developers, manufacturing companies, and commercial transport operators in UP.',
    requiredDocs: ['UPEIDA Nivesh Mitra Allotment Application'],
    deadline: 'UPEIDA Portal (upeida.up.gov.in)',
    officialWebsiteUrl: 'https://upeida.up.gov.in',
    rules: { minAge: 18, maxAge: 75, statesAllowed: ['Uttar Pradesh'] },
    isPopular: true,
    iconName: 'add_road'
  },
  {
    id: 'mh-mukhyamantri-gram-sadak-yojana-mmgsy',
    title: 'Maharashtra Mukhyamantri Gram Sadak Yojana (MMGSY Rural Road Upgradation)',
    code: 'MH-MMGSY-RURAL-ROADS',
    ministry: 'Rural Development Department, Govt. of Maharashtra',
    origin: 'state',
    stateName: 'Maharashtra',
    category: 'Transport & Infrastructure',
    subCategory: 'Roads & Rural Infrastructure',
    beneficiaries: ['Rural Citizens', 'Farmers'],
    benefitValue: '100% State Funded Upgradation of 30,000 km Rural Roads & Bridges Connecting Tribal & Sugarcane Belt Villages',
    benefitNumericMin: 500000,
    benefitNumericMax: 20000000,
    description: 'Upgrades unpaved village tracks into durable asphalt roads across rural Maharashtra to boost agricultural transportation and milk/sugarcane logistics.',
    eligibilityDescription: 'Gram Panchayats and rural habitations across Maharashtra.',
    requiredDocs: ['Gram Sabha Demand Resolution'],
    deadline: 'MMGSY Portal Maharashtra (mmgsy.maharashtra.gov.in)',
    officialWebsiteUrl: 'https://mmgsy.maharashtra.gov.in',
    rules: { minAge: 0, maxAge: 100, statesAllowed: ['Maharashtra'] },
    isPopular: true,
    iconName: 'add_road'
  },
  {
    id: 'tn-innuyir-kaappoon-nammai-kaakkum-48-road-safety',
    title: 'TN Innuyir Kaappoon - Nammai Kaakkum 48 (Free Emergency Accident Treatment)',
    code: 'TN-NAMMAI-KAAKKUM-48',
    ministry: 'Health and Family Welfare / Transport Dept, Govt. of Tamil Nadu',
    origin: 'state',
    stateName: 'Tamil Nadu',
    category: 'Transport & Infrastructure',
    subCategory: 'Roads & Emergency Safety',
    beneficiaries: ['General Citizen', 'Travelers', 'Workers'],
    benefitValue: '100% Free Emergency Medical & Surgical Treatment up to ₹1,00,000 per Person for First 48 Hours after Road Accidents',
    benefitNumericMin: 100000,
    benefitNumericMax: 100000,
    description: 'Provides cashless emergency medical treatment during crucial first 48 hours to any victim of road traffic accidents in Tamil Nadu regardless of state/nationality.',
    eligibilityDescription: 'Any person involved in a road traffic accident within the geographical boundaries of Tamil Nadu.',
    requiredDocs: ['No documents required at emergency time (Automated Hospital Registration)'],
    deadline: 'Toll Free Emergency 108 / Empaneled Government & Private Hospitals',
    officialWebsiteUrl: 'https://tn.gov.in',
    rules: { minAge: 0, maxAge: 100, statesAllowed: ['Tamil Nadu'] },
    isPopular: true,
    iconName: 'emergency'
  },
  {
    id: 'ka-kalyana-patha-and-k-ride-suburban-rail',
    title: 'Karnataka Kalyana Patha Rural Road Scheme & K-RIDE Suburban Rail Project',
    code: 'KA-KALYANA-PATHA-ROADS',
    ministry: 'Public Works Department (PWD) / Infrastructure Development Dept, Govt. of Karnataka',
    origin: 'state',
    stateName: 'Karnataka',
    category: 'Transport & Infrastructure',
    subCategory: 'Public Infrastructure & Connectivity',
    beneficiaries: ['General Citizen', 'Rural Citizens', 'Workers'],
    benefitValue: '1,000 km Asphalt Road Upgrade in Kalyana Karnataka Region + 148 km Bengaluru Suburban Rail Corridor Network',
    benefitNumericMin: 1000000,
    benefitNumericMax: 50000000,
    description: 'Upgrades high-traffic rural arterial roads in Kalyana Karnataka districts and builds Bengaluru suburban rail system for seamless commuting.',
    eligibilityDescription: 'Residents and commuters across Karnataka.',
    requiredDocs: ['PWD Engineering Allotment Copy'],
    deadline: 'PWD Karnataka Portal (karnataka.gov.in/pwd)',
    officialWebsiteUrl: 'https://karnataka.gov.in',
    rules: { minAge: 0, maxAge: 100, statesAllowed: ['Karnataka'] },
    isPopular: true,
    iconName: 'subway'
  },
  {
    id: 'ts-hyderabad-metro-phase-2-and-orr-bus-rapid',
    title: 'Telangana Hyderabad Metro Phase II & Airport Express Metro Corridor',
    code: 'TS-HYDERABAD-METRO-PHASE-2',
    ministry: 'HMRL / Transport, Roads & Buildings Dept, Govt. of Telangana',
    origin: 'state',
    stateName: 'Telangana',
    category: 'Transport & Infrastructure',
    subCategory: 'Public Infrastructure & Urban Mobility',
    beneficiaries: ['General Citizen', 'Workers', 'Travelers'],
    benefitValue: '70 km Modern Metro Rail Expansion Connecting Old City, Airport & IT Hubs + Electric Bus Rapid Transit Feeder Network',
    benefitNumericMin: 5000000,
    benefitNumericMax: 100000000,
    description: 'Expands rapid transit metro system in Greater Hyderabad, connecting IT corridors, Rajiv Gandhi International Airport, and densely populated Old City.',
    eligibilityDescription: 'Urban commuters and transit passengers in Greater Hyderabad Metropolitan Area.',
    requiredDocs: ['Hyderabad Metro Smart Card / QR Ticket'],
    deadline: 'Hyderabad Metro Rail Official Portal (hmrl.co.in)',
    officialWebsiteUrl: 'https://hmrl.co.in',
    rules: { minAge: 0, maxAge: 100, statesAllowed: ['Telangana'] },
    isPopular: true,
    iconName: 'train'
  },
  {
    id: 'ap-ports-development-and-greenfield-airports',
    title: 'AP Greenfield Sea Ports (Ramayapatnam, Bhavanapadu, Machilipatnam) & Airport Hubs',
    code: 'AP-PORTS-INFRA-DEVELOPMENT',
    ministry: 'AP Maritime Board / Infrastructure Dept, Govt. of Andhra Pradesh',
    origin: 'state',
    stateName: 'Andhra Pradesh',
    category: 'Transport & Infrastructure',
    subCategory: 'Public Infrastructure & Maritime Ports',
    beneficiaries: ['Entrepreneurs', 'Workers', 'General Citizen'],
    benefitValue: 'Multi-Crore Construction of 4 Deep-Water Greenfield Ports & Bhogapuram International Airport Logistics Corridor',
    benefitNumericMin: 10000000,
    benefitNumericMax: 1000000000,
    description: 'Constructs 4 major deep-water sea ports along AP’s 974 km coastline to establish AP as India’s eastern gateway for cargo and manufacturing EXIM trade.',
    eligibilityDescription: 'Exporters, shipping lines, commercial transport operators, and port logistics firms in AP.',
    requiredDocs: ['AP Maritime Board Concession Agreement'],
    deadline: 'AP Maritime Board Portal (maritime.ap.gov.in)',
    officialWebsiteUrl: 'https://maritime.ap.gov.in',
    rules: { minAge: 0, maxAge: 100, statesAllowed: ['Andhra Pradesh'] },
    isPopular: false,
    iconName: 'directions_boat'
  },
  {
    id: 'wb-pathashree-rastashree-scheme-road-renovation',
    title: 'Pathashree-Rastashree Scheme (12,000 km Rural Road Construction & Renovation WB)',
    code: 'WB-PATHASHREE-RASTASHREE',
    ministry: 'Panchayat and Rural Development Department, Govt. of West Bengal',
    origin: 'state',
    stateName: 'West Bengal',
    category: 'Transport & Infrastructure',
    subCategory: 'Roads & Rural Connectivity',
    beneficiaries: ['Rural Citizens', 'Farmers'],
    benefitValue: '100% State Funded Repair & Construction of 12,000 km Rural Village Roads across 29,000 Gram Panchayats',
    benefitNumericMin: 500000,
    benefitNumericMax: 10000000,
    description: 'Massive rural road campaign constructing and repairing thousands of kilometers of paved roads across every district in West Bengal.',
    eligibilityDescription: 'Gram Panchayats and rural residents in West Bengal.',
    requiredDocs: ['Gram Sabha Resolution / BDO Inspection Report'],
    deadline: 'P&RD Department West Bengal (wbprd.gov.in)',
    officialWebsiteUrl: 'https://wbprd.gov.in',
    rules: { minAge: 0, maxAge: 100, statesAllowed: ['West Bengal'] },
    isPopular: true,
    iconName: 'add_road'
  },
  {
    id: 'gj-vhali-expressway-and-metro-rail-extension',
    title: 'Gujarat High-Speed Rail Corridor & Metro Rail Phase 2 Mobility Scheme',
    code: 'GJ-METRO-RAIL-CORRIDORS',
    ministry: 'GMRC / Urban Development Department, Govt. of Gujarat',
    origin: 'state',
    stateName: 'Gujarat',
    category: 'Transport & Infrastructure',
    subCategory: 'Public Infrastructure & Urban Mobility',
    beneficiaries: ['General Citizen', 'Workers'],
    benefitValue: 'Rapid Metro Rail Connectivity between Ahmedabad, GIFT City & Gandhinagar + EV Feeder Bus Integration',
    benefitNumericMin: 1000000,
    benefitNumericMax: 50000000,
    description: 'Connects Ahmedabad, GIFT City, and Gandhinagar with high-speed metro transit and integrates feeder EV buses for clean urban commuting.',
    eligibilityDescription: 'Urban commuters traveling between Ahmedabad, GIFT City, and Gandhinagar.',
    requiredDocs: ['GMRC Metro Pass / Ticket'],
    deadline: 'Gujarat Metro Rail Corporation (gujaratmetrorail.com)',
    officialWebsiteUrl: 'https://gujaratmetrorail.com',
    rules: { minAge: 0, maxAge: 100, statesAllowed: ['Gujarat'] },
    isPopular: true,
    iconName: 'subway'
  },
  {
    id: 'rj-mukhyamantri-sadak-yojana-and-road-safety',
    title: 'Rajasthan Mukhyamantri Sadak Yojana & Road Safety Mission',
    code: 'RJ-MUKHYAMANTRI-SADAK-YOJANA',
    ministry: 'Public Works Department (PWD), Govt. of Rajasthan',
    origin: 'state',
    stateName: 'Rajasthan',
    category: 'Transport & Infrastructure',
    subCategory: 'Roads & Rural Connectivity',
    beneficiaries: ['Rural Citizens', 'Farmers', 'Travelers'],
    benefitValue: '100% Paved All-Weather Bitumen Road Connectivity to Unconnected Desert & Tribal Dhanis (Hamlets)',
    benefitNumericMin: 500000,
    benefitNumericMax: 15000000,
    description: 'Paves rural bitumen roads to remote desert hamlets (dhanis) across Barmer, Jaisalmer, Bikaner, and tribal belts in Rajasthan.',
    eligibilityDescription: 'Rural hamlets and dhanis with population of 100+ in desert and tribal areas of Rajasthan.',
    requiredDocs: ['Gram Panchayat Application / PWD Sanction Copy'],
    deadline: 'PWD Rajasthan Portal (pwd.rajasthan.gov.in)',
    officialWebsiteUrl: 'https://pwd.rajasthan.gov.in',
    rules: { minAge: 0, maxAge: 100, statesAllowed: ['Rajasthan'] },
    isPopular: true,
    iconName: 'add_road'
  },
  {
    id: 'kl-k-fon-free-internet-and-k-swift-bus-fleet',
    title: 'Kerala K-FON Free High-Speed Optical Fiber Internet & KSWIFT Electric Bus Fleet',
    code: 'KL-KFON-FREE-INTERNET-MOBILITY',
    ministry: 'IT Department & Transport Dept, Govt. of Kerala',
    origin: 'state',
    stateName: 'Kerala',
    category: 'Transport & Infrastructure',
    subCategory: 'Public Infrastructure & Connectivity',
    beneficiaries: ['General Citizen', 'Rural Citizens', 'Students'],
    benefitValue: '100% Free High-Speed Broadband Internet to 20 Lakh BPL Families + 1,000 Modern KSRTC-SWIFT EV Buses',
    benefitNumericMin: 5000,
    benefitNumericMax: 30000,
    description: 'Kerala’s landmark digital infrastructure project declaring internet access a basic right, laying 30,000 km optical fiber and providing free connectivity to BPL homes.',
    eligibilityDescription: 'Kerala resident BPL families and government schools/offices.',
    requiredDocs: ['Kerala BPL Ration Card', 'Aadhaar Card'],
    deadline: 'K-FON Portal (kfon.kerala.gov.in)',
    officialWebsiteUrl: 'https://kfon.kerala.gov.in',
    rules: { minAge: 0, maxAge: 100, statesAllowed: ['Kerala'] },
    isPopular: true,
    iconName: 'wifi'
  },
  {
    id: 'od-laccmi-bus-scheme-rural-transportation',
    title: 'LACCMI Scheme (Location Accessible Multi-Modal Initiative Rural Bus Network Odisha)',
    code: 'OD-LACCMI-RURAL-BUS-SCHEME',
    ministry: 'Commerce and Transport Department / OSRTC, Govt. of Odisha',
    origin: 'state',
    stateName: 'Odisha',
    category: 'Transport & Infrastructure',
    subCategory: 'Transport & Rural Mobility',
    beneficiaries: ['Rural Citizens', 'Women', 'Students'],
    benefitValue: 'Subsidized Bus Fares (₹5 Flat Ticket for Women & Students) Connecting 6,000+ Gram Panchayats to Block/District HQ',
    benefitNumericMin: 2000,
    benefitNumericMax: 10000,
    description: 'Plys 1,000+ modern AC/Non-AC buses directly connecting every Gram Panchayat in Odisha to block headquarters and district hospitals.',
    eligibilityDescription: 'Rural commuters, women, school/college students, and senior citizens in Odisha.',
    requiredDocs: ['LACCMI Bus Pass / Student ID / Aadhaar Card'],
    deadline: 'OSRTC / Commerce and Transport Dept Odisha',
    officialWebsiteUrl: 'https://transport.odisha.gov.in',
    rules: { minAge: 0, maxAge: 100, statesAllowed: ['Odisha'] },
    isPopular: true,
    iconName: 'directions_bus'
  },
  {
    id: 'pb-e-rickshaw-and-rural-link-road-scheme',
    title: 'Punjab Rural Link Roads Overhaul & Mukhyamantri E-Vehicle Subsidy',
    code: 'PB-RURAL-LINK-ROADS-EV',
    ministry: 'Punjab Mandi Board & Transport Department, Govt. of Punjab',
    origin: 'state',
    stateName: 'Punjab',
    category: 'Transport & Infrastructure',
    subCategory: 'Roads & Clean Mobility',
    beneficiaries: ['Farmers', 'Rural Citizens', 'Workers'],
    benefitValue: '100% Paved Repair of 60,000 km Agricultural Link Roads + Upfront Cash Subsidy on Commercial Electric 3-Wheelers',
    benefitNumericMin: 10000,
    benefitNumericMax: 50000,
    description: 'Maintains and repairs 60,000 km of agricultural mandi link roads and provides subsidies on commercial electric auto-rickshaws.',
    eligibilityDescription: 'Farmers, rural residents, and auto drivers in Punjab.',
    requiredDocs: ['Punjab Mandi Board Registration / Driving License', 'Aadhaar Card'],
    deadline: 'Punjab Mandi Board / Transport Dept',
    officialWebsiteUrl: 'https://punjab.gov.in',
    rules: { minAge: 18, maxAge: 75, statesAllowed: ['Punjab'] },
    isPopular: true,
    iconName: 'electric_rickshaw'
  },
  {
    id: 'hr-city-bus-sewa-and-railway-overbridge-scheme',
    title: 'Haryana E-Bus City Transit & Railway Overbridge (ROB) PWD Scheme',
    code: 'HR-CITY-BUS-SEWA-ROB',
    ministry: 'Transport Department & PWD (B&R), Govt. of Haryana',
    origin: 'state',
    stateName: 'Haryana',
    category: 'Transport & Infrastructure',
    subCategory: 'Public Infrastructure & City Transit',
    beneficiaries: ['General Citizen', 'Workers'],
    benefitValue: '100% Electric Zero-Emission City Buses Operating in Panipat, Yamunanagar, Rohtak, Hisar + Elimination of Railway Level Crossings',
    benefitNumericMin: 500000,
    benefitNumericMax: 20000000,
    description: 'Deploys 450+ zero-emission electric city buses across 9 major cities in Haryana and builds flyovers/overbridges over all busy railway level crossings.',
    eligibilityDescription: 'Urban commuters and highway transport travelers in Haryana.',
    requiredDocs: ['Haryana City Bus Digital Pass / Ticket'],
    deadline: 'Haryana Transport Dept (hartrans.gov.in)',
    officialWebsiteUrl: 'https://hartrans.gov.in',
    rules: { minAge: 0, maxAge: 100, statesAllowed: ['Haryana'] },
    isPopular: true,
    iconName: 'directions_bus'
  },
  {
    id: 'mp-mukhyamantri-rural-transport-and-flyover-mission',
    title: 'MP Mukhyamantri Gramin Transport Scheme & Urban Flyover Mission',
    code: 'MP-GRAMIN-TRANSPORT-FLYOVER',
    ministry: 'Transport Department & Urban Development Dept, Govt. of MP',
    origin: 'state',
    stateName: 'Madhya Pradesh',
    category: 'Transport & Infrastructure',
    subCategory: 'Transport & Rural Mobility',
    beneficiaries: ['Rural Citizens', 'Workers', 'General Citizen'],
    benefitValue: 'Subsidized Passenger 7-Seater/15-Seater Vehicles Plying on Tribal Routes + Permit Tax Exemption for Operators',
    benefitNumericMin: 20000,
    benefitNumericMax: 100000,
    description: 'Provides passenger mobility in remote tribal areas of MP by giving vehicle permit tax waivers to private operators running rural minibus routes.',
    eligibilityDescription: 'Rural transport operators and commuters in tribal districts of MP.',
    requiredDocs: ['MP Transport Permit Application', 'Driving License', 'Aadhaar Card'],
    deadline: 'MP Transport Department (transport.mp.gov.in)',
    officialWebsiteUrl: 'https://transport.mp.gov.in',
    rules: { minAge: 18, maxAge: 70, statesAllowed: ['Madhya Pradesh'] },
    isPopular: false,
    iconName: 'commute'
  },
  {
    id: 'br-mukhyamantri-gram-parivahan-yojana-mmgpy',
    title: 'Bihar Mukhyamantri Gram Parivahan Yojana (Subsidized Vehicle Grant)',
    code: 'BR-MMGPY-PARIVAHAN-GRANT',
    ministry: 'Transport Department, Govt. of Bihar',
    origin: 'state',
    stateName: 'Bihar',
    category: 'Transport & Infrastructure',
    subCategory: 'Transport & Rural Mobility',
    beneficiaries: ['Workers', 'Rural Citizens', 'Job Seekers'],
    benefitValue: '50% Direct Capital Subsidy up to ₹1,00,000 for Buying 4-Seater to 10-Seater Passenger Commercial Vehicles / E-Rickshaws',
    benefitNumericMin: 50000,
    benefitNumericMax: 100000,
    description: 'Provides 50% capital subsidy (up to ₹1 Lakh) to SC, ST, and EBC unemployed youth in Bihar to purchase passenger vehicles for village-to-block transit.',
    eligibilityDescription: 'Unemployed youth belonging to SC, ST, or EBC categories residing in Bihar gram panchayats.',
    requiredDocs: ['Bihar Residential Certificate', 'Caste Certificate', 'Driving License', 'Aadhaar Card'],
    deadline: 'Bihar Transport Portal (transport.bihar.gov.in)',
    officialWebsiteUrl: 'https://transport.bihar.gov.in',
    rules: { minAge: 21, maxAge: 50, allowedCategories: ['SC', 'ST', 'EBC'], statesAllowed: ['Bihar'] },
    isPopular: true,
    iconName: 'time_to_leave'
  },
  {
    id: 'cg-mukhyamantri-sugam-sarak-yojana',
    title: 'Chhattisgarh Mukhyamantri Sugam Sarak Yojana (Paved Access to Public Buildings)',
    code: 'CG-SUGAM-SARAK-YOJANA',
    ministry: 'Public Works Department (PWD), Govt. of Chhattisgarh',
    origin: 'state',
    stateName: 'Chhattisgarh',
    category: 'Transport & Infrastructure',
    subCategory: 'Roads & Public Infrastructure',
    beneficiaries: ['Rural Citizens', 'Students', 'General Citizen'],
    benefitValue: '100% Paved Concrete Access Roads to All Hospitals, Schools, Anganwadis & Grain Collection Mandis',
    benefitNumericMin: 200000,
    benefitNumericMax: 5000000,
    description: 'Constructs paved concrete approach roads connecting muddy unpaved rural government facilities (schools, hospitals, grain procurement centers) to main roads.',
    eligibilityDescription: 'Gram Panchayats and public institutions in Chhattisgarh.',
    requiredDocs: ['Gram Sabha Proposal Entry'],
    deadline: 'CG PWD Portal (pwd.cg.nic.in)',
    officialWebsiteUrl: 'https://pwd.cg.nic.in',
    rules: { minAge: 0, maxAge: 100, statesAllowed: ['Chhattisgarh'] },
    isPopular: false,
    iconName: 'add_road'
  },
  {
    id: 'as-chief-ministers-samagra-gramya-unnayan-yojana-e-rickshaw',
    title: 'Assam CM Samagra Gramya Unnayan Yojana (CMSGUY EV & Tractor Grant)',
    code: 'AS-CMSGUY-TRACTOR-EV-GRANT',
    ministry: 'Mega Mission Society CMSGUY, Govt. of Assam',
    origin: 'state',
    stateName: 'Assam',
    category: 'Transport & Infrastructure',
    subCategory: 'Transport & Rural Infrastructure',
    beneficiaries: ['Farmers', 'Rural Citizens', 'Workers'],
    benefitValue: '70% Capital Financial Subsidy for Village Agricultural Tractors & Commercial Passenger E-Rickshaws',
    benefitNumericMin: 50000,
    benefitNumericMax: 350000,
    description: 'Distributes 70% subsidized farm tractors to revenue village farmer groups and passenger e-rickshaws to rural youth in Assam.',
    eligibilityDescription: 'Registered farmer groups (FPGs) and rural youth in Assam.',
    requiredDocs: ['Assam Domicile Certificate', 'Farmer Group Registration', 'Aadhaar Card'],
    deadline: 'CMSGUY Portal Assam (minmissioncmsguy.assam.gov.in)',
    officialWebsiteUrl: 'https://minmissioncmsguy.assam.gov.in',
    rules: { minAge: 18, maxAge: 60, statesAllowed: ['Assam'] },
    isPopular: true,
    iconName: 'agriculture'
  },
  {
    id: 'delhi-e-auto-and-electric-bus-charging-subsidy',
    title: 'Delhi EV Policy Electric Auto Concession & Charging Station Subsidy',
    code: 'DELHI-EV-POLICY-CHARGING',
    ministry: 'Transport Department, Govt. of NCT of Delhi',
    origin: 'state',
    stateName: 'Delhi',
    category: 'Transport & Infrastructure',
    subCategory: 'Transport & Clean Mobility',
    beneficiaries: ['Workers', 'General Citizen', 'Entrepreneurs'],
    benefitValue: '₹30,000 Purchase Subsidy for Electric Auto-Rickshaws + 100% Interest Subvention + ₹6,000 Charging Station Subsidy',
    benefitNumericMin: 6000,
    benefitNumericMax: 30000,
    description: 'Offers purchase subsidies, 5% interest subvention on EV loans, and grants for setting up public EV charging stations across Delhi.',
    eligibilityDescription: 'Commercial auto drivers, fleet operators, and building owners installing EV chargers in Delhi.',
    requiredDocs: ['Delhi Public Transport Badge / PSV Badge', 'Delhi Commercial Registration', 'Aadhaar Card'],
    deadline: 'Delhi EV Switch Portal (ev.delhi.gov.in)',
    officialWebsiteUrl: 'https://ev.delhi.gov.in',
    rules: { minAge: 18, maxAge: 70, statesAllowed: ['Delhi'] },
    isPopular: true,
    iconName: 'ev_station'
  },
  {
    id: 'jk-prime-ministers-development-package-pmdp-tunnels',
    title: 'J&K All-Weather Highway Tunnels & Cable Stayed Bridges Scheme',
    code: 'JK-PMDP-HIGHWAY-TUNNELS',
    ministry: 'MoRTH / NHIDCL / PWD J&K',
    origin: 'state',
    stateName: 'Jammu and Kashmir',
    category: 'Transport & Infrastructure',
    subCategory: 'Roads & All-Weather Connectivity',
    beneficiaries: ['General Citizen', 'Travelers', 'Workers'],
    benefitValue: '100% Fully Funded Multi-Km All-Weather Mountain Tunnels (Zojila, Chenani-Nashri, Z-Morh) Ensuring Zero Winter Blockades',
    benefitNumericMin: 10000000,
    benefitNumericMax: 1000000000,
    description: 'Constructs mega engineering mountain tunnels and bridges connecting Ladakh and Kashmir Valley all 365 days a year.',
    eligibilityDescription: 'Transporters, armed forces, and general public traveling through mountain passes in J&K and Ladakh.',
    requiredDocs: ['NHIDCL Project Execution Clearance'],
    deadline: 'NHIDCL Official Portal (nhidcl.com)',
    officialWebsiteUrl: 'https://nhidcl.com',
    rules: { minAge: 0, maxAge: 100, statesAllowed: ['Jammu and Kashmir'] },
    isPopular: true,
    iconName: 'tunnel'
  },
  {
    id: 'pm-gatishakti-national-master-plan-infrastructure',
    title: 'PM GatiShakti National Master Plan for Multi-Modal Connectivity',
    code: 'PM-GATISHAKTI-NATIONAL-MASTER-PLAN',
    ministry: 'DPIIT, Ministry of Commerce and Industry, Govt. of India',
    origin: 'central',
    category: 'Transport & Infrastructure',
    subCategory: 'Connectivity & Multi-Modal Infrastructure',
    beneficiaries: ['General Citizen', 'Workers', 'Entrepreneurs'],
    benefitValue: '100% GIS-Based Integrated Planning & Fast-Track Environmental Clearance for Ports, Rail, Highway & Logistics Parks',
    benefitNumericMin: 10000000,
    benefitNumericMax: 100000000,
    description: 'Digital master platform bringing 16 ministries together for integrated planning and synchronized execution of transport infrastructure.',
    eligibilityDescription: 'State road corporations, port authorities, freight operators, and logistics developers.',
    requiredDocs: ['GatiShakti Portal GIS Layout Approval'],
    deadline: 'PM GatiShakti Portal (gatishakti.gov.in)',
    officialWebsiteUrl: 'https://gatishakti.gov.in',
    rules: { minAge: 18, maxAge: 75 },
    isPopular: true,
    iconName: 'hub'
  },
  {
    id: 'national-monetization-pipeline-transport-nmp',
    title: 'National Monetization Pipeline (NMP Transport Infrastructure Development)',
    code: 'NMP-TRANSPORT-MONETIZATION',
    ministry: 'NITI Aayog & MoRTH / Ministry of Railways',
    origin: 'central',
    category: 'Transport & Infrastructure',
    subCategory: 'Public Infrastructure & Capital Generation',
    beneficiaries: ['General Citizen', 'Workers'],
    benefitValue: 'Re-investment of ₹6 Lakh Crore Monetized Assets into Building New High-Speed Rail Corridors & Expressways',
    benefitNumericMin: 5000000,
    benefitNumericMax: 50000000,
    description: 'Monetizes operational core infrastructure assets (toll roads, railway stations, airports) to fund new greenfield transportation projects.',
    eligibilityDescription: 'Infrastructure developers and general public using greenfield expressways and modern railway stations.',
    requiredDocs: ['Niti Aayog Monetization Project Charter'],
    deadline: 'NITI Aayog Portal',
    officialWebsiteUrl: 'https://niti.gov.in',
    rules: { minAge: 18, maxAge: 75 },
    isPopular: false,
    iconName: 'monetization_on'
  },
  {
    id: 'bharatmala-pariyojana-phase-1-expressways',
    title: 'Bharatmala Pariyojana (34,800 Km Economic Corridors & Ring Roads)',
    code: 'BHARATMALA-ECONOMIC-CORRIDORS',
    ministry: 'Ministry of Road Transport and Highways (MoRTH)',
    origin: 'central',
    category: 'Transport & Infrastructure',
    subCategory: 'Roads & Highway Corridors',
    beneficiaries: ['General Citizen', 'Workers', 'Travelers'],
    benefitValue: 'Construction of Access-Controlled Expressways, Border Roads, Multi-Modal Logistics Parks & Bypass Ring Roads',
    benefitNumericMin: 10000000,
    benefitNumericMax: 500000000,
    description: 'Flagship highway sector program optimizing freight and passenger movement across economic corridors, border routes, and coastal ports.',
    eligibilityDescription: 'Highway commuters, logistics trucks, and inter-state bus operators.',
    requiredDocs: ['NHAI Toll Tag / FASTag'],
    deadline: 'MoRTH Bharatmala Portal',
    officialWebsiteUrl: 'https://morth.nic.in',
    rules: { minAge: 0, maxAge: 100 },
    isPopular: true,
    iconName: 'add_road'
  },
  {
    id: 'sagarmala-programme-port-led-development',
    title: 'Sagarmala Programme (Port-Led Development & Inland Waterways Transit)',
    code: 'SAGARMALA-PORT-DEVELOPMENT',
    ministry: 'Ministry of Ports, Shipping and Waterways',
    origin: 'central',
    category: 'Transport & Infrastructure',
    subCategory: 'Public Infrastructure & Maritime Transport',
    beneficiaries: ['Workers', 'General Citizen', 'Entrepreneurs'],
    benefitValue: 'Modernization of Ports, Coastal Shipping Subsidies & Ro-Ro Ferry Services Connecting Islands',
    benefitNumericMin: 5000000,
    benefitNumericMax: 100000000,
    description: 'Unlocks India’s 7,500 km coastline through port modernization, coastal community development, and inland waterway ferry networks.',
    eligibilityDescription: 'Coastal communities, fishermen, maritime operators, and cargo exporters.',
    requiredDocs: ['Port Trust / Shipping Ministry Application'],
    deadline: 'Sagarmala Portal (sagarmala.gov.in)',
    officialWebsiteUrl: 'https://sagarmala.gov.in',
    rules: { minAge: 18, maxAge: 70 },
    isPopular: true,
    iconName: 'directions_boat'
  },
  {
    id: 'pradhan-mantri-gram-sadak-yojana-phase-3-pmgsy',
    title: 'Pradhan Mantri Gram Sadak Yojana (PMGSY-III Rural Road Upgradation)',
    code: 'PMGSY-PHASE-3-RURAL-ROADS',
    ministry: 'Ministry of Rural Development, Govt. of India',
    origin: 'central',
    category: 'Transport & Infrastructure',
    subCategory: 'Roads & Rural Mobility',
    beneficiaries: ['Rural Citizens', 'Farmers', 'Students'],
    benefitValue: 'Upgradation of 1,25,000 Km All-Weather Rural Roads Connecting Villages to Markets, Hospitals & Secondary Schools',
    benefitNumericMin: 500000,
    benefitNumericMax: 10000000,
    description: 'Upgrades key rural routes and major rural links connecting habitations to Gramin Agricultural Markets (GrAMs), higher secondary schools, and hospitals.',
    eligibilityDescription: 'Rural habitations across all states with population above 250 in special areas / 500 in plain areas.',
    requiredDocs: ['Meri Sadak App Grievance / Gram Panchayat Resolution'],
    deadline: 'PMGSY Official Portal (pmgsy.nic.in)',
    officialWebsiteUrl: 'https://pmgsy.nic.in',
    rules: { minAge: 0, maxAge: 100 },
    isPopular: true,
    iconName: 'add_road'
  },
  {
    id: 'fame-india-phase-2-ev-bus-subsidies',
    title: 'FAME-II (Faster Adoption and Manufacturing of Electric Vehicles in India)',
    code: 'FAME-2-EV-BUS-GRANT',
    ministry: 'Ministry of Heavy Industries, Govt. of India',
    origin: 'central',
    category: 'Transport & Infrastructure',
    subCategory: 'Transport & Clean Mobility',
    beneficiaries: ['Workers', 'General Citizen', 'Entrepreneurs'],
    benefitValue: 'Up to ₹50 Lakh Subsidy per Electric City Bus + Direct Upfront Purchase Discount on Electric 2W/3W/4W',
    benefitNumericMin: 10000,
    benefitNumericMax: 5000000,
    description: 'Promotes electrification of public transport by subsidizing 7,000 electric buses, 5 lakh e-3 wheelers, and 10 lakh e-2 wheelers.',
    eligibilityDescription: 'State transport undertakings, commercial fleet operators, and individual EV buyers.',
    requiredDocs: ['Vehicle Registration Certificate (RC)', 'Aadhaar Card', 'Manufacturer OEM Subsidy Claim'],
    deadline: 'FAME-II Portal (fame2.heavyindustries.gov.in)',
    officialWebsiteUrl: 'https://fame2.heavyindustries.gov.in',
    rules: { minAge: 18, maxAge: 75 },
    isPopular: true,
    iconName: 'electric_car'
  },
  {
    id: 'national-ropeways-development-programme-parvatmala',
    title: 'Parvatmala Pariyojana (National Ropeways Development Programme for Hilly Areas)',
    code: 'PARVATMALA-ROPEWAYS-MORTH',
    ministry: 'Ministry of Road Transport and Highways (MoRTH)',
    origin: 'central',
    category: 'Transport & Infrastructure',
    subCategory: 'Public Infrastructure & Mountain Mobility',
    beneficiaries: ['Rural Citizens', 'Travelers', 'General Citizen'],
    benefitValue: 'Ecologically Sustainable Passenger Ropeway Systems Connecting High-Altitude Pilgrimages & Inaccessible Hilly Villages',
    benefitNumericMin: 2000000,
    benefitNumericMax: 50000000,
    description: 'Constructs modern cable car ropeways as sustainable alternative to conventional roads in hilly terrain (Himachal, Uttarakhand, Sikkim, J&K).',
    eligibilityDescription: 'Commuters and pilgrims in mountainous regions across India.',
    requiredDocs: ['NHLML Project Clearance'],
    deadline: 'National Highways Logistics Management Limited (NHLML)',
    officialWebsiteUrl: 'https://morth.nic.in',
    rules: { minAge: 0, maxAge: 100 },
    isPopular: true,
    iconName: 'tram'
  },
  {
    id: 'pradhan-mantri-e-bus-sewa-scheme-10000-buses',
    title: 'PM-eBus Sewa Scheme (Deploying 10,000 Electric City Buses in 169 Cities)',
    code: 'PM-EBUS-SEWA-MHUA',
    ministry: 'Ministry of Housing and Urban Affairs (MoHUA)',
    origin: 'central',
    category: 'Transport & Infrastructure',
    subCategory: 'Transport & Clean Mobility',
    beneficiaries: ['General Citizen', 'Workers'],
    benefitValue: '10,000 Electric Buses Operating on Public-Private Partnership (PPP) Model with Central Operational Subsidy for 10 Years',
    benefitNumericMin: 1000000,
    benefitNumericMax: 20000000,
    description: 'Augments green urban bus operations in 169 cities with population 3 to 40 lakh lacking organized bus services.',
    eligibilityDescription: 'Urban commuters residing in non-metropolitan tier-2 and tier-3 cities across India.',
    requiredDocs: ['City Bus Pass / Daily Transit Ticket'],
    deadline: 'MoHUA Official Portal',
    officialWebsiteUrl: 'https://mohua.gov.in',
    rules: { minAge: 0, maxAge: 100 },
    isPopular: true,
    iconName: 'directions_bus'
  },
  {
    id: 'ka-shakti-scheme-free-bus-travel-for-women',
    title: 'Karnataka Shakti Scheme (100% Free State Bus Travel for Women)',
    code: 'KA-SHAKTI-FREE-BUS-WOMEN',
    ministry: 'Transport Department & KSRTC/BMTC, Govt. of Karnataka',
    origin: 'state',
    stateName: 'Karnataka',
    category: 'Transport & Infrastructure',
    subCategory: 'Transport & Free Public Transit',
    beneficiaries: ['Women', 'Students', 'Workers'],
    benefitValue: '100% Free Bus Fares on Non-AC Ordinary & Express State Buses across KSRTC, BMTC, NWKRTC, and KKRTC',
    benefitNumericMin: 12000,
    benefitNumericMax: 36000,
    description: 'Provides completely free public bus travel for all women domiciled in Karnataka within state borders.',
    eligibilityDescription: 'All female citizens (including transgender women) domiciled in Karnataka state.',
    requiredDocs: ['Shakti Smart Card / Karnataka Domicile ID (Aadhaar / Voter ID)'],
    deadline: 'Seva Sindhu Portal Karnataka (sevasindhuservices.karnataka.gov.in)',
    officialWebsiteUrl: 'https://ksrtc.karnataka.gov.in',
    rules: { minAge: 5, maxAge: 100, genderConstraint: 'Female', statesAllowed: ['Karnataka'] },
    isPopular: true,
    iconName: 'directions_bus'
  },
  {
    id: 'ts-mahalaxmi-scheme-free-bus-travel-women',
    title: 'Telangana Maha Lakshmi Scheme (Free TSRTC Bus Travel for Women)',
    code: 'TS-MAHALAKSHMI-FREE-BUS',
    ministry: 'Transport Department & TSRTC, Govt. of Telangana',
    origin: 'state',
    stateName: 'Telangana',
    category: 'Transport & Infrastructure',
    subCategory: 'Transport & Free Public Transit',
    beneficiaries: ['Women', 'Students', 'Workers'],
    benefitValue: '100% Zero-Fare Bus Tickets in Express, Palle Velugu & City Ordinary Buses of TGSRTC across Telangana',
    benefitNumericMin: 12000,
    benefitNumericMax: 36000,
    description: 'Allows women and girls of all ages domiciled in Telangana to travel free of cost in state-run public transport buses.',
    eligibilityDescription: 'Women and girls residing in Telangana state.',
    requiredDocs: ['Telangana Address Proof (Aadhaar Card / Voter ID)'],
    deadline: 'TGSRTC Official Portal',
    officialWebsiteUrl: 'https://tgsrtc.telangana.gov.in',
    rules: { minAge: 0, maxAge: 100, genderConstraint: 'Female', statesAllowed: ['Telangana'] },
    isPopular: true,
    iconName: 'directions_bus'
  },
  {
    id: 'tn-vidiyal-payana-thittam-free-bus-for-women',
    title: 'Tamil Nadu Vidiyal Payana Thittam (Zero-Ticket Fare Bus Scheme for Women)',
    code: 'TN-VIDIYAL-PAYANA-FREE-BUS',
    ministry: 'Transport Department & TNSTC/MTC, Govt. of Tamil Nadu',
    origin: 'state',
    stateName: 'Tamil Nadu',
    category: 'Transport & Infrastructure',
    subCategory: 'Transport & Free Public Transit',
    beneficiaries: ['Women', 'Persons with Disabilities', 'Senior Citizens'],
    benefitValue: '100% Zero-Fare Bus Travel in Town Pink Buses across All Metropolitan & District Bus Routes in TN',
    benefitNumericMin: 10000,
    benefitNumericMax: 30000,
    description: 'Enables free commute for women, female students, and disabled persons in government town buses across Tamil Nadu.',
    eligibilityDescription: 'Women, female students, disabled persons, and trans-women residing in Tamil Nadu.',
    requiredDocs: ['Tamil Nadu Smart Ration Card / Aadhaar Card'],
    deadline: 'TNSTC Official Portal',
    officialWebsiteUrl: 'https://tnstc.in',
    rules: { minAge: 5, maxAge: 100, statesAllowed: ['Tamil Nadu'] },
    isPopular: true,
    iconName: 'directions_bus'
  },
  {
    id: 'mh-punyashlok-ahilyadevi-holkar-free-bus-women',
    title: 'Maharashtra Mahila Samman Scheme (50% Concession on MSRTC Bus Tickets)',
    code: 'MH-MAHILA-SAMMAN-50-BUS',
    ministry: 'Transport Department & MSRTC, Govt. of Maharashtra',
    origin: 'state',
    stateName: 'Maharashtra',
    category: 'Transport & Infrastructure',
    subCategory: 'Transport & Mobility Concessions',
    beneficiaries: ['Women', 'Senior Citizens'],
    benefitValue: '50% Flat Discount Concession on All MSRTC Bus Types (Ordinary, Semi-Luxury, Shivshahi) for Women + 100% Free Travel for Senior Citizens (75+)',
    benefitNumericMin: 6000,
    benefitNumericMax: 18000,
    description: 'Provides 50% fare discount to all female passengers and 100% free travel for senior citizens above 75 years in Maharashtra ST buses.',
    eligibilityDescription: 'Women domiciled in Maharashtra and senior citizens aged 75+.',
    requiredDocs: ['Aadhaar Card / MSRTC Smart Card'],
    deadline: 'MSRTC Official Portal (msrtc.maharashtra.gov.in)',
    officialWebsiteUrl: 'https://msrtc.maharashtra.gov.in',
    rules: { minAge: 0, maxAge: 100, statesAllowed: ['Maharashtra'] },
    isPopular: true,
    iconName: 'directions_bus'
  },
  {
    id: 'up-mukhya-mantri-nagar-srijan-yojana-urban-infra',
    title: 'UP Mukhyamantri Nagar Srijan Yojana (Infrastructure in Newly Included Urban Bodies)',
    code: 'UP-NAGAR-SRIJAN-URBAN-INFRA',
    ministry: 'Urban Development Department, Govt. of UP',
    origin: 'state',
    stateName: 'Uttar Pradesh',
    category: 'Transport & Infrastructure',
    subCategory: 'Public Infrastructure & Urban Mobility',
    beneficiaries: ['General Citizen', 'Workers'],
    benefitValue: '100% State Funding for Roads, LED Streetlights, Parks, Community Halls & Drainage in Newly Formed Nagar Panchayats',
    benefitNumericMin: 1000000,
    benefitNumericMax: 20000000,
    description: 'Accelerates urban road, lighting, and civic infrastructure in newly created and expanded municipal bodies of UP.',
    eligibilityDescription: 'Urban local bodies (Nagar Panchayats / Palikas) in Uttar Pradesh.',
    requiredDocs: ['Nagar Panchayat Development DPR'],
    deadline: 'UP Urban Development Portal (urbandevelopment.up.nic.in)',
    officialWebsiteUrl: 'https://urbandevelopment.up.nic.in',
    rules: { minAge: 0, maxAge: 100, statesAllowed: ['Uttar Pradesh'] },
    isPopular: false,
    iconName: 'location_city'
  },
  {
    id: 'rj-mukhyamantri-chiranjeevi-sadak-suraksha-yojana',
    title: 'Rajasthan Mukhyamantri Sadak Suraksha Yojana (Road Safety Equipment & Crash Barriers)',
    code: 'RJ-SADAK-SURAKSHA-YOJANA',
    ministry: 'Transport and Road Safety Department, Govt. of Rajasthan',
    origin: 'state',
    stateName: 'Rajasthan',
    category: 'Transport & Infrastructure',
    subCategory: 'Roads & Public Safety',
    beneficiaries: ['General Citizen', 'Workers', 'Travelers'],
    benefitValue: 'Installation of Metal Beam Crash Barriers, Solar Cat-Eyes, Speed Cameras & Immediate ₹10,000 Cash Grant to Good Samaritans',
    benefitNumericMin: 10000,
    benefitNumericMax: 50000,
    description: 'Transforms accident blackspots into safe road zones and rewards citizens assisting road accident victims.',
    eligibilityDescription: 'Road commuters in Rajasthan and citizens saving accident victims.',
    requiredDocs: ['Good Samaritan Bank Passbook / Hospital Certificate'],
    deadline: 'Rajasthan Transport Dept (transport.rajasthan.gov.in)',
    officialWebsiteUrl: 'https://transport.rajasthan.gov.in',
    rules: { minAge: 18, maxAge: 70, statesAllowed: ['Rajasthan'] },
    isPopular: true,
    iconName: 'health_and_safety'
  },
  {
    id: 'gj-mukhyamantri-gram-sadak-yojana-rural-asphalt',
    title: 'Gujarat Mukhyamantri Gram Sadak Yojana (100% Resurfacing of Rural Asphalt Roads)',
    code: 'GJ-MMGSY-RURAL-ASPHALT',
    ministry: 'Roads and Buildings Department (R&B), Govt. of Gujarat',
    origin: 'state',
    stateName: 'Gujarat',
    category: 'Transport & Infrastructure',
    subCategory: 'Roads & Rural Mobility',
    beneficiaries: ['Rural Citizens', 'Farmers', 'General Citizen'],
    benefitValue: '100% Paved Bituminous Double-Lane Rural Roads Connecting Every Hamlet to State Highways',
    benefitNumericMin: 500000,
    benefitNumericMax: 10000000,
    description: 'Ensures zero unpaved roads in rural Gujarat by converting dirt roads into high-durability hot-mix asphalt roads.',
    eligibilityDescription: 'Gram Panchayats and rural commuters in Gujarat.',
    requiredDocs: ['Panchayat Resolution Letter'],
    deadline: 'R&B Department Gujarat (roads.gujarat.gov.in)',
    officialWebsiteUrl: 'https://roads.gujarat.gov.in',
    rules: { minAge: 0, maxAge: 100, statesAllowed: ['Gujarat'] },
    isPopular: true,
    iconName: 'add_road'
  },
  {
    id: 'hr-haryana-har-hith-store-and-e-bus-city-transport',
    title: 'Haryana City Bus Service Scheme (100% Zero-Emission Electric AC City Buses)',
    code: 'HR-ELECTRIC-CITY-BUS-SCHEME',
    ministry: 'Transport Department, Govt. of Haryana',
    origin: 'state',
    stateName: 'Haryana',
    category: 'Transport & Infrastructure',
    subCategory: 'Public Infrastructure & Electric Mobility',
    beneficiaries: ['General Citizen', 'Workers', 'Students'],
    benefitValue: '₹10 Flat Concessional City Fare + 100% Air-Conditioned Electric City Bus Routes in 10 Major Haryana Towns',
    benefitNumericMin: 500,
    benefitNumericMax: 5000,
    description: 'Deploys 450+ modern low-floor electric AC city buses across Panipat, Ambala, Hisar, Rohtak, and Karnal.',
    eligibilityDescription: 'Urban commuters and daily pass holders in Haryana.',
    requiredDocs: ['Haryana Smart City Transit Card'],
    deadline: 'Haryana Transport Dept (hartrans.gov.in)',
    officialWebsiteUrl: 'https://hartrans.gov.in',
    rules: { minAge: 0, maxAge: 100, statesAllowed: ['Haryana'] },
    isPopular: true,
    iconName: 'directions_bus'
  },
  {
    id: 'ga-goa-ev-policy-and-charging-infrastructure-subsidy',
    title: 'Goa EV Policy (Capital Subsidy for EV Charging Stations & Electric Auto Rickshaws)',
    code: 'GA-EV-CHARGING-SUBSIDY',
    ministry: 'Department of Clean Energy & Transport, Govt. of Goa',
    origin: 'state',
    stateName: 'Goa',
    category: 'Transport & Infrastructure',
    subCategory: 'Electric Mobility & Public Infrastructure',
    beneficiaries: ['Entrepreneurs', 'Workers', 'General Citizen'],
    benefitValue: 'Capital Subsidy up to ₹3.0 Lakh for Setting Up Fast EV Charging Stations + ₹30,000 Purchase Subsidy for Electric Two-Wheelers/Autos',
    benefitNumericMin: 30000,
    benefitNumericMax: 300000,
    description: 'Accelerates green mobility in Goa by subsidizing public charging infrastructure along coastal highways and tourist hubs.',
    eligibilityDescription: 'Goan residents, taxi drivers, and charging station entrepreneurs.',
    requiredDocs: ['Goa Domicile Certificate', 'RTO Registration Certificate', 'Electricity DISCOM Approval'],
    deadline: 'Goa Clean Energy Portal (goa.gov.in)',
    officialWebsiteUrl: 'https://goa.gov.in',
    rules: { minAge: 18, maxAge: 65, statesAllowed: ['Goa'] },
    isPopular: true,
    iconName: 'ev_station'
  },
  {
    id: 'sk-sikkim-ropeway-and-mountain-cable-car-scheme',
    title: 'Sikkim Eco-Ropeway & Mountain Mass Transit Infrastructure Scheme',
    code: 'SK-ROPEWAY-INFRA-SCHEME',
    ministry: 'Tourism & Urban Development Department, Govt. of Sikkim',
    origin: 'state',
    stateName: 'Sikkim',
    category: 'Transport & Infrastructure',
    subCategory: 'Public Infrastructure & Connectivity',
    beneficiaries: ['General Citizen', 'Travelers', 'Rural Citizens'],
    benefitValue: '100% State Funding for Passenger Cable Car Ropeway Passenger Lines (Gangtok, Namchi, Bhaleydhunga)',
    benefitNumericMin: 10000000,
    benefitNumericMax: 100000000,
    description: 'Constructs eco-friendly passenger ropeways in steep Himalayan mountain terrain, reducing traffic jams and providing last-mile mobility.',
    eligibilityDescription: 'Commuters and tourists in hill towns of Sikkim.',
    requiredDocs: ['Sikkim Urban Commuter Pass'],
    deadline: 'Sikkim Urban Dept Portal',
    officialWebsiteUrl: 'https://sikkim.gov.in',
    rules: { minAge: 0, maxAge: 100, statesAllowed: ['Sikkim'] },
    isPopular: false,
    iconName: 'route'
  },
  {
    id: 'tr-tripura-border-road-and-indus-corridor-scheme',
    title: 'Tripura Maitri Setu & Border Infrastructure Mobility Corridor Scheme',
    code: 'TR-MAITRI-SETU-CORRIDOR',
    ministry: 'Public Works Department (PWD Roads), Govt. of Tripura',
    origin: 'state',
    stateName: 'Tripura',
    category: 'Transport & Infrastructure',
    subCategory: 'Public Infrastructure & Connectivity',
    beneficiaries: ['General Citizen', 'Workers', 'Entrepreneurs'],
    benefitValue: '100% Paved 4-Lane Freight Corridors Connecting Agartala to Sabroom Chittagong Port Access Road',
    benefitNumericMin: 10000000,
    benefitNumericMax: 200000000,
    description: 'Transforms Tripura into the gateway to Southeast Asia through 4-lane high-speed trade and transit corridors.',
    eligibilityDescription: 'Freight operators, traders, and commuters in Tripura.',
    requiredDocs: ['Tripura PWD Transit Charter'],
    deadline: 'Tripura PWD Portal (pwd.tripura.gov.in)',
    officialWebsiteUrl: 'https://pwd.tripura.gov.in',
    rules: { minAge: 0, maxAge: 100, statesAllowed: ['Tripura'] },
    isPopular: false,
    iconName: 'alt_route'
  },
  {
    id: 'me-meghalaya-rural-bridge-and-footbridge-scheme',
    title: 'Meghalaya Chief Minister’s Rural Steel Bridge & Footbridge Construction Mission',
    code: 'ME-RURAL-FOOTBRIDGE-MISSION',
    ministry: 'Community and Rural Development Department, Govt. of Meghalaya',
    origin: 'state',
    stateName: 'Meghalaya',
    category: 'Transport & Infrastructure',
    subCategory: 'Roads & Rural Mobility',
    beneficiaries: ['Rural Citizens', 'Students', 'Farmers'],
    benefitValue: '100% State Grant for All-Weather Modular Steel Footbridges over Heavy Rain Rivers in Khasi & Garo Hills',
    benefitNumericMin: 500000,
    benefitNumericMax: 5000000,
    description: 'Replaces dangerous wooden planks with high-durability steel pedestrian footbridges across fast-flowing monsoon rivers in Meghalaya.',
    eligibilityDescription: 'Gram Sevak and village Dorbar Shnong in remote rainfall zones of Meghalaya.',
    requiredDocs: ['Dorbar Shnong Resolution / PWD Application'],
    deadline: 'Meghalaya C&RD Dept Portal (cnrd.gov.in)',
    officialWebsiteUrl: 'https://cnrd.gov.in',
    rules: { minAge: 0, maxAge: 100, statesAllowed: ['Meghalaya'] },
    isPopular: true,
    iconName: 'route'
  },
  {
    id: 'mn-manipur-ring-road-and-national-highway-4-lane',
    title: 'Manipur Imphal Ring Road & Hill District Highway Connectivity Scheme',
    code: 'MN-IMPHAL-RING-ROAD-SCHEME',
    ministry: 'Public Works Department (PWD Roads), Govt. of Manipur',
    origin: 'state',
    stateName: 'Manipur',
    category: 'Transport & Infrastructure',
    subCategory: 'Roads & Public Infrastructure',
    beneficiaries: ['General Citizen', 'Rural Citizens'],
    benefitValue: '100% State Funded 4-Lane Bypass Ring Road + Landslide Prevention Protection Walls along NH-37',
    benefitNumericMin: 10000000,
    benefitNumericMax: 150000000,
    description: 'Constructs Imphal bypass ring road and landslide-resistant mountain highways linking hill district headquarters.',
    eligibilityDescription: 'Commuters and transport operators in Manipur.',
    requiredDocs: ['Manipur PWD Infrastructure Project Charter'],
    deadline: 'Manipur PWD Portal (pwd.manipur.gov.in)',
    officialWebsiteUrl: 'https://pwd.manipur.gov.in',
    rules: { minAge: 0, maxAge: 100, statesAllowed: ['Manipur'] },
    isPopular: false,
    iconName: 'add_road'
  },
  {
    id: 'nl-nagaland-road-maintenance-and-pothole-free-mission',
    title: 'Nagaland Chief Minister’s Pothole-Free City Roads & Hill Highway Scheme',
    code: 'NL-POTHOLE-FREE-ROADS',
    ministry: 'Works & Housing Department (PWD), Govt. of Nagaland',
    origin: 'state',
    stateName: 'Nagaland',
    category: 'Transport & Infrastructure',
    subCategory: 'Roads & Connectivity',
    beneficiaries: ['General Citizen', 'Workers', 'Rural Citizens'],
    benefitValue: '100% Paved Bituminous Roads with Stone Masonry Retaining Walls in Kohima & Dimapur Municipal Areas',
    benefitNumericMin: 2000000,
    benefitNumericMax: 20000000,
    description: 'Upgrades monsoon-damaged urban roads in Kohima and Dimapur with heavy-duty drainage channels and asphalt paving.',
    eligibilityDescription: 'Residents and commuters across Nagaland municipalities.',
    requiredDocs: ['Nagaland Domicile Certificate / Municipal Pass'],
    deadline: 'Nagaland PWD Portal (npwd.nagaland.gov.in)',
    officialWebsiteUrl: 'https://npwd.nagaland.gov.in',
    rules: { minAge: 0, maxAge: 100, statesAllowed: ['Nagaland'] },
    isPopular: false,
    iconName: 'construction'
  },
  {
    id: 'mz-mizoram-kaladan-multimodal-transit-and-road-scheme',
    title: 'Mizoram Kaladan Multi-Modal Transport Corridor & Aizawl Bypass Scheme',
    code: 'MZ-KALADAN-TRANSIT-CORRIDOR',
    ministry: 'Public Works Department (PWD Roads), Govt. of Mizoram',
    origin: 'state',
    stateName: 'Mizoram',
    category: 'Transport & Infrastructure',
    subCategory: 'Public Infrastructure & Connectivity',
    beneficiaries: ['General Citizen', 'Workers', 'Entrepreneurs'],
    benefitValue: '100% State & Central Funding for High-Speed Hill Corridors Connecting Mizoram to Myanmar Port Access',
    benefitNumericMin: 10000000,
    benefitNumericMax: 200000000,
    description: 'Establishes high-capacity road transportation networks in Mizoram for international trade and smooth intra-state travel.',
    eligibilityDescription: 'Transporters, trade operators, and commuters in Mizoram.',
    requiredDocs: ['Mizoram PWD Project Documentation'],
    deadline: 'Mizoram PWD Portal (pwd.mizoram.gov.in)',
    officialWebsiteUrl: 'https://pwd.mizoram.gov.in',
    rules: { minAge: 0, maxAge: 100, statesAllowed: ['Mizoram'] },
    isPopular: false,
    iconName: 'alt_route'
  },
  {
    id: 'ar-arunachal-frontier-highway-and-trans-arunachal-highway',
    title: 'Arunachal Pradesh Frontier Highway & Border Connectivity Infrastructure Mission',
    code: 'AR-FRONTIER-HIGHWAY-MISSION',
    ministry: 'Public Works Department (PWD) & BRO, Govt. of Arunachal Pradesh',
    origin: 'state',
    stateName: 'Arunachal Pradesh',
    category: 'Transport & Infrastructure',
    subCategory: 'Roads & Public Infrastructure',
    beneficiaries: ['General Citizen', 'Rural Citizens', 'Workers'],
    benefitValue: '100% All-Weather 2-Lane Bituminous Border Highways with Double-Lane Tunnels (Sela Tunnel Corridor)',
    benefitNumericMin: 50000000,
    benefitNumericMax: 500000000,
    description: 'Constructs 2,000 km of border highways linking remotest high-altitude villages along the international border in Arunachal Pradesh.',
    eligibilityDescription: 'Border district residents, defense convoys, and mountain tourists in Arunachal Pradesh.',
    requiredDocs: ['Inner Line Permit (ILP) / Arunachal Domicile Certificate'],
    deadline: 'Arunachal PWD Portal (arunachalpwd.org)',
    officialWebsiteUrl: 'https://arunachalpwd.org',
    rules: { minAge: 0, maxAge: 100, statesAllowed: ['Arunachal Pradesh'] },
    isPopular: true,
    iconName: 'add_road'
  },
  {
    id: 'py-puducherry-smart-city-e-rickshaw-and-bus-shelter-scheme',
    title: 'Puducherry Smart City Public Transport & EV Shuttle Scheme',
    code: 'PY-SMART-CITY-E-SHUTTLE',
    ministry: 'Puducherry Transport Department & Smart City Development Ltd',
    origin: 'state',
    stateName: 'Puducherry',
    category: 'Transport & Infrastructure',
    subCategory: 'Public Infrastructure & Electric Mobility',
    beneficiaries: ['General Citizen', 'Travelers', 'Workers'],
    benefitValue: '100% Free Electric Shuttle Service in Boulevard Town + Smart Passenger Information Display Bus Shelters',
    benefitNumericMin: 1000,
    benefitNumericMax: 10000,
    description: 'Introduces clean zero-emission electric buses and automated smart bus stop shelters across Puducherry urban center.',
    eligibilityDescription: 'Urban commuters, students, and tourists in Puducherry.',
    requiredDocs: ['Puducherry Transit Card'],
    deadline: 'Puducherry Smart City Portal',
    officialWebsiteUrl: 'https://transport.py.gov.in',
    rules: { minAge: 0, maxAge: 100, statesAllowed: ['Puducherry'] },
    isPopular: true,
    iconName: 'directions_bus'
  }
];

console.log('Transport & Infrastructure schemes count updated:', transportInfraSchemes.length);

fs.writeFileSync('temp_transport_infra.json', JSON.stringify(transportInfraSchemes, null, 2));


