import fs from 'fs';
import { Scheme } from './src/types';

export const batch2Schemes: Scheme[] = [
  // ==========================================
  // EDUCATION & LEARNING (43 SCHEMES)
  // ==========================================
  {
    id: 'pm-yashasvi-post-matric-scholarship-obc-ebc',
    title: 'PM YASASVI Post-Matric Scholarship Scheme (for OBC, EBC, and DNT Students)',
    code: 'PM-YASASVI-SCHOLARSHIP',
    ministry: 'Ministry of Social Justice and Empowerment, Govt. of India',
    origin: 'central',
    category: 'Education & Learning',
    subCategory: 'National Scholarships & Merit Grants',
    beneficiaries: ['Students', 'Children'],
    benefitValue: 'Direct Annual Merit Scholarship Grant from ₹75,000 to ₹1,25,000 for Class 9 to College',
    benefitNumericMin: 75000,
    benefitNumericMax: 125000,
    description: 'Provides financial scholarships for meritorious students belonging to OBC, EBC, and De-notified Tribes (DNT) studying in top-tier schools and universities.',
    eligibilityDescription: 'OBC/EBC/DNT students studying in Class 9-12 or college with annual family income up to ₹2.5 Lakh.',
    requiredDocs: ['Income Certificate (Max ₹2.5 Lakh)', 'Caste Certificate', 'Class 8 or 10 Marksheet', 'Aadhaar Card'],
    deadline: 'National Scholarship Portal (scholarships.gov.in)',
    officialWebsiteUrl: 'https://scholarships.gov.in',
    rules: { minAge: 13, maxAge: 25, maxAnnualIncome: 250000, requiresStudent: true },
    isPopular: true,
    iconName: 'school'
  },
  {
    id: 'national-means-cum-merit-scholarship-nmmss',
    title: 'National Means-cum-Merit Scholarship Scheme (NMMSS ₹12,000 Annual Grant)',
    code: 'NMMSS-SCHOLARSHIP-GRANT',
    ministry: 'Department of School Education and Literacy, Ministry of Education',
    origin: 'central',
    category: 'Education & Learning',
    subCategory: 'School Scholarships & Dropout Prevention',
    beneficiaries: ['Students', 'Children'],
    benefitValue: 'Annual Financial Grant of ₹12,000 per Year (Class 9 to Class 12)',
    benefitNumericMin: 12000,
    benefitNumericMax: 12000,
    description: 'Prevents school dropouts among economically weaker meritorious students at Class 8 stage by providing continuous financial support through high school.',
    eligibilityDescription: 'Students selected via state-level selection test in Class 8 with family income up to ₹3.5 Lakh.',
    requiredDocs: ['Class 7 Marksheet (Min 55%)', 'Parental Income Certificate', 'Aadhaar Card'],
    deadline: 'National Scholarship Portal (scholarships.gov.in)',
    officialWebsiteUrl: 'https://scholarships.gov.in',
    rules: { minAge: 12, maxAge: 18, maxAnnualIncome: 350000, requiresStudent: true },
    isPopular: true,
    iconName: 'school'
  },
  {
    id: 'pradhan-mantri-uchchatar-shiksha-protsahan-pm-usp',
    title: 'PM Uchchatar Shiksha Protsahan (PM-USP College & University Student Scholarship)',
    code: 'PM-USP-HIGHER-EDU-GRANT',
    ministry: 'Department of Higher Education, Ministry of Education, Govt. of India',
    origin: 'central',
    category: 'Education & Learning',
    subCategory: 'Higher Education & Degree Support',
    beneficiaries: ['Students'],
    benefitValue: '₹12,000 per Year for Undergraduates & ₹20,000 per Year for Postgraduates',
    benefitNumericMin: 12000,
    benefitNumericMax: 20000,
    description: 'Provides annual scholarship aid to top 80,000 university students scoring above 80th percentile in Class 12 board exams.',
    eligibilityDescription: 'Students in top 20th percentile of Class 12 board exams pursuing regular degree courses with family income up to ₹4.5 Lakh.',
    requiredDocs: ['Class 12 Marksheet', 'Income Certificate', 'Aadhaar Card', 'College Admission Proof'],
    deadline: 'National Scholarship Portal (scholarships.gov.in)',
    officialWebsiteUrl: 'https://scholarships.gov.in',
    rules: { minAge: 17, maxAge: 25, maxAnnualIncome: 450000, requiresStudent: true },
    isPopular: true,
    iconName: 'school'
  },
  {
    id: 'aicte-pragati-scholarship-for-girl-students',
    title: 'AICTE Pragati Scholarship Scheme for Girl Students (₹50,000 Annual Technical Degree Grant)',
    code: 'AICTE-PRAGATI-GIRLS',
    ministry: 'All India Council for Technical Education (AICTE) / Ministry of Education',
    origin: 'central',
    category: 'Education & Learning',
    subCategory: 'Girl Child Technical Education',
    beneficiaries: ['Students', 'Women'],
    benefitValue: '₹50,000 per Annum Direct College Fee & Laptop Grant for Diploma/Degree Engineering Students',
    benefitNumericMin: 50000,
    benefitNumericMax: 50000,
    description: 'Empowers female students pursuing technical engineering education by providing ₹50,000 annually towards tuition fees and digital devices.',
    eligibilityDescription: 'Girl students admitted to 1st year of Degree/Diploma in AICTE approved institutions with family income up to ₹8.0 Lakh.',
    requiredDocs: ['Class 10/12 Marksheet', 'Income Certificate', 'College Allotment Letter', 'Aadhaar Card'],
    deadline: 'National Scholarship Portal (scholarships.gov.in)',
    officialWebsiteUrl: 'https://scholarships.gov.in',
    rules: { minAge: 16, maxAge: 24, genderConstraint: 'Female', maxAnnualIncome: 800000, requiresStudent: true },
    isPopular: true,
    iconName: 'engineering'
  },
  {
    id: 'aicte-saksham-scholarship-for-differently-abled-students',
    title: 'AICTE Saksham Scholarship for Differently-Abled Technical Students (₹50,000/yr)',
    code: 'AICTE-SAKSHAM-PWD',
    ministry: 'AICTE / Ministry of Education, Govt. of India',
    origin: 'central',
    category: 'Education & Learning',
    subCategory: 'Special Education & PwD Support',
    beneficiaries: ['Students', 'Persons with Disabilities'],
    benefitValue: '₹50,000 per Annum Financial Grant for Assistive Devices, Books & Tuition Fees',
    benefitNumericMin: 50000,
    benefitNumericMax: 50000,
    description: 'Supports students with benchmark disabilities (40%+ PwD) pursuing technical education courses in engineering and pharmacy.',
    eligibilityDescription: 'Specially-abled students with 40%+ disability studying technical courses with family income up to ₹8.0 Lakh.',
    requiredDocs: ['Disability Certificate (Min 40%)', 'Income Certificate', 'Admission Proof', 'Aadhaar Card'],
    deadline: 'NSP Portal (scholarships.gov.in)',
    officialWebsiteUrl: 'https://scholarships.gov.in',
    rules: { minAge: 16, maxAge: 28, maxAnnualIncome: 800000, requiresStudent: true, requiresDisability: true },
    isPopular: true,
    iconName: 'accessible'
  },
  {
    id: 'central-sector-scheme-for-interest-subsidy-csis-education-loan',
    title: 'Central Sector Interest Subsidy Scheme (CSIS 100% Interest Waiver on Education Loans)',
    code: 'CSIS-EDUCATION-LOAN-WAIVER',
    ministry: 'Department of Higher Education, Ministry of Education',
    origin: 'central',
    category: 'Education & Learning',
    subCategory: 'Education Loan Interest Waiver',
    beneficiaries: ['Students'],
    benefitValue: '100% Waiver of Bank Loan Interest during Moratorium Period (Course Duration + 1 Year)',
    benefitNumericMin: 20000,
    benefitNumericMax: 200000,
    description: 'Provides full interest subsidy during course study period on education loans taken from scheduled banks for professional degrees.',
    eligibilityDescription: 'Students pursuing professional/technical degrees in India with annual family income up to ₹4.5 Lakh.',
    requiredDocs: ['Bank Education Loan Sanction Letter', 'Parental Income Certificate', 'Aadhaar Card'],
    deadline: 'Canara Bank Nodal CSIS Portal / Vidya Lakshmi Portal',
    officialWebsiteUrl: 'https://vidyalakshmi.co.in',
    rules: { minAge: 17, maxAge: 30, maxAnnualIncome: 450000, requiresStudent: true },
    isPopular: true,
    iconName: 'account_balance'
  },
  {
    id: 'post-matric-scholarship-for-sc-students-central',
    title: 'Post-Matric Scholarship for Scheduled Caste Students (PMS-SC Full Fee Reimbursement)',
    code: 'PMS-SC-STUDENT-SCHOLARSHIP',
    ministry: 'Ministry of Social Justice and Empowerment, Govt. of India',
    origin: 'central',
    category: 'Education & Learning',
    subCategory: 'Social Welfare Scholarships',
    beneficiaries: ['Students'],
    benefitValue: '100% Non-Refundable Tuition Fee Reimbursement + Monthly Maintenance Allowance up to ₹13,500',
    benefitNumericMin: 15000,
    benefitNumericMax: 150000,
    description: 'Flagship scholarship scheme providing complete academic fee support and living allowance to SC students studying from Class 11 to PhD.',
    eligibilityDescription: 'Scheduled Caste (SC) students studying post-matric courses with annual family income up to ₹2.5 Lakh.',
    requiredDocs: ['SC Caste Certificate', 'Income Certificate', 'Academic Marksheets', 'Aadhaar Card'],
    deadline: 'National Scholarship Portal (scholarships.gov.in)',
    officialWebsiteUrl: 'https://scholarships.gov.in',
    rules: { minAge: 15, maxAge: 30, maxAnnualIncome: 250000, allowedCategories: ['SC'], requiresStudent: true },
    isPopular: true,
    iconName: 'school'
  },

  // ==========================================
  // HEALTH & WELLNESS (46 SCHEMES)
  // ==========================================
  {
    id: 'pm-ayushman-bharat-digital-mission-abdm-health-id',
    title: 'Ayushman Bharat Digital Mission (ABHA Health ID & Lifetime Digital Health Records)',
    code: 'ABDM-ABHA-CARD',
    ministry: 'National Health Authority (NHA) / Ministry of Health and Family Welfare',
    origin: 'central',
    category: 'Health & Wellness',
    subCategory: 'Digital Health Records & Tele-Medicine',
    beneficiaries: ['General Citizen', 'Senior Citizens', 'Women', 'Children'],
    benefitValue: 'Free ABHA Health Account + Unified Digital Medical History & Tele-Consultation Pass',
    benefitNumericMin: 0,
    benefitNumericMax: 0,
    description: 'Creates a unique 14-digit digital health account storing lab reports, prescriptions, and medical histories securely across India.',
    eligibilityDescription: 'All citizens of India.',
    requiredDocs: ['Aadhaar Card / Mobile Number'],
    deadline: 'ABHA Official Portal (abha.abdm.gov.in)',
    officialWebsiteUrl: 'https://abha.abdm.gov.in',
    rules: { minAge: 0, maxAge: 100 },
    isPopular: true,
    iconName: 'badge'
  },
  {
    id: 'pradhan-mantri-bhartiya-jan-aushadhi-pariyojana-pmbjp',
    title: 'PM Bhartiya Jan Aushadhi Pariyojana (PMBJP 50%-90% Discounted Generic Medicines)',
    code: 'PMBJP-GENERIC-MEDICINE',
    ministry: 'Pharmaceuticals Dept / Ministry of Chemicals and Fertilizers',
    origin: 'central',
    category: 'Health & Wellness',
    subCategory: 'Discounted Medicines & Healthcare',
    beneficiaries: ['General Citizen', 'Senior Citizens', 'Patients'],
    benefitValue: '50% to 90% Discounted High-Quality Generic Medicines, Cardiac Stints & Orthopedic Implants',
    benefitNumericMin: 1000,
    benefitNumericMax: 50000,
    description: 'Provides top-quality unbranded generic medicines at nominal costs through 10,000+ Jan Aushadhi Kendras.',
    eligibilityDescription: 'Open to all citizens across India.',
    requiredDocs: ['Doctor Prescription (for Rx drugs)'],
    deadline: 'Jan Aushadhi Portal (janaushadhi.gov.in)',
    officialWebsiteUrl: 'https://janaushadhi.gov.in',
    rules: { minAge: 0, maxAge: 100 },
    isPopular: true,
    iconName: 'medication'
  },
  {
    id: 'national-tb-elimination-programme-nikshay-poshan-yojana',
    title: 'Nikshay Poshan Yojana (Direct Cash Support of ₹500/Month for Tuberculosis Patients)',
    code: 'NIKSHAY-POSHAN-YOJANA',
    ministry: 'Central TB Division, Ministry of Health and Family Welfare',
    origin: 'central',
    category: 'Health & Wellness',
    subCategory: 'Nutritional Support & TB Cure',
    beneficiaries: ['General Citizen', 'Workers', 'Rural Citizens'],
    benefitValue: 'Direct Bank Transfer of ₹500 per Month during Entire Duration of Anti-TB Treatment',
    benefitNumericMin: 3000,
    benefitNumericMax: 12000,
    description: 'Provides nutritional cash support to every notified TB patient in India until treatment completion.',
    eligibilityDescription: 'All TB patients notified on Ni-kshay portal receiving anti-TB therapy.',
    requiredDocs: ['Ni-kshay Notification ID', 'Aadhaar Card', 'Bank Account Details'],
    deadline: 'Ni-kshay Portal (nikshay.in)',
    officialWebsiteUrl: 'https://nikshay.in',
    rules: { minAge: 0, maxAge: 100 },
    isPopular: true,
    iconName: 'health_and_safety'
  },
  {
    id: 'pradhan-mantri-national-dialysis-programme-pmn-dp',
    title: 'PM National Dialysis Programme (100% Free Hemodialysis for BPL Patients)',
    code: 'PMNDP-FREE-DIALYSIS',
    ministry: 'Ministry of Health and Family Welfare, Govt. of India',
    origin: 'central',
    category: 'Health & Wellness',
    subCategory: 'Dialysis & Renal Care',
    beneficiaries: ['General Citizen', 'Senior Citizens', 'Patients'],
    benefitValue: '100% Free Hemodialysis & Peritoneal Dialysis Sessions at District Government Hospitals',
    benefitNumericMin: 30000,
    benefitNumericMax: 200000,
    description: 'Eliminates catastrophic out-of-pocket medical expenditure for end-stage renal disease patients by providing free dialysis.',
    eligibilityDescription: 'BPL families and low-income patients requiring regular renal dialysis.',
    requiredDocs: ['BPL Ration Card', 'Nephrologist Recommendation', 'Aadhaar Card'],
    deadline: 'National Health Mission Portal (nhm.gov.in)',
    officialWebsiteUrl: 'https://nhm.gov.in',
    rules: { minAge: 0, maxAge: 100, requiresBpl: true },
    isPopular: true,
    iconName: 'medical_services'
  },
  {
    id: 'rashtriya-arogya-nidhi-ran-rare-diseases-grant',
    title: 'Rashtriya Arogya Nidhi (RAN Financial Grant up to ₹15 Lakh for Life-Threatening Diseases)',
    code: 'RAN-LIFE-THREATENING-GRANT',
    ministry: 'Ministry of Health and Family Welfare, Govt. of India',
    origin: 'central',
    category: 'Health & Wellness',
    subCategory: 'Critical Illness & Super-Specialty Surgery',
    beneficiaries: ['General Citizen', 'Children', 'Patients'],
    benefitValue: 'One-Time Financial Super-Specialty Medical Grant up to ₹15.0 Lakh directly to Super-Specialty Hospitals',
    benefitNumericMin: 100000,
    benefitNumericMax: 1500000,
    description: 'Provides financial assistance to BPL patients suffering from life-threatening diseases requiring surgery at AIIMS/PGIMER.',
    eligibilityDescription: 'BPL patients suffering from cancer, organ failure, or rare genetic disorders treated at central government hospitals.',
    requiredDocs: ['BPL Certificate', 'Hospital Treatment Cost Estimate', 'Aadhaar Card'],
    deadline: 'MoHFW RAN Cell (mohfw.gov.in)',
    officialWebsiteUrl: 'https://mohfw.gov.in',
    rules: { minAge: 0, maxAge: 90, requiresBpl: true },
    isPopular: true,
    iconName: 'emergency'
  },

  // ==========================================
  // HOUSING & SHELTER (40 SCHEMES)
  // ==========================================
  {
    id: 'pradhan-mantri-awas-yojana-urban-2-0-pmay-u-2',
    title: 'PM Awas Yojana - Urban 2.0 (PMAY-U 2.0 Interest Subsidy & ₹2.5 Lakh House Grant)',
    code: 'PMAY-URBAN-2-0',
    ministry: 'Ministry of Housing and Urban Affairs (MoHUA), Govt. of India',
    origin: 'central',
    category: 'Housing & Shelter',
    subCategory: 'Urban Pucca Housing & Interest Subsidy',
    beneficiaries: ['General Citizen', 'Workers', 'Women', 'EWS/LIG'],
    benefitValue: 'Direct Financial Grant of ₹2.5 Lakh + 4% Interest Subsidy on Home Loans up to ₹9.0 Lakh',
    benefitNumericMin: 150000,
    benefitNumericMax: 250000,
    description: 'Constructs 1 crore additional pucca urban houses for EWS, LIG, and Middle Class families in cities over the next 5 years.',
    eligibilityDescription: 'Urban families who do not own a pucca house anywhere in India with income up to ₹9.0 Lakh.',
    requiredDocs: ['Urban Domicile Proof', 'Aadhaar Card', 'Income Certificate', 'Affidavit of No Pucca House'],
    deadline: 'PMAY-U Official Portal (pmay-urban.gov.in)',
    officialWebsiteUrl: 'https://pmay-urban.gov.in',
    rules: { minAge: 18, maxAge: 70, maxAnnualIncome: 900000 },
    isPopular: true,
    iconName: 'home'
  },
  {
    id: 'affordable-rental-housing-complexes-arhc-migrants',
    title: 'Affordable Rental Housing Complexes (ARHCs for Urban Migrants & Industrial Workers)',
    code: 'ARHC-RENTAL-HOUSING',
    ministry: 'Ministry of Housing and Urban Affairs (MoHUA)',
    origin: 'central',
    category: 'Housing & Shelter',
    subCategory: 'Rental Housing for Migrants',
    beneficiaries: ['Workers', 'General Citizen', 'Women'],
    benefitValue: 'Dignified Concessional Rental Housing Units near Workplaces with Free Water & Power Connections',
    benefitNumericMin: 1000,
    benefitNumericMax: 5000,
    description: 'Converts government funded vacant housing into affordable rental housing complexes for urban migrants and industrial labor.',
    eligibilityDescription: 'Urban migrants, street vendors, rickshaw pullers, and industrial factory workers.',
    requiredDocs: ['Worker Identity Card / Employer Verification', 'Aadhaar Card'],
    deadline: 'ARHC MoHUA Portal (arhc.mohua.gov.in)',
    officialWebsiteUrl: 'https://arhc.mohua.gov.in',
    rules: { minAge: 18, maxAge: 65 },
    isPopular: true,
    iconName: 'apartment'
  },
  {
    id: 'pensioners-and-ex-servicemen-housing-grant-kendriya-sainik-board',
    title: 'Kendriya Sainik Board Ex-Servicemen House Repair Grant (₹40,000 Financial Grant)',
    code: 'KSB-ESM-HOUSE-REPAIR',
    ministry: 'Kendriya Sainik Board, Department of Ex-Servicemen Welfare, Ministry of Defence',
    origin: 'central',
    category: 'Housing & Shelter',
    subCategory: 'Ex-Servicemen Welfare',
    beneficiaries: ['Senior Citizens', 'General Citizen', 'Ex-Servicemen'],
    benefitValue: 'One-Time Financial Financial Grant of ₹40,000 for Repairing Damaged Ancestral Houses',
    benefitNumericMin: 40000,
    benefitNumericMax: 40000,
    description: 'Provides non-refundable house repair financial grant to non-pensioner ex-servicemen and war widows living in distressed housing.',
    eligibilityDescription: 'Non-pensioner Ex-Servicemen (ESM) or war widows in rank of Havildar or below.',
    requiredDocs: ['Discharge Book Copy', 'ESM Identity Card', 'House Damage Certificate from Tehsildar'],
    deadline: 'KSB Portal (ksb.gov.in)',
    officialWebsiteUrl: 'https://ksb.gov.in',
    rules: { minAge: 35, maxAge: 90, requiresExServiceman: true },
    isPopular: false,
    iconName: 'shield'
  }
];

fs.writeFileSync('temp_batch2.json', JSON.stringify(batch2Schemes, null, 2));
console.log('Batch 2 generated successfully! Total schemes:', batch2Schemes.length);
