import fs from 'fs';
import { Scheme } from './src/types';

export const batch1Schemes: Scheme[] = [
  // ==========================================
  // AGRICULTURE, RURAL & ENVIRONMENT (45 SCHEMES)
  // ==========================================
  {
    id: 'pm-pranam-chemical-fertilizer-reduction-scheme',
    title: 'PM-PRANAM (Programme for Restoration, Awareness, Nourishment and Amelioration of Mother Earth)',
    code: 'PM-PRANAM-FERTILIZER',
    ministry: 'Ministry of Chemicals and Fertilizers, Govt. of India',
    origin: 'central',
    category: 'Agriculture, Rural & Environment',
    subCategory: 'Organic Farming & Soil Health',
    beneficiaries: ['Farmers', 'Rural Citizens'],
    benefitValue: '50% Financial Subsidy Grant to States for Bio-Fertilizer Plants & Organic Farm Inputs',
    benefitNumericMin: 10000,
    benefitNumericMax: 500000,
    description: 'Promotes balanced use of chemical fertilizers by encouraging natural, bio, and organic fertilizers through state performance grants.',
    eligibilityDescription: 'Farmers adopting organic farming and local panchayats reducing chemical fertilizer use.',
    requiredDocs: ['Land Ownership Document (7/12 / Khasra)', 'Aadhaar Card', 'Soil Health Card'],
    deadline: 'PM-PRANAM Portal (fert.nic.in)',
    officialWebsiteUrl: 'https://fert.nic.in',
    rules: { minAge: 18, maxAge: 80, requiresFarmer: true },
    isPopular: true,
    iconName: 'eco'
  },
  {
    id: 'national-beekeeping-and-honey-mission-nbhm',
    title: 'National Beekeeping and Honey Mission (NBHM - Sweet Revolution Grant)',
    code: 'NBHM-HONEY-MISSION',
    ministry: 'Ministry of Agriculture and Farmers Welfare, Govt. of India',
    origin: 'central',
    category: 'Agriculture, Rural & Environment',
    subCategory: 'Agri-Horticulture & Bee Keeping',
    beneficiaries: ['Farmers', 'Entrepreneurs', 'Rural Citizens'],
    benefitValue: '80% Capital Subsidy up to ₹4.0 Lakh for Beehive Boxes, Extraction Units & Processing Equipment',
    benefitNumericMin: 50000,
    benefitNumericMax: 400000,
    description: 'Promotes scientific beekeeping for crop pollination and raw honey production under Sweet Revolution.',
    eligibilityDescription: 'Small farmers, landless agricultural workers, and self-help groups (SHGs).',
    requiredDocs: ['Aadhaar Card', 'Honey Bee Training Certificate', 'Bank Account Details'],
    deadline: 'Madhukranti Portal (madhuqranti.in)',
    officialWebsiteUrl: 'https://madhuqranti.in',
    rules: { minAge: 18, maxAge: 70 },
    isPopular: true,
    iconName: 'hive'
  },
  {
    id: 'national-mission-on-edible-oils-oil-palm-nmeo-op',
    title: 'National Mission on Edible Oils - Oil Palm (NMEO-OP Subsidy)',
    code: 'NMEO-OP-OIL-PALM',
    ministry: 'Ministry of Agriculture and Farmers Welfare, Govt. of India',
    origin: 'central',
    category: 'Agriculture, Rural & Environment',
    subCategory: 'Crop Support & Plantation',
    beneficiaries: ['Farmers'],
    benefitValue: 'Capital Grant of ₹29,000 per Hectare for Oil Palm Planting Material + Maintenance Allowance',
    benefitNumericMin: 29000,
    benefitNumericMax: 150000,
    description: 'Provides high planting material subsidies and price viability gap payments for farmers cultivating oil palm in Northeast and Southern states.',
    eligibilityDescription: 'Farmers owning agricultural land suitable for oil palm plantation.',
    requiredDocs: ['Land Title Deed', 'Aadhaar Card', 'Soil Suitability Test Report'],
    deadline: 'NMEO Portal (oilpalm.dac.gov.in)',
    officialWebsiteUrl: 'https://oilpalm.dac.gov.in',
    rules: { minAge: 18, maxAge: 75, requiresFarmer: true },
    isPopular: false,
    iconName: 'nature'
  },
  {
    id: 'sub-mission-on-seeds-and-planting-material-smsp',
    title: 'Sub-Mission on Seeds and Planting Material (SMSP Certified Seed Subsidy)',
    code: 'SMSP-SEED-SUBSIDY',
    ministry: 'Department of Agriculture and Farmers Welfare',
    origin: 'central',
    category: 'Agriculture, Rural & Environment',
    subCategory: 'Seed Infrastructure & Crop Yield',
    beneficiaries: ['Farmers'],
    benefitValue: '50% Subsidy on High-Yielding Certified HYV Seeds & Foundation Seed Production',
    benefitNumericMin: 2000,
    benefitNumericMax: 25000,
    description: 'Ensures availability of high-quality climate-resilient certified seeds to farmers at heavily subsidized prices.',
    eligibilityDescription: 'All practicing farmers registered on state seed portals.',
    requiredDocs: ['Aadhaar Card', 'Land Possession Certificate', 'Kisan Credit Card'],
    deadline: 'Seednet India Portal (seednet.gov.in)',
    officialWebsiteUrl: 'https://seednet.gov.in',
    rules: { minAge: 18, maxAge: 85, requiresFarmer: true },
    isPopular: true,
    iconName: 'grain'
  },
  {
    id: 'mis-price-deficiency-payment-scheme-market-intervention',
    title: 'Market Intervention Scheme and Price Support Scheme (MIS-PSS Crop Safety Net)',
    code: 'MIS-PSS-PRICE-SUPPORT',
    ministry: 'Ministry of Agriculture and Farmers Welfare, Govt. of India',
    origin: 'central',
    category: 'Agriculture, Rural & Environment',
    subCategory: 'Market Support & Price Stabilization',
    beneficiaries: ['Farmers'],
    benefitValue: '100% Procurement Guarantee at Minimum Support Price (MSP) or Price Deficiency Payment',
    benefitNumericMin: 10000,
    benefitNumericMax: 200000,
    description: 'Protects horticultural and perishable crop growers from distress sale during bumper harvest market gluts.',
    eligibilityDescription: 'Growers of perishable agricultural and horticultural commodities.',
    requiredDocs: ['Crop Sowing Certificate (Girdawari)', 'Aadhaar Card', 'Bank Passbook'],
    deadline: 'NAFED Procurement Portal (nafed-india.com)',
    officialWebsiteUrl: 'https://nafed-india.com',
    rules: { minAge: 18, maxAge: 85, requiresFarmer: true },
    isPopular: true,
    iconName: 'storefront'
  },
  {
    id: 'pradhan-mantri-matsya-sampada-yojana-deep-sea-fishing',
    title: 'PM Matsya Sampada Yojana (Deep Sea Fishing Vessel & Fish Cage Farming Subsidy)',
    code: 'PMMSY-DEEP-SEA-FISHING',
    ministry: 'Department of Fisheries, Ministry of Fisheries, Animal Husbandry & Dairying',
    origin: 'central',
    category: 'Agriculture, Rural & Environment',
    subCategory: 'Fisheries & Aquaculture',
    beneficiaries: ['Farmers', 'Workers', 'Entrepreneurs'],
    benefitValue: 'Up to 60% Financial Subsidy (Max ₹15 Lakh) for Fish Pond Construction, Biofloc Units & Boats',
    benefitNumericMin: 100000,
    benefitNumericMax: 1500000,
    description: 'Modernizes inland and marine fisheries, biofloc technology, recirculatory aquaculture systems (RAS), and cold chain infrastructure.',
    eligibilityDescription: 'Traditional fishermen, fish farmers, women cooperatives, and SC/ST aquaculture entrepreneurs.',
    requiredDocs: ['Fisherman ID Card / Inland Land Document', 'Aadhaar Card', 'Project Proposal'],
    deadline: 'PMMSY Official Portal (pmmsy.dof.gov.in)',
    officialWebsiteUrl: 'https://pmmsy.dof.gov.in',
    rules: { minAge: 18, maxAge: 70 },
    isPopular: true,
    iconName: 'phishing'
  },
  {
    id: 'national-livestock-mission-breed-development-grant',
    title: 'National Livestock Mission (NLM Breed Development & Fodder Farm Capital Subsidy)',
    code: 'NLM-BREED-DEVELOPMENT',
    ministry: 'Department of Animal Husbandry and Dairying, Govt. of India',
    origin: 'central',
    category: 'Agriculture, Rural & Environment',
    subCategory: 'Animal Husbandry & Livestock',
    beneficiaries: ['Farmers', 'Entrepreneurs', 'Rural Citizens'],
    benefitValue: '50% Capital Subsidy up to ₹50 Lakh for Goat, Sheep, Pig & Poultry Breeding Farms',
    benefitNumericMin: 250000,
    benefitNumericMax: 5000000,
    description: 'Subsidizes commercial breeding units for goats, sheep, pigs, and native poultry breeds alongside hydroponic fodder units.',
    eligibilityDescription: 'Individual farmers, FPOs, JLGs, and livestock entrepreneurs.',
    requiredDocs: ['Land Ownership/Lease Agreement', 'Project DPR', 'Aadhaar Card', 'Bank Sanction Letter'],
    deadline: 'NLM Portal (nlm.udyamimitra.in)',
    officialWebsiteUrl: 'https://nlm.udyamimitra.in',
    rules: { minAge: 18, maxAge: 65 },
    isPopular: true,
    iconName: 'pets'
  },
  {
    id: 'rashtriya-gokul-mission-indigenous-bovine-breed',
    title: 'Rashtriya Gokul Mission (RGM Artificial Insemination & Bovine Breeding Support)',
    code: 'RGM-BOVINE-BREEDING',
    ministry: 'Ministry of Fisheries, Animal Husbandry and Dairying',
    origin: 'central',
    category: 'Agriculture, Rural & Environment',
    subCategory: 'Animal Husbandry & Dairy',
    beneficiaries: ['Farmers', 'Rural Citizens'],
    benefitValue: 'Free High-Genetic Sex-Sorted Semen Doses + ₹5,000 Cash Incentive per High-Yielding Gir/Sahiwal Calf',
    benefitNumericMin: 5000,
    benefitNumericMax: 50000,
    description: 'Enhances milk productivity of indigenous cattle breeds (Gir, Sahiwal, Red Sindhi, Kankrej) using sex-sorted semen technology.',
    eligibilityDescription: 'Dairy farmers, MAITRI workers, and cattle rearers.',
    requiredDocs: ['INAPH Ear Tag Number', 'Aadhaar Card', 'Bank Passbook'],
    deadline: 'INAPH Bovine Portal (dahd.nic.in)',
    officialWebsiteUrl: 'https://dahd.nic.in',
    rules: { minAge: 18, maxAge: 80 },
    isPopular: true,
    iconName: 'pets'
  },
  {
    id: 'sub-mission-on-agroforestry-har-medh-par-ped',
    title: 'Sub-Mission on Agroforestry (SMAF - Har Medh Par Ped Subsidy)',
    code: 'SMAF-HAR-MEDH-PAR-PED',
    ministry: 'Ministry of Agriculture and Farmers Welfare, Govt. of India',
    origin: 'central',
    category: 'Agriculture, Rural & Environment',
    subCategory: 'Agroforestry & Tree Plantation',
    beneficiaries: ['Farmers', 'Rural Citizens'],
    benefitValue: '₹70 per Sapling Financial Incentive for Planting Timber & Fruit Trees on Farm Bunds',
    benefitNumericMin: 3500,
    benefitNumericMax: 35000,
    description: 'Encourages farmers to plant multi-purpose trees (Teak, Poplar, Malabar Neem, Sandalwood) on farm field boundaries for extra income.',
    eligibilityDescription: 'Farmers planting timber/fruit saplings along field perimeters.',
    requiredDocs: ['Land Record Copy', 'Aadhaar Card', 'Nursery Sapling Bill'],
    deadline: 'SMAF Portal (agroforestry.dac.gov.in)',
    officialWebsiteUrl: 'https://agroforestry.dac.gov.in',
    rules: { minAge: 18, maxAge: 80, requiresFarmer: true },
    isPopular: false,
    iconName: 'park'
  },
  {
    id: 'integrated-development-of-horticulture-midh-cold-storage',
    title: 'Mission for Integrated Development of Horticulture (MIDH Cold Storage & Polyhouse Grant)',
    code: 'MIDH-HORTICULTURE-GRANT',
    ministry: 'Department of Agriculture and Farmers Welfare',
    origin: 'central',
    category: 'Agriculture, Rural & Environment',
    subCategory: 'Horticulture & Cold Chain',
    beneficiaries: ['Farmers', 'Entrepreneurs'],
    benefitValue: 'Up to 50% Capital Subsidy for Polyhouses, Shade Nets, Mushroom Units & Packhouses',
    benefitNumericMin: 50000,
    benefitNumericMax: 2000000,
    description: 'Provides financial assistance for protected cultivation (polyhouses), post-harvest cold storage, and drip-irrigated fruit orchards.',
    eligibilityDescription: 'Horticulture farmers, farmer producer organizations (FPOs), and rural agri-preneurs.',
    requiredDocs: ['Land Revenue Record', 'Polyhouse Architectural Layout', 'Aadhaar Card'],
    deadline: 'MIDH Portal (midh.gov.in)',
    officialWebsiteUrl: 'https://midh.gov.in',
    rules: { minAge: 18, maxAge: 75 },
    isPopular: true,
    iconName: 'grass'
  },
  {
    id: 'mh-chhatrapati-shivaji-maharaj-shetkari-sanman-yojana',
    title: 'Maharashtra Crop Loan Waiver Scheme (Mahakarzmafi Loan Relief)',
    code: 'MH-CROP-LOAN-WAIVER',
    ministry: 'Department of Agriculture & Co-operation, Govt. of Maharashtra',
    origin: 'state',
    stateName: 'Maharashtra',
    category: 'Agriculture, Rural & Environment',
    subCategory: 'Farm Loan Waiver & Credit Relief',
    beneficiaries: ['Farmers'],
    benefitValue: '100% Direct Bank Transfer Waiver of Overdue Crop Loans up to ₹2.0 Lakh',
    benefitNumericMin: 25000,
    benefitNumericMax: 200000,
    description: 'Waives off outstanding crop loans up to ₹2 Lakh for distressed farmers in drought-affected and rainfed regions of Maharashtra.',
    eligibilityDescription: 'Farmers in Maharashtra with defaulted short-term crop loans from cooperative/commercial banks.',
    requiredDocs: ['7/12 Extract', 'Bank Loan Account Passbook', 'Aadhaar Card'],
    deadline: 'MJPSKY Mahafood Portal (mjpsky.maharashtra.gov.in)',
    officialWebsiteUrl: 'https://mjpsky.maharashtra.gov.in',
    rules: { minAge: 18, maxAge: 85, requiresFarmer: true, statesAllowed: ['Maharashtra'] },
    isPopular: true,
    iconName: 'agriculture'
  },
  {
    id: 'up-mukhya-mantri-khet-suraksha-yojana-solar-fencing',
    title: 'UP Mukhyamantri Khet Suraksha Yojana (Solar Fencing Subsidy for Farmers)',
    code: 'UP-KHET-SURAKSHA-SOLAR-FENCE',
    ministry: 'Department of Agriculture, Govt. of Uttar Pradesh',
    origin: 'state',
    stateName: 'Uttar Pradesh',
    category: 'Agriculture, Rural & Environment',
    subCategory: 'Crop Protection & Farm Security',
    beneficiaries: ['Farmers'],
    benefitValue: '60% Financial Subsidy (up to ₹1.43 Lakh per Hectare) for Low-Voltage Solar Powered Fencing',
    benefitNumericMin: 30000,
    benefitNumericMax: 143000,
    description: 'Installs non-lethal solar pulse energizer fences around crop fields to protect crops from wild animals and stray cattle.',
    eligibilityDescription: 'Small and marginal farmers in Uttar Pradesh.',
    requiredDocs: ['Khasra Khatauni Copy', 'Aadhaar Card', 'Bank Details'],
    deadline: 'UP Agriculture Portal (upagriculture.com)',
    officialWebsiteUrl: 'https://upagriculture.com',
    rules: { minAge: 18, maxAge: 80, requiresFarmer: true, statesAllowed: ['Uttar Pradesh'] },
    isPopular: true,
    iconName: 'security'
  },
  {
    id: 'rj-mukhyamantri-kisan-mitra-urja-yojana-power-subsidy',
    title: 'Rajasthan Mukhyamantri Kisan Mitra Urja Yojana (₹1,000 Free Power Monthly)',
    code: 'RJ-KISAN-MITRA-URJA',
    ministry: 'Energy Department & DISCOMs, Govt. of Rajasthan',
    origin: 'state',
    stateName: 'Rajasthan',
    category: 'Agriculture, Rural & Environment',
    subCategory: 'Agricultural Power & Utility Subsidy',
    beneficiaries: ['Farmers'],
    benefitValue: 'Direct Monthly Power Bill Subsidy of ₹1,000 (up to ₹12,000 per year) for Agricultural Electricity Meters',
    benefitNumericMin: 1000,
    benefitNumericMax: 12000,
    description: 'Provides ₹1,000 per month directly into electricity accounts of farmers using metered agricultural pumpsets.',
    eligibilityDescription: 'Farmers in Rajasthan with metered agricultural power connections.',
    requiredDocs: ['Jan Aadhaar Card', 'Electricity Connection K-Number'],
    deadline: 'Rajasthan Energy Department Portal (energy.rajasthan.gov.in)',
    officialWebsiteUrl: 'https://energy.rajasthan.gov.in',
    rules: { minAge: 18, maxAge: 85, requiresFarmer: true, statesAllowed: ['Rajasthan'] },
    isPopular: true,
    iconName: 'bolt'
  },
  {
    id: 'ka-krishi-yanthradhare-farm-machinery-custom-hiring',
    title: 'Karnataka Krishi Yanthradhare Scheme (High-Tech Farm Machinery Custom Hiring)',
    code: 'KA-KRISHI-YANTHRADHARE',
    ministry: 'Department of Agriculture, Govt. of Karnataka',
    origin: 'state',
    stateName: 'Karnataka',
    category: 'Agriculture, Rural & Environment',
    subCategory: 'Farm Mechanization & Hiring',
    beneficiaries: ['Farmers'],
    benefitValue: 'Rental Hiring of Tractors, Harvesters & Drones at 50% Below Market Commercial Rates',
    benefitNumericMin: 500,
    benefitNumericMax: 15000,
    description: 'Provides custom hiring centers (CHCs) in every hobli where small farmers can rent heavy agricultural equipment at nominal government tariffs.',
    eligibilityDescription: 'Small and marginal farmers domiciled in Karnataka.',
    requiredDocs: ['Pahani / RTC Document', 'Aadhaar Card', 'Kisaan Card'],
    deadline: 'Seva Sindhu Portal Karnataka (sevasindhuservices.karnataka.gov.in)',
    officialWebsiteUrl: 'https://raitamitra.karnataka.gov.in',
    rules: { minAge: 18, maxAge: 85, requiresFarmer: true, statesAllowed: ['Karnataka'] },
    isPopular: true,
    iconName: 'agriculture'
  },
  {
    id: 'tn-chief-ministers-dryland-development-mission',
    title: 'Tamil Nadu Chief Minister’s Dryland Development Mission (Kalaignarin All Village Integrated Agriculture)',
    code: 'TN-DRYLAND-AGRICULTURE',
    ministry: 'Agriculture and Farmers Welfare Department, Govt. of Tamil Nadu',
    origin: 'state',
    stateName: 'Tamil Nadu',
    category: 'Agriculture, Rural & Environment',
    subCategory: 'Dryland Farming & Irrigation',
    beneficiaries: ['Farmers', 'Rural Citizens'],
    benefitValue: '100% Free Well Drilling + Solar Pumpset + Free Saplings for Dryland Farmer Clusters',
    benefitNumericMin: 25000,
    benefitNumericMax: 150000,
    description: 'Transforms fallow rainfed drylands into productive agricultural zones by providing collective borewells and micro-irrigation systems.',
    eligibilityDescription: 'Dryland farmers holding land in designated rainfed village panchayats in Tamil Nadu.',
    requiredDocs: ['Chitta / Adangal Land Extracts', 'Aadhaar Card'],
    deadline: 'TNAU / Uzhavan App (tnagrisnet.tn.gov.in)',
    officialWebsiteUrl: 'https://tnagrisnet.tn.gov.in',
    rules: { minAge: 18, maxAge: 85, requiresFarmer: true, statesAllowed: ['Tamil Nadu'] },
    isPopular: true,
    iconName: 'water_drop'
  },
  {
    id: 'gj-suni-yojana-sauni-yojana-narmada-water-diversion',
    title: 'Gujarat SAUNI Yojana (Saurashtra Narmada Avtaran Irrigation Network)',
    code: 'GJ-SAUNI-YOJANA-IRRIGATION',
    ministry: 'Water Resources Department, Govt. of Gujarat',
    origin: 'state',
    stateName: 'Gujarat',
    category: 'Agriculture, Rural & Environment',
    subCategory: 'Canal & Water Diversion',
    beneficiaries: ['Farmers', 'Rural Citizens'],
    benefitValue: 'Assured Narmada Canal Water Supply for Recharging 115 Dams & 10 Lakh Acres of Farm Land',
    benefitNumericMin: 50000,
    benefitNumericMax: 500000,
    description: 'Fills 115 reservoirs across drought-prone Saurashtra region with surplus Narmada flood waters through high-pressure pipelines.',
    eligibilityDescription: 'Farmers in Saurashtra region (Rajkot, Jamnagar, Junagadh, Amreli, Bhavnagar).',
    requiredDocs: ['8-A / 7-12 Land Document', 'Aadhaar Card'],
    deadline: 'Gujarat Narmada & Water Resources Dept',
    officialWebsiteUrl: 'https://gu jarat.gov.in',
    rules: { minAge: 18, maxAge: 85, requiresFarmer: true, statesAllowed: ['Gujarat'] },
    isPopular: true,
    iconName: 'water'
  },
  {
    id: 'ts-rythu-bandhu-investment-support-scheme-agriculture',
    title: 'Telangana Rythu Bandhu Scheme (₹10,000 per Acre Crop Investment Support)',
    code: 'TS-RYTHU-BANDHU',
    ministry: 'Department of Agriculture, Govt. of Telangana',
    origin: 'state',
    stateName: 'Telangana',
    category: 'Agriculture, Rural & Environment',
    subCategory: 'Crop Financial Assistance',
    beneficiaries: ['Farmers'],
    benefitValue: 'Direct Bank Transfer of ₹10,000 per Acre per Year (₹5,000 per Kharif & Rabi season)',
    benefitNumericMin: 10000,
    benefitNumericMax: 100000,
    description: 'First direct crop investment support scheme in India providing ₹10,000 per acre annually for purchasing seeds, fertilizers, and pesticides.',
    eligibilityDescription: 'Landowning farmers in Telangana possessing Pattadar Passbooks.',
    requiredDocs: ['Pattadar Passbook Title', 'Aadhaar Card', 'Bank Account Details'],
    deadline: 'Rythu Bandhu Portal (rythubandhu.telangana.gov.in)',
    officialWebsiteUrl: 'https://rythubandhu.telangana.gov.in',
    rules: { minAge: 18, maxAge: 90, requiresFarmer: true, statesAllowed: ['Telangana'] },
    isPopular: true,
    iconName: 'payments'
  },
  {
    id: 'ap-dr-ysr-rythu-bharosa-pm-kisan-integrated-scheme',
    title: 'Andhra Pradesh YSR Rythu Bharosa (₹13,500 Annual Farmer Financial Grant)',
    code: 'AP-YSR-RYTHU-BHAROSA',
    ministry: 'Department of Agriculture, Govt. of Andhra Pradesh',
    origin: 'state',
    stateName: 'Andhra Pradesh',
    category: 'Agriculture, Rural & Environment',
    subCategory: 'Crop Financial Assistance',
    beneficiaries: ['Farmers'],
    benefitValue: 'Direct Financial Grant of ₹13,500 per Year (Including Tenant Farmers & SC/ST/BC Cultivators)',
    benefitNumericMin: 13500,
    benefitNumericMax: 13500,
    description: 'Provides ₹13,500 annual input financial assistance to landowning as well as ROFR landless tenant farmers in Andhra Pradesh.',
    eligibilityDescription: 'Landowning farmers and registered tenant farmers in Andhra Pradesh.',
    requiredDocs: ['Pattadar Passbook or CCRC Tenant Certificate', 'Aadhaar Card', 'Rice Card'],
    deadline: 'YSR Rythu Bharosa Portal (rythubharosa.ap.gov.in)',
    officialWebsiteUrl: 'https://rythubharosa.ap.gov.in',
    rules: { minAge: 18, maxAge: 85, requiresFarmer: true, statesAllowed: ['Andhra Pradesh'] },
    isPopular: true,
    iconName: 'payments'
  },
  {
    id: 'pb-paani-bachao-paisa-kamao-direct-benefit-transfer-power',
    title: 'Punjab "Paani Bachao, Paisa Kamao" Electricity & Groundwater Conservation Scheme',
    code: 'PB-PAANI-BACHAO-PAISA-KAMAO',
    ministry: 'Department of Power & Department of Agriculture, Govt. of Punjab',
    origin: 'state',
    stateName: 'Punjab',
    category: 'Agriculture, Rural & Environment',
    subCategory: 'Water & Energy Conservation',
    beneficiaries: ['Farmers'],
    benefitValue: 'Direct Cash Transfer of ₹4 per kWh for Every Unit of Electricity Saved on Agricultural Pumpsets',
    benefitNumericMin: 2000,
    benefitNumericMax: 20000,
    description: 'Incentivizes farmers with direct cash payments in their bank accounts for conserving groundwater and reducing power consumption on tube wells.',
    eligibilityDescription: 'Farmers in Punjab voluntarily installing digital electricity meters on agricultural feeders.',
    requiredDocs: ['PSPCL Tube-Well Connection Number', 'Aadhaar Card', 'Bank Account'],
    deadline: 'PSPCL Official Portal (pspcl.in)',
    officialWebsiteUrl: 'https://pspcl.in',
    rules: { minAge: 18, maxAge: 85, requiresFarmer: true, statesAllowed: ['Punjab'] },
    isPopular: true,
    iconName: 'savings'
  },
  {
    id: 'kl-subhiksha-keralam-integrated-food-security-mission',
    title: 'Kerala Subhiksha Keralam Integrated Fallow Land Farming Mission',
    code: 'KL-SUBHIKSHA-KERALAM',
    ministry: 'Department of Agriculture Development & Farmers’ Welfare, Govt. of Kerala',
    origin: 'state',
    stateName: 'Kerala',
    category: 'Agriculture, Rural & Environment',
    subCategory: 'Food Security & Land Reclamation',
    beneficiaries: ['Farmers', 'Rural Citizens', 'Women'],
    benefitValue: '₹40,000 per Hectare Financial Incentive for Converting Uncultivated Fallow Land into Paddy & Vegetable Fields',
    benefitNumericMin: 10000,
    benefitNumericMax: 40000,
    description: 'Reclaims uncultivated fallow land for paddy, tuber, and banana farming through Kudumbashree women collectives.',
    eligibilityDescription: 'Farmers, Kudumbashree SHGs, and youth collectives cultivating fallow land in Kerala.',
    requiredDocs: ['AIMS Portal Registration', 'Kudumbashree Membership Certificate', 'Land Lease Agreement'],
    deadline: 'AIMS Portal Kerala (aims.kerala.gov.in)',
    officialWebsiteUrl: 'https://aims.kerala.gov.in',
    rules: { minAge: 18, maxAge: 75, statesAllowed: ['Kerala'] },
    isPopular: true,
    iconName: 'agriculture'
  },
  {
    id: 'as-chief-ministers-samagra-gramya-unnayan-yojana-tractor',
    title: 'Assam CMSGUY 70% Tractor & Mechanization Subsidy Scheme',
    code: 'AS-CMSGUY-TRACTOR-SUBSIDY',
    ministry: 'Mega Mission Society - CMSGUY, Govt. of Assam',
    origin: 'state',
    stateName: 'Assam',
    category: 'Agriculture, Rural & Environment',
    subCategory: 'Farm Mechanization',
    beneficiaries: ['Farmers', 'Rural Citizens'],
    benefitValue: '70% Direct Capital Subsidy (up to ₹5.5 Lakh) for Purchasing Heavy Duty Farm Tractors in Every Village',
    benefitNumericMin: 200000,
    benefitNumericMax: 550000,
    description: 'Provides one 35-hp tractor unit to a selected group of farmers in every revenue village of Assam to double farm productivity.',
    eligibilityDescription: 'Registered farmer groups/JLGs consisting of 8 to 10 active farmers in Assam.',
    requiredDocs: ['Farmer Group Resolution', 'Aadhaar Cards of Group Members', 'Bank Account Passbook'],
    deadline: 'Assam CMSGUY Portal (mincom.assam.gov.in)',
    officialWebsiteUrl: 'https://mincom.assam.gov.in',
    rules: { minAge: 18, maxAge: 65, requiresFarmer: true, statesAllowed: ['Assam'] },
    isPopular: true,
    iconName: 'agriculture'
  },
  {
    id: 'wb-krishak-bandhu-scheme-death-benefit-and-input-grant',
    title: 'West Bengal Krishak Bandhu Scheme (₹10,000 Annual Grant + ₹2 Lakh Life Insurance)',
    code: 'WB-KRISHAK-BANDHU',
    ministry: 'Department of Agriculture, Govt. of West Bengal',
    origin: 'state',
    stateName: 'West Bengal',
    category: 'Agriculture, Rural & Environment',
    subCategory: 'Crop Assistance & Social Security',
    beneficiaries: ['Farmers'],
    benefitValue: 'Direct Financial Grant up to ₹10,000 per Year + ₹2.0 Lakh Life Insurance Cover upon Farmer Death',
    benefitNumericMin: 4000,
    benefitNumericMax: 200000,
    description: 'Provides dual benefit of bi-annual crop assistance and 100% state-funded ₹2 Lakh financial grant to nominee families on death of a farmer aged 18 to 60.',
    eligibilityDescription: 'All landowning and recorded bargadar (sharecropper) farmers in West Bengal.',
    requiredDocs: ['RoR Khatian Land Extract', 'Voter ID Card', 'Aadhaar Card', 'Bank Passbook'],
    deadline: 'Krishak Bandhu Portal (krishakbandhu.wb.gov.in)',
    officialWebsiteUrl: 'https://krishakbandhu.wb.gov.in',
    rules: { minAge: 18, maxAge: 60, requiresFarmer: true, statesAllowed: ['West Bengal'] },
    isPopular: true,
    iconName: 'health_and_safety'
  },
  {
    id: 'od-kalia-scheme-krushak-assistance-for-livelihood',
    title: 'Odisha KALIA Scheme (Krushak Assistance for Livelihood and Income Augmentation)',
    code: 'OD-KALIA-SCHEME',
    ministry: 'Department of Agriculture & Farmers’ Empowerment, Govt. of Odisha',
    origin: 'state',
    stateName: 'Odisha',
    category: 'Agriculture, Rural & Environment',
    subCategory: 'Crop & Livelihood Financial Support',
    beneficiaries: ['Farmers', 'Workers', 'Rural Citizens'],
    benefitValue: 'Financial Support of ₹10,000 per Year for Cultivators + ₹12,500 Livelihood Grant for Landless Agricultural Laborers',
    benefitNumericMin: 10000,
    benefitNumericMax: 22500,
    description: 'Covers small farmers, sharecroppers, and landless agricultural households with cash transfers for farming inputs and goat/poultry rearing.',
    eligibilityDescription: 'Small, marginal, landless agricultural workers and sharecroppers in Odisha.',
    requiredDocs: ['Aadhaar Card', 'BPL Ration Card', 'Bank Passbook'],
    deadline: 'KALIA Portal Odisha (kalia.odisha.gov.in)',
    officialWebsiteUrl: 'https://kalia.odisha.gov.in',
    rules: { minAge: 18, maxAge: 80, statesAllowed: ['Odisha'] },
    isPopular: true,
    iconName: 'payments'
  },
  {
    id: 'br-mukhyamantri-tivr-beej-vistar-yojana-seed-distribution',
    title: 'Bihar Mukhyamantri Teevr Beej Vistar Yojana (90% Subsidized Seed Door-Delivery)',
    code: 'BR-TEEVR-BEEJ-VISTAR',
    ministry: 'Department of Agriculture, Govt. of Bihar',
    origin: 'state',
    stateName: 'Bihar',
    category: 'Agriculture, Rural & Environment',
    subCategory: 'Seed Distribution & Crop Yield',
    beneficiaries: ['Farmers'],
    benefitValue: '90% Subsidy on High-Yielding Paddy, Wheat & Maize Seeds Delivered Directly to Village Level',
    benefitNumericMin: 1000,
    benefitNumericMax: 10000,
    description: 'Provides doorstep delivery of certified foundation seeds of paddy, wheat, and pulses at 90% government subsidy in every Panchayat.',
    eligibilityDescription: 'Farmers in Bihar registered on DBT Agriculture Portal.',
    requiredDocs: ['DBT Registration Number', 'Aadhaar Card', 'Land LPC'],
    deadline: 'DBT Agriculture Bihar Portal (dbtagriculture.bihar.gov.in)',
    officialWebsiteUrl: 'https://dbtagriculture.bihar.gov.in',
    rules: { minAge: 18, maxAge: 80, requiresFarmer: true, statesAllowed: ['Bihar'] },
    isPopular: true,
    iconName: 'grain'
  },
  {
    id: 'cg-godhan-nyay-yojana-cow-dung-vermicompost',
    title: 'Chhattisgarh Godhan Nyay Yojana (Cow Dung Purchase at ₹2/kg & Organic Compost)',
    code: 'CG-GODHAN-NYAY-YOJANA',
    ministry: 'Department of Agriculture and Biotechnology, Govt. of Chhattisgarh',
    origin: 'state',
    stateName: 'Chhattisgarh',
    category: 'Agriculture, Rural & Environment',
    subCategory: 'Organic Fertilizer & Livestock Income',
    beneficiaries: ['Farmers', 'Rural Citizens', 'Women'],
    benefitValue: 'Government Procurement of Cow Dung at ₹2.00 per kg directly at Gauthans (Cattle Care Centres)',
    benefitNumericMin: 2000,
    benefitNumericMax: 30000,
    description: 'Procures cow dung from cattle rearers and converts it into organic vermicompost through Women Self-Help Groups (SHGs).',
    eligibilityDescription: 'Cattle rearers, farmers, and women SHG members in Chhattisgarh.',
    requiredDocs: ['Gauthan Card', 'Aadhaar Card', 'Bank Account Details'],
    deadline: 'Godhan Nyay Portal Chhattisgarh',
    officialWebsiteUrl: 'https://agriportal.cg.nic.in',
    rules: { minAge: 18, maxAge: 80, statesAllowed: ['Chhattisgarh'] },
    isPopular: true,
    iconName: 'recycling'
  },
  {
    id: 'jh-mukhyamantri-pashudhan-vikas-yojana-dairy-goat',
    title: 'Jharkhand Mukhyamantri Pashudhan Vikas Yojana (90% Dairy & Poultry Subsidy)',
    code: 'JH-PASHUDHAN-VIKAS-YOJANA',
    ministry: 'Department of Agriculture, Animal Husbandry & Co-operative, Govt. of Jharkhand',
    origin: 'state',
    stateName: 'Jharkhand',
    category: 'Agriculture, Rural & Environment',
    subCategory: 'Livestock & Animal Husbandry',
    beneficiaries: ['Farmers', 'Rural Citizens', 'Women'],
    benefitValue: '90% Subsidy on High-Yielding Crossbred Milch Cows, Goats, Duckling & Piglets',
    benefitNumericMin: 15000,
    benefitNumericMax: 150000,
    description: 'Provides 90% capital financial subsidy to rural women, widowers, and SC/ST families for purchasing milch cattle and poultry units.',
    eligibilityDescription: 'Rural families, widows, and SC/ST farmers domiciled in Jharkhand.',
    requiredDocs: ['Jharkhand Caste / Domicile Certificate', 'Aadhaar Card', 'Bank Account Details'],
    deadline: 'Jharkhand Agriculture Portal (jharkhand.gov.in)',
    officialWebsiteUrl: 'https://jharkhand.gov.in',
    rules: { minAge: 18, maxAge: 70, statesAllowed: ['Jharkhand'] },
    isPopular: true,
    iconName: 'pets'
  },
  {
    id: 'uk-mukhyamantri-ghasiyari-kalyan-yojana-silage-fodder',
    title: 'Uttarakhand Mukhyamantri Ghasiyari Kalyan Yojana (Subsidized Nutritious Fodder Blocks)',
    code: 'UK-GHASIYARI-KALYAN-YOJANA',
    ministry: 'Department of Animal Husbandry, Govt. of Uttarakhand',
    origin: 'state',
    stateName: 'Uttarakhand',
    category: 'Agriculture, Rural & Environment',
    subCategory: 'Animal Husbandry & Fodder Security',
    beneficiaries: ['Women', 'Farmers', 'Rural Citizens'],
    benefitValue: '30% Subsidized Nutritious Maize Silage & Fodder Blocks (₹2/kg) Delivered to Mountain Villages',
    benefitNumericMin: 1000,
    benefitNumericMax: 10000,
    description: 'Relieves hill women from arduous trek in dense forests for collecting cattle green fodder by delivering vacuum-packed nutritious silage at doorstep.',
    eligibilityDescription: 'Livestock rearers and rural farm women in hill districts of Uttarakhand.',
    requiredDocs: ['Cooperative Dairy Membership', 'Aadhaar Card'],
    deadline: 'Uttarakhand Cooperative Portal',
    officialWebsiteUrl: 'https://ahd.uk.gov.in',
    rules: { minAge: 18, maxAge: 75, statesAllowed: ['Uttarakhand'] },
    isPopular: true,
    iconName: 'pets'
  },
  {
    id: 'hr-mera-pani-meri-virasat-yojana-crop-diversification',
    title: 'Haryana "Mera Pani - Meri Virasat" Crop Diversification Financial Incentive',
    code: 'HR-MERA-PANI-MERI-VIRASAT',
    ministry: 'Department of Agriculture and Farmers Welfare, Govt. of Haryana',
    origin: 'state',
    stateName: 'Haryana',
    category: 'Agriculture, Rural & Environment',
    subCategory: 'Water Conservation & Crop Diversification',
    beneficiaries: ['Farmers'],
    benefitValue: 'Direct Financial Incentive of ₹7,000 per Acre for Replacing Water-Intensive Paddy with Maize, Cotton, Pulses or Vegetables',
    benefitNumericMin: 7000,
    benefitNumericMax: 70000,
    description: 'Promotes groundwater conservation in dark zone blocks by encouraging paddy farmers to switch to alternate dry crops.',
    eligibilityDescription: 'Farmers in Haryana replacing paddy cultivation with alternative crops.',
    requiredDocs: ['Meri Fasal Mera Byora (MFMB) Portal ID', 'Aadhaar Card', 'Bank Passbook'],
    deadline: 'MFMB Haryana Portal (fasal.haryana.gov.in)',
    officialWebsiteUrl: 'https://fasal.haryana.gov.in',
    rules: { minAge: 18, maxAge: 85, requiresFarmer: true, statesAllowed: ['Haryana'] },
    isPopular: true,
    iconName: 'water_drop'
  },
  {
    id: 'hp-mukhya-mantri-khet-sanrakshan-yojana-fencing',
    title: 'Himachal Pradesh Mukhya Mantri Khet Sanrakshan Yojana (80% Solar Fence Subsidy)',
    code: 'HP-KHET-SANRAKSHAN-YOJANA',
    ministry: 'Department of Agriculture, Govt. of Himachal Pradesh',
    origin: 'state',
    stateName: 'Himachal Pradesh',
    category: 'Agriculture, Rural & Environment',
    subCategory: 'Crop Protection & Solar Security',
    beneficiaries: ['Farmers'],
    benefitValue: '80% Capital Subsidy for Individual Solar Fencing (85% for Group Farmers) against Wild Animals',
    benefitNumericMin: 40000,
    benefitNumericMax: 200000,
    description: 'Protect agricultural crops in hilly terrains from monkeys, wild boars, and stray animals using high-grade solar composite fencing.',
    eligibilityDescription: 'Practicing farmers and farmer clusters in Himachal Pradesh.',
    requiredDocs: ['Bonafide Himachali Certificate', 'Khasra Land Extraction', 'Aadhaar Card'],
    deadline: 'HP Agriculture Portal (hpagrisnet.gov.in)',
    officialWebsiteUrl: 'https://hpagrisnet.gov.in',
    rules: { minAge: 18, maxAge: 80, requiresFarmer: true, statesAllowed: ['Himachal Pradesh'] },
    isPopular: true,
    iconName: 'shield'
  },
  {
    id: 'mp-mukhyamantri-krishi-yantra-yojana-subsidy-dbt',
    title: 'MP Mukhyamantri Krishi Yantra Yojana (Subsidized Seed Drills & Rotavators)',
    code: 'MP-KRISHI-YANTRA-YOJANA',
    ministry: 'Directorate of Agricultural Engineering, Govt. of Madhya Pradesh',
    origin: 'state',
    stateName: 'Madhya Pradesh',
    category: 'Agriculture, Rural & Environment',
    subCategory: 'Farm Machinery & Implements',
    beneficiaries: ['Farmers'],
    benefitValue: '50% Financial Capital Subsidy on Rotavators, Seed Drills, Laser Land Levelers & Power Tillers',
    benefitNumericMin: 15000,
    benefitNumericMax: 150000,
    description: 'Provides online lottery-based capital subsidies on modern tractor-driven farm implements for small/marginal farmers.',
    eligibilityDescription: 'Farmers in Madhya Pradesh registered on e-Krishi Yantra Anudan Portal.',
    requiredDocs: ['Land Khasra B1 Copy', 'Aadhaar Card', 'Caste Certificate (if SC/ST)'],
    deadline: 'MP e-Krishi Yantra Portal (dwt.mpeproc.gov.in)',
    officialWebsiteUrl: 'https://dwt.mpeproc.gov.in',
    rules: { minAge: 18, maxAge: 80, requiresFarmer: true, statesAllowed: ['Madhya Pradesh'] },
    isPopular: true,
    iconName: 'agriculture'
  },
  {
    id: 'goa-shetkari-adhaar-yojana-crop-loss-compensation',
    title: 'Goa Shetkari Adhaar Yojana (Top-Up Price Support for Arecanut & Coconut)',
    code: 'GA-SHETKARI-ADHAAR-YOJANA',
    ministry: 'Directorate of Agriculture, Govt. of Goa',
    origin: 'state',
    stateName: 'Goa',
    category: 'Agriculture, Rural & Environment',
    subCategory: 'Price Assurance & Plantation',
    beneficiaries: ['Farmers'],
    benefitValue: 'Assured Price Support Top-Up Grant per kg for Coconut, Paddy, Cashew & Arecanut Harvests',
    benefitNumericMin: 5000,
    benefitNumericMax: 50000,
    description: 'Compensates horticultural farmers in Goa when market prices drop below prescribed economic cost thresholds.',
    eligibilityDescription: 'Goan farmers holding Krishi Card issued by Directorate of Agriculture.',
    requiredDocs: ['Goa Krishi Card', 'Aadhaar Card', 'Sale Receipts'],
    deadline: 'Goa Agriculture Portal (agri.goa.gov.in)',
    officialWebsiteUrl: 'https://agri.goa.gov.in',
    rules: { minAge: 18, maxAge: 80, requiresFarmer: true, statesAllowed: ['Goa'] },
    isPopular: false,
    iconName: 'eco'
  },
  {
    id: 'tr-chief-ministers-rubber-mission-plantation-grant',
    title: 'Tripura Chief Minister’s Natural Rubber Plantation Expansion Mission',
    code: 'TR-RUBBER-MISSION-GRANT',
    ministry: 'Department of Agriculture and Farmers Welfare, Govt. of Tripura',
    origin: 'state',
    stateName: 'Tripura',
    category: 'Agriculture, Rural & Environment',
    subCategory: 'Plantation Crops & Tribal Income',
    beneficiaries: ['Farmers', 'Rural Citizens'],
    benefitValue: 'Capital Subsidy of ₹50,000 per Hectare for High-Yielding Rubber Budded Plants & Smoke Houses',
    benefitNumericMin: 25000,
    benefitNumericMax: 100000,
    description: 'Expands natural rubber plantations across tribal jhumia families to provide permanent sustainable livelihood in Tripura.',
    eligibilityDescription: 'Tribal and small farmers in Tripura with suitable uncultivated hilly land.',
    requiredDocs: ['RoR Land Allotment Order', 'ST Certificate', 'Aadhaar Card'],
    deadline: 'Tripura Agriculture Portal (agri.tripura.gov.in)',
    officialWebsiteUrl: 'https://agri.tripura.gov.in',
    rules: { minAge: 18, maxAge: 70, requiresFarmer: true, statesAllowed: ['Tripura'] },
    isPopular: false,
    iconName: 'park'
  },
  {
    id: 'sk-sikkim-garib-thekedar-and-organic-farming-grant',
    title: 'Sikkim Organic Farming Financial Incentive & Bio-Input Subsidy',
    code: 'SK-ORGANIC-FARMING-SUBSIDY',
    ministry: 'Department of Agriculture, Govt. of Sikkim',
    origin: 'state',
    stateName: 'Sikkim',
    category: 'Agriculture, Rural & Environment',
    subCategory: '100% Organic Farming Support',
    beneficiaries: ['Farmers', 'Rural Citizens'],
    benefitValue: '₹10,000 per Hectare Direct Financial Grant for Bio-Compost, Vermicompost & Neem Oil Inputs',
    benefitNumericMin: 10000,
    benefitNumericMax: 50000,
    description: 'Sustains Sikkim’s 100% organic state status by subsidizing bio-fertilizers, organic seeds, and bio-pesticide kits for mountain farmers.',
    eligibilityDescription: 'Sikkim Subject / Certificate of Identification holder farmers practicing certified organic farming.',
    requiredDocs: ['Sikkim COI / Subject Certificate', 'Organic Farmer Card', 'Bank Passbook'],
    deadline: 'Sikkim Organic Mission Portal',
    officialWebsiteUrl: 'https://sikkim.gov.in',
    rules: { minAge: 18, maxAge: 80, requiresFarmer: true, statesAllowed: ['Sikkim'] },
    isPopular: true,
    iconName: 'eco'
  },
  {
    id: 'py-puducherry-paddy-bonus-and-crop-subsidy',
    title: 'Puducherry Per-Hectare Paddy Cultivation Bonus & Crop Subsidy',
    code: 'PY-PADDY-BONUS-SCHEME',
    ministry: 'Department of Agriculture and Farmers Welfare, Govt. of Puducherry',
    origin: 'state',
    stateName: 'Puducherry',
    category: 'Agriculture, Rural & Environment',
    subCategory: 'Crop Financial Assistance',
    beneficiaries: ['Farmers'],
    benefitValue: 'Cash Bonus Grant of ₹10,000 per Hectare directly deposited for Paddy Cultivators',
    benefitNumericMin: 5000,
    benefitNumericMax: 20000,
    description: 'Provides direct financial cash bonus to paddy farmers in Puducherry, Karaikal, Yanam, and Mahe regions.',
    eligibilityDescription: 'Farmers in UT of Puducherry cultivating paddy crops.',
    requiredDocs: ['Puducherry Chitta Extract', 'Aadhaar Card', 'Bank Passbook'],
    deadline: 'Puducherry Agri Portal (agri.py.gov.in)',
    officialWebsiteUrl: 'https://agri.py.gov.in',
    rules: { minAge: 18, maxAge: 80, requiresFarmer: true, statesAllowed: ['Puducherry'] },
    isPopular: false,
    iconName: 'payments'
  },

  // ==========================================
  // BANKING, FINANCIAL SERVICES & INSURANCE (49 SCHEMES)
  // ==========================================
  {
    id: 'pm-jan-dhan-yojana-overdraft-and-accidental-cover',
    title: 'Pradhan Mantri Jan Dhan Yojana (PMJDY ₹10,000 Overdraft & ₹2 Lakh Insurance)',
    code: 'PMJDY-OVERDRAFT-INSURANCE',
    ministry: 'Department of Financial Services, Ministry of Finance, Govt. of India',
    origin: 'central',
    category: 'Banking, Financial Services & Insurance',
    subCategory: 'Financial Inclusion & Micro Banking',
    beneficiaries: ['General Citizen', 'Workers', 'Women', 'Rural Citizens'],
    benefitValue: 'Zero-Balance Savings Account + Free RuPay Debit Card with ₹2 Lakh Accidental Insurance + ₹10,000 Overdraft Facility',
    benefitNumericMin: 10000,
    benefitNumericMax: 200000,
    description: 'National mission for financial inclusion ensuring universal access to banking accounts, credit, remittance, and pension.',
    eligibilityDescription: 'Any Indian citizen aged 10 and above without a formal bank account.',
    requiredDocs: ['Aadhaar Card or Voter ID / Driving License'],
    deadline: 'PMJDY Portal (pmjdy.gov.in)',
    officialWebsiteUrl: 'https://pmjdy.gov.in',
    rules: { minAge: 10, maxAge: 75 },
    isPopular: true,
    iconName: 'account_balance'
  },
  {
    id: 'pm-suraksha-bima-yojana-accidental-death-disability',
    title: 'Pradhan Mantri Suraksha Bima Yojana (PMSBY ₹2 Lakh Accidental Death Insurance for ₹20/yr)',
    code: 'PMSBY-ACCIDENTAL-INSURANCE',
    ministry: 'Department of Financial Services, Ministry of Finance',
    origin: 'central',
    category: 'Banking, Financial Services & Insurance',
    subCategory: 'Accidental Insurance & Social Security',
    beneficiaries: ['General Citizen', 'Workers', 'Farmers'],
    benefitValue: '₹2 Lakh Accidental Death & Permanent Total Disability Insurance Cover for ₹20 Annual Premium',
    benefitNumericMin: 200000,
    benefitNumericMax: 200000,
    description: 'Provides affordable accidental death and disability insurance cover with auto-debit facility from savings bank account.',
    eligibilityDescription: 'Indian citizens aged 18 to 70 with an active savings bank account.',
    requiredDocs: ['Savings Bank Account Number', 'Aadhaar Card', 'Nominee Details'],
    deadline: 'Financial Services Portal (jansuraksha.gov.in)',
    officialWebsiteUrl: 'https://jansuraksha.gov.in',
    rules: { minAge: 18, maxAge: 70 },
    isPopular: true,
    iconName: 'health_and_safety'
  },
  {
    id: 'pm-jeevan-jyoti-bima-yojana-life-insurance-cover',
    title: 'Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY ₹2 Lakh Life Insurance for ₹436/yr)',
    code: 'PMJJBY-LIFE-INSURANCE',
    ministry: 'Department of Financial Services, Ministry of Finance',
    origin: 'central',
    category: 'Banking, Financial Services & Insurance',
    subCategory: 'Term Life Insurance',
    beneficiaries: ['General Citizen', 'Workers', 'Farmers'],
    benefitValue: '₹2 Lakh Term Life Insurance Cover upon Death due to Any Cause for ₹436 Annual Premium',
    benefitNumericMin: 200000,
    benefitNumericMax: 200000,
    description: 'Government-backed renewable term life insurance offering financial protection to families upon untimely death of the breadwinner.',
    eligibilityDescription: 'Indian citizens aged 18 to 50 with a bank/post office account.',
    requiredDocs: ['Bank Account Number', 'Aadhaar Card', 'Nominee Relationship Details'],
    deadline: 'Jan Suraksha Portal (jansuraksha.gov.in)',
    officialWebsiteUrl: 'https://jansuraksha.gov.in',
    rules: { minAge: 18, maxAge: 50 },
    isPopular: true,
    iconName: 'favorite'
  },
  {
    id: 'atal-pension-yojana-guaranteed-monthly-pension',
    title: 'Atal Pension Yojana (APY Guaranteed ₹1,000 to ₹5,000 Monthly Pension)',
    code: 'APY-GUARANTEED-PENSION',
    ministry: 'Pension Fund Regulatory and Development Authority (PFRDA) / Ministry of Finance',
    origin: 'central',
    category: 'Banking, Financial Services & Insurance',
    subCategory: 'Pension & Old Age Security',
    beneficiaries: ['Workers', 'General Citizen', 'Farmers', 'Rural Citizens'],
    benefitValue: 'Guaranteed Lifetime Monthly Pension of ₹1,000, ₹2,000, ₹3,000, ₹4,000 or ₹5,000 from Age 60',
    benefitNumericMin: 1000,
    benefitNumericMax: 5000,
    description: 'Unorganized sector pension scheme with government co-contribution ensuring lifelong monthly pension and return of pension corpus to nominee.',
    eligibilityDescription: 'Unorganized workers aged 18 to 40 who are non-income taxpayers.',
    requiredDocs: ['Aadhaar Card', 'Savings Bank Account Number', 'Mobile Number'],
    deadline: 'PFRDA / NSDL APY Portal (pfrda.org.in)',
    officialWebsiteUrl: 'https://pfrda.org.in',
    rules: { minAge: 18, maxAge: 40 },
    isPopular: true,
    iconName: 'savings'
  },
  {
    id: 'mahila-samman-savings-certificate-mssc-post-office',
    title: 'Mahila Samman Savings Certificate (MSSC 7.5% Fixed Interest Post Office Deposit)',
    code: 'MSSC-POST-OFFICE-SAVINGS',
    ministry: 'Department of Posts / Ministry of Finance, Govt. of India',
    origin: 'central',
    category: 'Banking, Financial Services & Insurance',
    subCategory: 'Post Office Small Savings & Women Finance',
    beneficiaries: ['Women', 'Children'],
    benefitValue: 'High 7.5% Fixed Annual Interest Rate + Partial Withdrawal Facility for Deposits up to ₹2.0 Lakh',
    benefitNumericMin: 1000,
    benefitNumericMax: 200000,
    description: 'Special 2-year deposit scheme for women and girl children offering government-backed 7.5% guaranteed compounding interest.',
    eligibilityDescription: 'Women citizens or minor girls through natural guardian.',
    requiredDocs: ['Aadhaar Card', 'PAN Card', 'Post Office Account Opening Form'],
    deadline: 'India Post Official Portal (indiapost.gov.in)',
    officialWebsiteUrl: 'https://indiapost.gov.in',
    rules: { minAge: 0, maxAge: 100, genderConstraint: 'Female' },
    isPopular: true,
    iconName: 'savings'
  },
  {
    id: 'sukanya-samriddhi-yojana-ssy-girl-child-savings',
    title: 'Sukanya Samriddhi Yojana (SSY 8.2% Tax-Free Girl Child Higher Education Deposit)',
    code: 'SSY-GIRL-CHILD-SAVINGS',
    ministry: 'Ministry of Finance, Govt. of India',
    origin: 'central',
    category: 'Banking, Financial Services & Insurance',
    subCategory: 'Small Savings & Child Welfare',
    beneficiaries: ['Children', 'Women'],
    benefitValue: '8.2% Compound Interest + Triple Tax Exemption (EEE Status under Section 80C) for Girl Child',
    benefitNumericMin: 250,
    benefitNumericMax: 150000,
    description: 'Government small savings scheme created for building higher education and marriage funds for girl children.',
    eligibilityDescription: 'Parents/guardians of girl children below 10 years of age (max 2 girls per family).',
    requiredDocs: ['Girl Child Birth Certificate', 'Guardian Aadhaar Card', 'PAN Card'],
    deadline: 'India Post / Authorized Commercial Banks',
    officialWebsiteUrl: 'https://indiapost.gov.in',
    rules: { minAge: 0, maxAge: 10, genderConstraint: 'Female' },
    isPopular: true,
    iconName: 'child_care'
  },
  {
    id: 'pm-street-vendors-atmanirbhar-nidhi-pm-svanidhi-loan',
    title: 'PM SVANidhi (Micro Credit Scheme for Street Vendors with 7% Interest Subsidy)',
    code: 'PM-SVANIDHI-MICRO-CREDIT',
    ministry: 'Ministry of Housing and Urban Affairs (MoHUA)',
    origin: 'central',
    category: 'Banking, Financial Services & Insurance',
    subCategory: 'Micro Credit & Digital Cashbacks',
    beneficiaries: ['Workers', 'Entrepreneurs', 'General Citizen'],
    benefitValue: 'Collateral-Free Micro Loans of ₹10,000, ₹20,000 & ₹50,000 + 7% Interest Subsidy & Digital Cashback',
    benefitNumericMin: 10000,
    benefitNumericMax: 50000,
    description: 'Provides working capital loans to street vendors to restart business post-lockdown, offering cashback incentives on digital UPI transactions.',
    eligibilityDescription: 'Street vendors and hawkers possessing Vending Certificate / ID Card.',
    requiredDocs: ['Certificate of Vending (CoV)', 'Aadhaar Card', 'Bank Account Details'],
    deadline: 'PM SVANidhi Official Portal (pmsvanidhi.mohua.gov.in)',
    officialWebsiteUrl: 'https://pmsvanidhi.mohua.gov.in',
    rules: { minAge: 18, maxAge: 65 },
    isPopular: true,
    iconName: 'store'
  },
  {
    id: 'kisan-credit-card-kcc-3-percent-interest-subvention',
    title: 'Kisan Credit Card (KCC 4% Effective Interest Rate & Concessional Credit)',
    code: 'KCC-CONCESSIONAL-CREDIT',
    ministry: 'Department of Agriculture and Farmers Welfare / RBI / NABARD',
    origin: 'central',
    category: 'Banking, Financial Services & Insurance',
    subCategory: 'Agricultural Credit & Crop Insurance',
    beneficiaries: ['Farmers', 'Workers'],
    benefitValue: 'Collateral-Free Loans up to ₹1.6 Lakh (Total Limit ₹3 Lakh) at Effective 4% Reduced Interest Rate',
    benefitNumericMin: 10000,
    benefitNumericMax: 300000,
    description: 'Offers revolving crop loan credit facility to farmers, dairy owners, and fishers with 3% prompt repayment interest subvention.',
    eligibilityDescription: 'Farmers, tenant farmers, sharecroppers, and animal husbandry rearers.',
    requiredDocs: ['Land Record Extract', 'Aadhaar Card', 'KCC Application Form'],
    deadline: 'PM-KISAN KCC Portal / All Commercial Banks',
    officialWebsiteUrl: 'https://pmkisan.gov.in',
    rules: { minAge: 18, maxAge: 75, requiresFarmer: true },
    isPopular: true,
    iconName: 'credit_card'
  },
  {
    id: 'stand-up-india-scheme-sc-st-women-bank-loan',
    title: 'Stand-Up India Scheme (₹10 Lakh to ₹1 Crore Bank Loans for SC/ST & Women)',
    code: 'STAND-UP-INDIA-LOAN',
    ministry: 'Department of Financial Services, Ministry of Finance',
    origin: 'central',
    category: 'Banking, Financial Services & Insurance',
    subCategory: 'Commercial Loans & Social Entrepreneurship',
    beneficiaries: ['Women', 'Entrepreneurs', 'General Citizen'],
    benefitValue: 'Bank Greenfield Project Loans between ₹10 Lakh and ₹1 Crore + Credit Guarantee Scheme Cover',
    benefitNumericMin: 1000000,
    benefitNumericMax: 10000000,
    description: 'Facilitates bank loans for setting up greenfield manufacturing, service, or trading enterprises by SC, ST, or women entrepreneurs.',
    eligibilityDescription: 'SC/ST and women entrepreneurs establishing new commercial units.',
    requiredDocs: ['Caste Certificate (if SC/ST)', 'Project DPR', 'Aadhaar Card', 'PAN Card'],
    deadline: 'Stand-Up Mitra Portal (standupmitra.in)',
    officialWebsiteUrl: 'https://standupmitra.in',
    rules: { minAge: 18, maxAge: 65 },
    isPopular: true,
    iconName: 'account_balance_wallet'
  },
  {
    id: 'pradhan-mantri-mudra-yojana-shishu-kishor-tarun',
    title: 'Pradhan Mantri MUDRA Yojana (Collateral-Free Business Loans up to ₹20 Lakh)',
    code: 'PMMY-MUDRA-LOAN',
    ministry: 'Department of Financial Services, Ministry of Finance',
    origin: 'central',
    category: 'Banking, Financial Services & Insurance',
    subCategory: 'Micro & Small Business Loans',
    beneficiaries: ['Entrepreneurs', 'Workers', 'Women', 'General Citizen'],
    benefitValue: 'Collateral-Free Bank Loans under Shishu (up to ₹50k), Kishor (up to ₹5 Lakh) & Tarun Plus (up to ₹20 Lakh)',
    benefitNumericMin: 50000,
    benefitNumericMax: 2000000,
    description: 'Provides non-corporate, non-farm micro enterprise loans to shopkeepers, artisans, fruit vendors, and small industrialists.',
    eligibilityDescription: 'Small business owners, micro-entrepreneurs, and self-employed individuals.',
    requiredDocs: ['Business Proof', 'Aadhaar Card', 'PAN Card', 'Bank Passbook'],
    deadline: 'Udyami Mitra MUDRA Portal (mudra.org.in)',
    officialWebsiteUrl: 'https://mudra.org.in',
    rules: { minAge: 18, maxAge: 65 },
    isPopular: true,
    iconName: 'payments'
  },
  {
    id: 'senior-citizens-savings-scheme-scss-post-office-8-2-percent',
    title: 'Senior Citizens Savings Scheme (SCSS 8.2% Quarterly Guaranteed Pension)',
    code: 'SCSS-SENIOR-SAVINGS',
    ministry: 'Ministry of Finance / Department of Posts, Govt. of India',
    origin: 'central',
    category: 'Banking, Financial Services & Insurance',
    subCategory: 'Senior Citizen Investment & Regular Income',
    beneficiaries: ['Senior Citizens'],
    benefitValue: 'Guaranteed 8.2% Annual Interest Paid Quarterly on Deposits up to ₹30 Lakh + Section 80C Tax Savings',
    benefitNumericMin: 10000,
    benefitNumericMax: 3000000,
    description: 'Safe, high-yield government security deposit scheme providing regular quarterly interest payout to retired senior citizens.',
    eligibilityDescription: 'Retired individuals aged 60 and above (55+ for superannuated defense employees).',
    requiredDocs: ['Age Proof (Aadhaar / Passport)', 'Retirement Order Copy', 'PAN Card'],
    deadline: 'Post Office / Public & Private Sector Banks',
    officialWebsiteUrl: 'https://indiapost.gov.in',
    rules: { minAge: 60, maxAge: 100, requiresSeniorCitizen: true },
    isPopular: true,
    iconName: 'elderly'
  },
  {
    id: 'public-provident-fund-ppf-tax-free-savings',
    title: 'Public Provident Fund (PPF 7.1% Compound Interest EEE Tax-Free Account)',
    code: 'PPF-TAX-FREE-SAVINGS',
    ministry: 'Department of Economic Affairs, Ministry of Finance',
    origin: 'central',
    category: 'Banking, Financial Services & Insurance',
    subCategory: 'Long-Term Savings & Tax Exemption',
    beneficiaries: ['General Citizen', 'Workers', 'Senior Citizens'],
    benefitValue: '7.1% Sovereign Guaranteed Interest + Complete Tax Exemption under EEE Category',
    benefitNumericMin: 500,
    benefitNumericMax: 150000,
    description: '15-year long-term government savings scheme offering completely tax-free interest earnings and lump-sum maturity corpus.',
    eligibilityDescription: 'Indian resident citizens.',
    requiredDocs: ['Aadhaar Card', 'PAN Card', 'PPF Account Opening Form'],
    deadline: 'Post Offices & Authorized Commercial Banks',
    officialWebsiteUrl: 'https://nsiindia.gov.in',
    rules: { minAge: 18, maxAge: 80 },
    isPopular: true,
    iconName: 'savings'
  },
  {
    id: 'national-pension-system-nps-tier-1-tax-deduction-80ccd',
    title: 'National Pension System (NPS Tier-1 Extra ₹50,000 Tax Deduction under Sec 80CCD)',
    code: 'NPS-TIER1-PENSION-TAX',
    ministry: 'Pension Fund Regulatory and Development Authority (PFRDA)',
    origin: 'central',
    category: 'Banking, Financial Services & Insurance',
    subCategory: 'Retirement Planning & Investment',
    beneficiaries: ['General Citizen', 'Workers', 'Entrepreneurs'],
    benefitValue: 'Market-Linked Pension Annuity + Additional ₹50,000 Income Tax Exemption under Sec 80CCD(1B)',
    benefitNumericMin: 1000,
    benefitNumericMax: 200000,
    description: 'Voluntary defined contribution pension system allowing flexible investment allocation across equity, corporate bonds, and government debt.',
    eligibilityDescription: 'Indian citizens aged 18 to 70.',
    requiredDocs: ['PAN Card', 'Aadhaar Card', 'PRAN Application'],
    deadline: 'eNPS Portal (enps.nsdl.com)',
    officialWebsiteUrl: 'https://enps.nsdl.com',
    rules: { minAge: 18, maxAge: 70 },
    isPopular: true,
    iconName: 'account_balance'
  },

  // ==========================================
  // BUSINESS & ENTREPRENEURSHIP (46 SCHEMES)
  // ==========================================
  {
    id: 'pm-employment-generation-programme-pmegp-subsidy',
    title: 'Prime Minister’s Employment Generation Programme (PMEGP 35% Capital Subsidy)',
    code: 'PMEGP-CAPITAL-SUBSIDY',
    ministry: 'KVIC / Ministry of Micro, Small and Medium Enterprises (MSME)',
    origin: 'central',
    category: 'Business & Entrepreneurship',
    subCategory: 'MSME Capital Subsidy & Startup Loan',
    beneficiaries: ['Entrepreneurs', 'Job Seekers', 'Women', 'General Citizen'],
    benefitValue: 'Up to 35% Margin Money Capital Subsidy for Manufacturing (up to ₹50 Lakh) & Service Units (up to ₹20 Lakh)',
    benefitNumericMin: 100000,
    benefitNumericMax: 5000000,
    description: 'Credit-linked subsidy scheme generating self-employment opportunities through establishment of micro-enterprises in non-farm sector.',
    eligibilityDescription: 'Individuals above 18 years passing 8th class for manufacturing project above ₹10 Lakh.',
    requiredDocs: ['Project Detailed DPR', 'Educational Qualification Certificate', 'Aadhaar Card', 'Caste Certificate'],
    deadline: 'KVIC e-Portal (kviconline.gov.in)',
    officialWebsiteUrl: 'https://kviconline.gov.in',
    rules: { minAge: 18, maxAge: 65 },
    isPopular: true,
    iconName: 'business_center'
  },
  {
    id: 'credit-guarantee-fund-trust-for-micro-and-small-enterprises-cgtmse',
    title: 'CGTMSE Scheme (Collateral-Free Bank Loans up to ₹5 Crore for MSMEs)',
    code: 'CGTMSE-COLLATERAL-FREE-LOAN',
    ministry: 'Ministry of MSME & SIDBI',
    origin: 'central',
    category: 'Business & Entrepreneurship',
    subCategory: 'Credit Guarantee & MSME Finance',
    beneficiaries: ['Entrepreneurs', 'Workers'],
    benefitValue: '100% Collateral-Free Bank Business Loan Coverage up to ₹5.0 Crore with 85% Credit Risk Guarantee',
    benefitNumericMin: 500000,
    benefitNumericMax: 50000000,
    description: 'Enables new and existing small businesses to access bank credit without submitting third-party guarantees or real estate collateral.',
    eligibilityDescription: 'New and existing Micro and Small Enterprises (MSEs) in manufacturing and services.',
    requiredDocs: ['Udyam Registration Certificate', 'Project Business Plan', 'Audited Financials / ITR'],
    deadline: 'CGTMSE Official Portal (cgtmse.in)',
    officialWebsiteUrl: 'https://cgtmse.in',
    rules: { minAge: 18, maxAge: 70 },
    isPopular: true,
    iconName: 'verified_user'
  },
  {
    id: 'startup-india-seed-fund-scheme-sisfs-grant',
    title: 'Startup India Seed Fund Scheme (SISFS up to ₹50 Lakh Grant & Convertible Debentures)',
    code: 'SISFS-STARTUP-SEED-GRANT',
    ministry: 'DPIIT, Ministry of Commerce and Industry, Govt. of India',
    origin: 'central',
    category: 'Business & Entrepreneurship',
    subCategory: 'Tech Startups & Venture Seed Capital',
    beneficiaries: ['Entrepreneurs', 'Job Seekers'],
    benefitValue: 'Financial Grant up to ₹20 Lakh for Proof of Concept / Prototype + ₹50 Lakh for Commercialization',
    benefitNumericMin: 200000,
    benefitNumericMax: 5000000,
    description: 'Provides early-stage financial assistance to DPIIT-recognized startups for proof of concept, prototype development, and market entry.',
    eligibilityDescription: 'DPIIT-recognized startups incorporated within 2 years with innovative technology solution.',
    requiredDocs: ['DPIIT Startup Recognition Certificate', 'Pitch Deck', 'Certificate of Incorporation'],
    deadline: 'Startup India Seed Fund Portal (seedfund.startupindia.gov.in)',
    officialWebsiteUrl: 'https://seedfund.startupindia.gov.in',
    rules: { minAge: 18, maxAge: 60 },
    isPopular: true,
    iconName: 'rocket_launch'
  },
  {
    id: 'msme-champions-scheme-zed-certification-subsidy',
    title: 'MSME ZED Certification Scheme (Zero Defect Zero Effect 80% Subsidy)',
    code: 'MSME-ZED-CERTIFICATION',
    ministry: 'Ministry of Micro, Small and Medium Enterprises (MSME)',
    origin: 'central',
    category: 'Business & Entrepreneurship',
    subCategory: 'Quality Certification & Export Standards',
    beneficiaries: ['Entrepreneurs'],
    benefitValue: 'Up to 80% Financial Subsidy on ZED Certification Fee + ₹5.0 Lakh Financial Subsidy for Testing Equipment',
    benefitNumericMin: 10000,
    benefitNumericMax: 500000,
    description: 'Incentivizes MSMEs to manufacture zero-defect products with zero environmental impact, granting priority in bank loans and concessions.',
    eligibilityDescription: 'Micro, Small, and Medium Manufacturing Enterprises with valid Udyam Registration.',
    requiredDocs: ['Udyam Registration Number', 'Factory License', 'Aadhaar Card'],
    deadline: 'ZED MSME Portal (zed.msme.gov.in)',
    officialWebsiteUrl: 'https://zed.msme.gov.in',
    rules: { minAge: 18, maxAge: 75 },
    isPopular: true,
    iconName: 'verified'
  },
  {
    id: 'production-linked-incentive-pli-scheme-electronics',
    title: 'Production Linked Incentive Scheme (PLI 4% to 6% Cash Rebate on Incremental Sales)',
    code: 'PLI-ELECTRONICS-MANUFACTURING',
    ministry: 'Ministry of Electronics and IT / DPIIT / NITI Aayog',
    origin: 'central',
    category: 'Business & Entrepreneurship',
    subCategory: 'Industrial Manufacturing & Exports',
    beneficiaries: ['Entrepreneurs', 'Workers'],
    benefitValue: '4% to 6% Direct Cash Financial Incentive on Incremental Manufactured Sales over Base Year',
    benefitNumericMin: 1000000,
    benefitNumericMax: 100000000,
    description: 'Boosts domestic manufacturing in semiconductors, mobile phones, pharmaceuticals, solar PV modules, and automobiles.',
    eligibilityDescription: 'Manufacturing entities investing in specified greenfield industrial facilities.',
    requiredDocs: ['Company Incorporation Certificate', 'Audited Baseline Financial Statements', 'DPIIT Clearance'],
    deadline: 'PLI Portal (pliindia.org.in)',
    officialWebsiteUrl: 'https://pliindia.org.in',
    rules: { minAge: 21, maxAge: 70 },
    isPopular: true,
    iconName: 'precision_manufacturing'
  },
  {
    id: 'asPIRE-scheme-promotion-of-innovation-rural-industry',
    title: 'ASPIRE Scheme (A Scheme for Promotion of Innovation, Rural Industry & Entrepreneurship)',
    code: 'ASPIRE-RURAL-INCUBATION',
    ministry: 'Ministry of Micro, Small and Medium Enterprises (MSME)',
    origin: 'central',
    category: 'Business & Entrepreneurship',
    subCategory: 'Rural Business Incubation & Agro-Industry',
    beneficiaries: ['Entrepreneurs', 'Rural Citizens', 'Job Seekers'],
    benefitValue: '100% One-Time Financial Capital Grant up to ₹1.0 Crore for Establishing Livelihood Business Incubators (LBI)',
    benefitNumericMin: 500000,
    benefitNumericMax: 10000000,
    description: 'Sets up a network of technology and livelihood business incubators to create local employment in agro-based rural areas.',
    eligibilityDescription: 'Government agencies, universities, industry associations, and rural incubators.',
    requiredDocs: ['DPR for LBI / TBI', 'Organization Registration', 'Land Clearance'],
    deadline: 'ASPIRE Portal MSME (aspire.msme.gov.in)',
    officialWebsiteUrl: 'https://aspire.msme.gov.in',
    rules: { minAge: 21, maxAge: 65 },
    isPopular: false,
    iconName: 'domain'
  },
  {
    id: 'pradhan-mantri-formalisation-of-micro-food-processing-pmfme',
    title: 'PM Formalisation of Micro Food Processing Enterprises (PMFME 35% Credit Subsidy)',
    code: 'PMFME-FOOD-PROCESSING',
    ministry: 'Ministry of Food Processing Industries (MoFPI), Govt. of India',
    origin: 'central',
    category: 'Business & Entrepreneurship',
    subCategory: 'Food Processing & Agri-Business',
    beneficiaries: ['Entrepreneurs', 'Farmers', 'Women', 'Workers'],
    benefitValue: '35% Capital Financial Subsidy (Max ₹10 Lakh) + ₹40,000 Seed Capital per SHG Member for Food Equipment',
    benefitNumericMin: 40000,
    benefitNumericMax: 1000000,
    description: 'Upgrades unorganized micro food processors (pickles, spices, grain milling, bakery) under One District One Product (ODOP) framework.',
    eligibilityDescription: 'Existing micro food processing units, farmer cooperatives, and SHG members.',
    requiredDocs: ['FSSAI Food License', 'Aadhaar Card', 'Udyam Registration', 'Bank Passbook'],
    deadline: 'PMFME Official Portal (pmfme.mofpi.gov.in)',
    officialWebsiteUrl: 'https://pmfme.mofpi.gov.in',
    rules: { minAge: 18, maxAge: 65 },
    isPopular: true,
    iconName: 'restaurant'
  },
  {
    id: 'scheme-of-fund-for-regeneration-of-traditional-industries-sfurti',
    title: 'SFURTI Scheme (Scheme of Fund for Regeneration of Traditional Industries Grant)',
    code: 'SFURTI-TRADITIONAL-CLUSTER',
    ministry: 'Ministry of MSME, Govt. of India',
    origin: 'central',
    category: 'Business & Entrepreneurship',
    subCategory: 'Artisan Clusters & Khadi Promotion',
    beneficiaries: ['Workers', 'Entrepreneurs', 'Rural Citizens'],
    benefitValue: '100% Financial Grant up to ₹5.0 Crore per Artisan Cluster for Raw Material Banks & Common Facility Centres',
    benefitNumericMin: 5000000,
    benefitNumericMax: 50000000,
    description: 'Organizes traditional artisans (handloom, pottery, coir, bamboo, woodcraft) into competitive clusters with modern machinery.',
    eligibilityDescription: 'Non-government organizations (NGOs), field institutions of KVIC, and artisan cooperatives.',
    requiredDocs: ['Cluster Diagnostic Study Report', 'Artisan Registration Roll', 'Society Registration'],
    deadline: 'SFURTI Portal (sfurti.msme.gov.in)',
    officialWebsiteUrl: 'https://sfurti.msme.gov.in',
    rules: { minAge: 18, maxAge: 70 },
    isPopular: true,
    iconName: 'groups'
  },
  {
    id: 'procurement-and-marketing-support-pms-msme-trade-fair',
    title: 'MSME Trade Fair & International Exhibition Reimbursement Scheme (PMS Scheme)',
    code: 'PMS-MSME-EXHIBITION-GRANT',
    ministry: 'Ministry of Micro, Small and Medium Enterprises (MSME)',
    origin: 'central',
    category: 'Business & Entrepreneurship',
    subCategory: 'Marketing & Trade Fairs',
    beneficiaries: ['Entrepreneurs', 'Women'],
    benefitValue: '100% Stall Rent Reimbursement + 80% Airfare Subsidies for MSMEs Participating in National/International Trade Fairs',
    benefitNumericMin: 20000,
    benefitNumericMax: 250000,
    description: 'Assists small entrepreneurs to market their products nationally and internationally through trade exhibitions.',
    eligibilityDescription: 'Micro and Small Enterprises holding valid Udyam Registration.',
    requiredDocs: ['Udyam Registration', 'Trade Fair Stall Allotment Letter', 'Boarding Passes & Receipts'],
    deadline: 'MSME Mart Portal (msmemart.com)',
    officialWebsiteUrl: 'https://msmemart.com',
    rules: { minAge: 18, maxAge: 70 },
    isPopular: false,
    iconName: 'storefront'
  },
  {
    id: 'udyam-registration-portal-free-msme-certification',
    title: 'Udyam Registration Scheme (Zero-Cost Official Government MSME Certificate)',
    code: 'UDYAM-MSME-REGISTRATION',
    ministry: 'Ministry of MSME, Govt. of India',
    origin: 'central',
    category: 'Business & Entrepreneurship',
    subCategory: 'Business Registration & Compliance',
    beneficiaries: ['Entrepreneurs', 'Workers', 'Women', 'General Citizen'],
    benefitValue: 'Free Instant Digital MSME Certificate Unlocking Priority Bank Credit & 1% EMD Fee Exemptions in Govt Tenders',
    benefitNumericMin: 0,
    benefitNumericMax: 0,
    description: 'Official paperless online portal for registering micro, small, and medium enterprises based on self-declaration.',
    eligibilityDescription: 'Any proprietor, partnership firm, LLP, or private limited company in manufacturing or services.',
    requiredDocs: ['Aadhaar Card of Proprietor/Partner', 'GSTIN', 'PAN Card'],
    deadline: 'Udyam Official Portal (udyamregistration.gov.in)',
    officialWebsiteUrl: 'https://udyamregistration.gov.in',
    rules: { minAge: 18, maxAge: 80 },
    isPopular: true,
    iconName: 'badge'
  }
];

fs.writeFileSync('temp_batch1.json', JSON.stringify(batch1Schemes, null, 2));
console.log('Batch 1 generated successfully! Total schemes:', batch1Schemes.length);
